package ies

import "rrc/utils"

// AccessStratumReleaseSidelink-r16 ::= utils.ENUMERATED // Extensible
type AccessstratumreleasesidelinkR16 struct {
	Value utils.ENUMERATED
}

const (
	AccessstratumreleasesidelinkR16EnumeratedNothing = iota
	AccessstratumreleasesidelinkR16EnumeratedRel16
	AccessstratumreleasesidelinkR16EnumeratedRel17
	AccessstratumreleasesidelinkR16EnumeratedSpare6
	AccessstratumreleasesidelinkR16EnumeratedSpare5
	AccessstratumreleasesidelinkR16EnumeratedSpare4
	AccessstratumreleasesidelinkR16EnumeratedSpare3
	AccessstratumreleasesidelinkR16EnumeratedSpare2
	AccessstratumreleasesidelinkR16EnumeratedSpare1
)
