package ies

import "rrc/utils"

// AffectedCarrierFreqCombInfoMRDC-interferenceDirectionMRDC ::= ENUMERATED
type AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdc struct {
	Value utils.ENUMERATED
}

const (
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedNothing = iota
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedEutra_Nr
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedNr
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedOther
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedUtra_Nr_Other
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedNr_Other
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedSpare3
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedSpare2
	AffectedcarrierfreqcombinfomrdcInterferencedirectionmrdcEnumeratedSpare1
)
