package ies

import "rrc/utils"

// AffectedCarrierFreqCombInfoMRDC-r15-interferenceDirectionMRDC-r15 ::= ENUMERATED
type AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15 struct {
	Value utils.ENUMERATED
}

const (
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedNothing = iota
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedEutra_Nr
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedNr
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedOther
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedEutra_Nr_Other
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedNr_Other
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedSpare3
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedSpare2
	AffectedcarrierfreqcombinfomrdcR15InterferencedirectionmrdcR15EnumeratedSpare1
)
