package ies

import "rrc/utils"

// AffectedCarrierFreq-r16-interferenceDirection-r16 ::= ENUMERATED
type AffectedcarrierfreqR16InterferencedirectionR16 struct {
	Value utils.ENUMERATED
}

const (
	AffectedcarrierfreqR16InterferencedirectionR16EnumeratedNothing = iota
	AffectedcarrierfreqR16InterferencedirectionR16EnumeratedNr
	AffectedcarrierfreqR16InterferencedirectionR16EnumeratedOther
	AffectedcarrierfreqR16InterferencedirectionR16EnumeratedBoth
	AffectedcarrierfreqR16InterferencedirectionR16EnumeratedSpare
)
