package ies

import "rrc/utils"

// AntennaInfoDedicatedSTTI-r15-setup-transmissionModeDL-nonMBSFN-r15 ::= ENUMERATED
type AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15 struct {
	Value utils.ENUMERATED
}

const (
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedNothing = iota
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm1
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm2
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm3
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm4
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm6
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm8
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm9
	AntennainfodedicatedsttiR15SetupTransmissionmodedlNonmbsfnR15EnumeratedTm10
)
