package ies

import "rrc/utils"

// AntennaInfoDedicated-r10-transmissionMode-r10 ::= ENUMERATED
type AntennainfodedicatedR10TransmissionmodeR10 struct {
	Value utils.ENUMERATED
}

const (
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedNothing = iota
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm1
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm2
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm3
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm4
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm5
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm6
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm7
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm8_V920
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm9_V1020
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedTm10_V1130
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedSpare6
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedSpare5
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedSpare4
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedSpare3
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedSpare2
	AntennainfodedicatedR10TransmissionmodeR10EnumeratedSpare1
)
