package ies

import "rrc/utils"

// AUL-Config-r15-setup-aul-StartingPartialBW-OutsideMCOT-r15 ::= ENUMERATED
type AulConfigR15SetupAulStartingpartialbwOutsidemcotR15 struct {
	Value utils.ENUMERATED
}

const (
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedNothing = iota
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedO16
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedO25
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedO34
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedO43
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedO52
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedO61
	AulConfigR15SetupAulStartingpartialbwOutsidemcotR15EnumeratedOos1
)
