package ies

import "rrc/utils"

// AUL-Config-r15-setup-aul-RetransmissionTimer-r15 ::= ENUMERATED
type AulConfigR15SetupAulRetransmissiontimerR15 struct {
	Value utils.ENUMERATED
}

const (
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedNothing = iota
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf4
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf5
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf6
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf8
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf10
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf12
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf20
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf28
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf37
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf44
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf68
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf84
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf100
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf116
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf132
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf164
	AulConfigR15SetupAulRetransmissiontimerR15EnumeratedPsf324
)
