package ies

import "rrc/utils"

// BandNR-activeConfiguredGrant-r16-maxNumberConfigsPerBWP-r16 ::= ENUMERATED
type BandnrActiveconfiguredgrantR16MaxnumberconfigsperbwpR16 struct {
	Value utils.ENUMERATED
}

const (
	BandnrActiveconfiguredgrantR16MaxnumberconfigsperbwpR16EnumeratedNothing = iota
	BandnrActiveconfiguredgrantR16MaxnumberconfigsperbwpR16EnumeratedN1
	BandnrActiveconfiguredgrantR16MaxnumberconfigsperbwpR16EnumeratedN2
	BandnrActiveconfiguredgrantR16MaxnumberconfigsperbwpR16EnumeratedN4
	BandnrActiveconfiguredgrantR16MaxnumberconfigsperbwpR16EnumeratedN8
	BandnrActiveconfiguredgrantR16MaxnumberconfigsperbwpR16EnumeratedN12
)
