package ies

// BandParametersSidelinkDiscovery-r17-sl-TransmissionMode2-PartialSensing-r17-scs-CP-PatternTxSidelinkModeTwo-r17 ::= CHOICE
const (
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17ChoiceNothing = iota
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17ChoiceFr1R17
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17ChoiceFr2R17
)

type BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17 struct {
	Choice uint64
	Fr1R17 *BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17Fr1R17
	Fr2R17 *BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17Fr2R17
}
