package ies

import "rrc/utils"

// BandNR-maxUplinkDutyCycle-FR2 ::= ENUMERATED
type BandnrMaxuplinkdutycycleFr2 struct {
	Value utils.ENUMERATED
}

const (
	BandnrMaxuplinkdutycycleFr2EnumeratedNothing = iota
	BandnrMaxuplinkdutycycleFr2EnumeratedN15
	BandnrMaxuplinkdutycycleFr2EnumeratedN20
	BandnrMaxuplinkdutycycleFr2EnumeratedN25
	BandnrMaxuplinkdutycycleFr2EnumeratedN30
	BandnrMaxuplinkdutycycleFr2EnumeratedN40
	BandnrMaxuplinkdutycycleFr2EnumeratedN50
	BandnrMaxuplinkdutycycleFr2EnumeratedN60
	BandnrMaxuplinkdutycycleFr2EnumeratedN70
	BandnrMaxuplinkdutycycleFr2EnumeratedN80
	BandnrMaxuplinkdutycycleFr2EnumeratedN90
	BandnrMaxuplinkdutycycleFr2EnumeratedN100
)
