package ies

// BandParametersSidelinkEUTRA-NR-v1710-nr-sl-TransmissionMode2-PartialSensing-r17-scs-CP-PatternTxSidelinkModeTwo-r17 ::= CHOICE
const (
	BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17ChoiceNothing = iota
	BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17ChoiceFr1R17
	BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17ChoiceFr2R17
)

type BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17 struct {
	Choice uint64
	Fr1R17 *BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17Fr1R17
	Fr2R17 *BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17Fr2R17
}
