package ies

import "rrc/utils"

// BandNR-dynamicSlotRepetitionMulticastNTN-SharedSpectrumChAccess-r17 ::= ENUMERATED
type BandnrDynamicslotrepetitionmulticastntnSharedspectrumchaccessR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrDynamicslotrepetitionmulticastntnSharedspectrumchaccessR17EnumeratedNothing = iota
	BandnrDynamicslotrepetitionmulticastntnSharedspectrumchaccessR17EnumeratedN8
	BandnrDynamicslotrepetitionmulticastntnSharedspectrumchaccessR17EnumeratedN16
)
