package ies

import "rrc/utils"

// BandNR-enhancedType3-HARQ-CodebookFeedback-r17-enhancedType3-HARQ-Codebooks-r17 ::= ENUMERATED
type BandnrEnhancedtype3HarqCodebookfeedbackR17Enhancedtype3HarqCodebooksR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrEnhancedtype3HarqCodebookfeedbackR17Enhancedtype3HarqCodebooksR17EnumeratedNothing = iota
	BandnrEnhancedtype3HarqCodebookfeedbackR17Enhancedtype3HarqCodebooksR17EnumeratedN1
	BandnrEnhancedtype3HarqCodebookfeedbackR17Enhancedtype3HarqCodebooksR17EnumeratedN2
	BandnrEnhancedtype3HarqCodebookfeedbackR17Enhancedtype3HarqCodebooksR17EnumeratedN4
	BandnrEnhancedtype3HarqCodebookfeedbackR17Enhancedtype3HarqCodebooksR17EnumeratedN8
)
