package ies

import "rrc/utils"

// BandParametersSidelinkEUTRA-NR-v1710-nr-sl-TransmissionMode2-PartialSensing-r17-harq-TxProcessModeTwoSidelink-r17 ::= ENUMERATED
type BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17 struct {
	Value utils.ENUMERATED
}

const (
	BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17EnumeratedNothing = iota
	BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17EnumeratedN8
	BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17EnumeratedN16
)
