package ies

import "rrc/utils"

// BandSidelink-r16-ue-PowerClassSidelink-r16 ::= ENUMERATED
type BandsidelinkR16UePowerclasssidelinkR16 struct {
	Value utils.ENUMERATED
}

const (
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedNothing = iota
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedPc2
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedPc3
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedSpare6
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedSpare5
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedSpare4
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedSpare3
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedSpare2
	BandsidelinkR16UePowerclasssidelinkR16EnumeratedSpare1
)
