package ies

import "rrc/utils"

// BandSidelink-r16-sl-TransmissionMode2-RandomResourceSelection-r17-harq-TxProcessModeTwoSidelink-r17 ::= ENUMERATED
type BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17HarqTxprocessmodetwosidelinkR17 struct {
	Value utils.ENUMERATED
}

const (
	BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17HarqTxprocessmodetwosidelinkR17EnumeratedNothing = iota
	BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17HarqTxprocessmodetwosidelinkR17EnumeratedN8
	BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17HarqTxprocessmodetwosidelinkR17EnumeratedN16
)
