package ies

import "rrc/utils"

// BandCombination-UplinkTxSwitch-r16-uplinkTxSwitching-PUSCH-TransCoherence-r16 ::= ENUMERATED
type BandcombinationUplinktxswitchR16UplinktxswitchingPuschTranscoherenceR16 struct {
	Value utils.ENUMERATED
}

const (
	BandcombinationUplinktxswitchR16UplinktxswitchingPuschTranscoherenceR16EnumeratedNothing = iota
	BandcombinationUplinktxswitchR16UplinktxswitchingPuschTranscoherenceR16EnumeratedNoncoherent
	BandcombinationUplinktxswitchR16UplinktxswitchingPuschTranscoherenceR16EnumeratedFullcoherent
)
