package ies

// BandParametersSidelinkEUTRA-NR-v1710-nr-sl-TransmissionMode2-PartialSensing-r17 ::= SEQUENCE
type BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17 struct {
	HarqTxprocessmodetwosidelinkR17  BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17
	ScsCpPatterntxsidelinkmodetwoR17 *BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17
	ExtendedcpMode2partialsensingR17 *BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17ExtendedcpMode2partialsensingR17
	DlOpenlooppcSidelinkR17          *BandparameterssidelinkeutraNrV1710NrSlTransmissionmode2PartialsensingR17DlOpenlooppcSidelinkR17
}
