package ies

import "rrc/utils"

// BandNR-enhancedType3-HARQ-CodebookFeedback-r17-maxNumberPUCCH-Transmissions-r17 ::= ENUMERATED
type BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedNothing = iota
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedN1
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedN2
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedN3
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedN4
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedN5
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedN6
	BandnrEnhancedtype3HarqCodebookfeedbackR17MaxnumberpucchTransmissionsR17EnumeratedN7
)
