package ies

import "rrc/utils"

// BandNR-aperiodicCSI-RS-FastScellActivation-r17-maxNumberAperiodicCSI-RS-PerCC-r17 ::= ENUMERATED
type BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedNothing = iota
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedN8
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedN16
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedN32
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedN48
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedN64
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedN128
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsPerccR17EnumeratedN255
)
