package ies

import "rrc/utils"

// BandSidelinkEUTRA-r16-gnb-ScheduledMode3SidelinkEUTRA-r16-gnb-ScheduledMode3DelaySidelinkEUTRA-r16 ::= ENUMERATED
type BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16 struct {
	Value utils.ENUMERATED
}

const (
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedNothing = iota
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs0
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs0dot25
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs0dot5
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs0dot625
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs0dot75
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs1
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs1dot25
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs1dot5
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs1dot75
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs2
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs2dot5
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs3
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs4
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs5
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs6
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs8
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs10
	BandsidelinkeutraR16GnbScheduledmode3sidelinkeutraR16GnbScheduledmode3delaysidelinkeutraR16EnumeratedMs20
)
