package ies

import "rrc/utils"

// BandParametersSidelinkDiscovery-r17-sl-TransmissionMode2-PartialSensing-r17-dl-openLoopPC-Sidelink-r17 ::= ENUMERATED
type BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17DlOpenlooppcSidelinkR17 struct {
	Value utils.ENUMERATED
}

const (
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17DlOpenlooppcSidelinkR17EnumeratedNothing = iota
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17DlOpenlooppcSidelinkR17EnumeratedSupported
)
