package ies

// BandParametersSidelinkDiscovery-r17-sl-TransmissionMode2-PartialSensing-r17 ::= SEQUENCE
type BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17 struct {
	HarqTxprocessmodetwosidelinkR17  BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17
	ScsCpPatterntxsidelinkmodetwoR17 *BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ScsCpPatterntxsidelinkmodetwoR17
	ExtendedcpMode2partialsensingR17 *BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17ExtendedcpMode2partialsensingR17
	DlOpenlooppcSidelinkR17          *BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17DlOpenlooppcSidelinkR17
}
