package ies

// BandSidelink-r16-sl-TransmissionMode2-RandomResourceSelection-r17-scs-CP-PatternTxSidelinkModeTwo-r17 ::= CHOICE
const (
	BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17ScsCpPatterntxsidelinkmodetwoR17ChoiceNothing = iota
	BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17ScsCpPatterntxsidelinkmodetwoR17ChoiceFr1R17
	BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17ScsCpPatterntxsidelinkmodetwoR17ChoiceFr2R17
)

type BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17ScsCpPatterntxsidelinkmodetwoR17 struct {
	Choice uint64
	Fr1R17 *BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17ScsCpPatterntxsidelinkmodetwoR17Fr1R17
	Fr2R17 *BandsidelinkR16SlTransmissionmode2RandomresourceselectionR17ScsCpPatterntxsidelinkmodetwoR17Fr2R17
}
