package ies

import "rrc/utils"

// BandNR-triggeredHARQ-CodebookRetx-r17-maxHARQ-Retx-Offset-r17 ::= ENUMERATED
type BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedNothing = iota
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN4
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN6
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN8
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN10
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN12
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN14
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN16
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN18
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN20
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN22
	BandnrTriggeredharqCodebookretxR17MaxharqRetxOffsetR17EnumeratedN24
)
