package ies

import "rrc/utils"

// BandNR-srs-SemiPersistent-PosResourcesRRC-Inactive-r17-maxNumOfSemiPersistentSRSposResourcesPerSlot-r17 ::= ENUMERATED
type BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedNothing = iota
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN1
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN2
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN3
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN4
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN5
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN6
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN8
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN10
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN12
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN14
)
