package ies

import "rrc/utils"

// BandNR-aperiodicCSI-RS-FastScellActivation-r17-maxNumberAperiodicCSI-RS-AcrossCCs-r17 ::= ENUMERATED
type BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedNothing = iota
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN8
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN16
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN32
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN64
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN128
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN256
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN512
	BandnrAperiodiccsiRsFastscellactivationR17MaxnumberaperiodiccsiRsAcrossccsR17EnumeratedN1024
)
