package ies

import "rrc/utils"

// BandSidelinkPC5-r16-sl-Reception-r16-harq-RxProcessSidelink-r16 ::= ENUMERATED
type Bandsidelinkpc5R16SlReceptionR16HarqRxprocesssidelinkR16 struct {
	Value utils.ENUMERATED
}

const (
	Bandsidelinkpc5R16SlReceptionR16HarqRxprocesssidelinkR16EnumeratedNothing = iota
	Bandsidelinkpc5R16SlReceptionR16HarqRxprocesssidelinkR16EnumeratedN16
	Bandsidelinkpc5R16SlReceptionR16HarqRxprocesssidelinkR16EnumeratedN24
	Bandsidelinkpc5R16SlReceptionR16HarqRxprocesssidelinkR16EnumeratedN32
	Bandsidelinkpc5R16SlReceptionR16HarqRxprocesssidelinkR16EnumeratedN64
)
