package ies

import "rrc/utils"

// BandNR-srs-SemiPersistent-PosResourcesRRC-Inactive-r17-maxNumOfSemiPersistentSRSposResources-r17 ::= ENUMERATED
type BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17 struct {
	Value utils.ENUMERATED
}

const (
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedNothing = iota
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN1
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN2
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN4
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN8
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN16
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN32
	BandnrSrsSemipersistentPosresourcesrrcInactiveR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN64
)
