package ies

import "rrc/utils"

// BandParametersSidelinkDiscovery-r17-sl-TransmissionMode2-PartialSensing-r17-harq-TxProcessModeTwoSidelink-r17 ::= ENUMERATED
type BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17 struct {
	Value utils.ENUMERATED
}

const (
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17EnumeratedNothing = iota
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17EnumeratedN8
	BandparameterssidelinkdiscoveryR17SlTransmissionmode2PartialsensingR17HarqTxprocessmodetwosidelinkR17EnumeratedN16
)
