package ies

import "rrc/utils"

// BandCombinationParameters-v1610-interFreqDAPS-r16-interFreqMultiUL-TransmissionDAPS-r16 ::= ENUMERATED
type BandcombinationparametersV1610InterfreqdapsR16InterfreqmultiulTransmissiondapsR16 struct {
	Value utils.ENUMERATED
}

const (
	BandcombinationparametersV1610InterfreqdapsR16InterfreqmultiulTransmissiondapsR16EnumeratedNothing = iota
	BandcombinationparametersV1610InterfreqdapsR16InterfreqmultiulTransmissiondapsR16EnumeratedSupported
)
