package ies

import "rrc/utils"

// BandSidelink-r16-psfch-FormatZeroSidelink-r16-psfch-RxNumber ::= ENUMERATED
type BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumber struct {
	Value utils.ENUMERATED
}

const (
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedNothing = iota
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN5
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN15
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN25
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN32
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN35
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN45
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN50
	BandsidelinkR16PsfchFormatzerosidelinkR16PsfchRxnumberEnumeratedN64
)
