package ies

import "rrc/utils"

// BandParametersSidelinkEUTRA-NR-v1710-nr-rx-sidelinkPSFCH-r17 ::= ENUMERATED
type BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17 struct {
	Value utils.ENUMERATED
}

const (
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedNothing = iota
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN5
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN15
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN25
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN32
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN35
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN45
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN50
	BandparameterssidelinkeutraNrV1710NrRxSidelinkpsfchR17EnumeratedN64
)
