package ies

import "rrc/utils"

// BarringPerACDC-Category-r13-acdc-BarringConfig-r13-ac-BarringTime-r13 ::= ENUMERATED
type BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13 struct {
	Value utils.ENUMERATED
}

const (
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedNothing = iota
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS4
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS8
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS16
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS32
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS64
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS128
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS256
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringtimeR13EnumeratedS512
)
