package ies

import "rrc/utils"

// BarringPerACDC-Category-r13-acdc-BarringConfig-r13-ac-BarringFactor-r13 ::= ENUMERATED
type BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13 struct {
	Value utils.ENUMERATED
}

const (
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedNothing = iota
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP00
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP05
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP10
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP15
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP20
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP25
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP30
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP40
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP50
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP60
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP70
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP75
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP80
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP85
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP90
	BarringperacdcCategoryR13AcdcBarringconfigR13AcBarringfactorR13EnumeratedP95
)
