package ies

import "rrc/utils"

// BeamFailureDetectionSet-r17-beamFailureDetectionTimer-r17 ::= ENUMERATED
type BeamfailuredetectionsetR17BeamfailuredetectiontimerR17 struct {
	Value utils.ENUMERATED
}

const (
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedNothing = iota
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd1
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd2
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd3
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd4
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd5
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd6
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd8
	BeamfailuredetectionsetR17BeamfailuredetectiontimerR17EnumeratedPbfd10
)
