package ies

import "rrc/utils"

// BeamFailureDetectionSet-r17-beamFailureInstanceMaxCount-r17 ::= ENUMERATED
type BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17 struct {
	Value utils.ENUMERATED
}

const (
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedNothing = iota
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN1
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN2
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN3
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN4
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN5
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN6
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN8
	BeamfailuredetectionsetR17BeamfailureinstancemaxcountR17EnumeratedN10
)
