package ies

import "rrc/utils"

// BFD-RelaxationReportingConfig-r17-bfd-RelaxtionReportingProhibitTimer ::= ENUMERATED
type BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimer struct {
	Value utils.ENUMERATED
}

const (
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedNothing = iota
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS0
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS0dot5
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS1
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS2
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS5
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS10
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS20
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS30
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS60
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS90
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS120
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS300
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedS600
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedInfinity
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedSpare2
	BfdRelaxationreportingconfigR17BfdRelaxtionreportingprohibittimerEnumeratedSpare1
)
