package ies

import "rrc/utils"

// BSR-Config-periodicBSR-Timer ::= ENUMERATED
type BsrConfigPeriodicbsrTimer struct {
	Value utils.ENUMERATED
}

const (
	BsrConfigPeriodicbsrTimerEnumeratedNothing = iota
	BsrConfigPeriodicbsrTimerEnumeratedSf1
	BsrConfigPeriodicbsrTimerEnumeratedSf5
	BsrConfigPeriodicbsrTimerEnumeratedSf10
	BsrConfigPeriodicbsrTimerEnumeratedSf16
	BsrConfigPeriodicbsrTimerEnumeratedSf20
	BsrConfigPeriodicbsrTimerEnumeratedSf32
	BsrConfigPeriodicbsrTimerEnumeratedSf40
	BsrConfigPeriodicbsrTimerEnumeratedSf64
	BsrConfigPeriodicbsrTimerEnumeratedSf80
	BsrConfigPeriodicbsrTimerEnumeratedSf128
	BsrConfigPeriodicbsrTimerEnumeratedSf160
	BsrConfigPeriodicbsrTimerEnumeratedSf320
	BsrConfigPeriodicbsrTimerEnumeratedSf640
	BsrConfigPeriodicbsrTimerEnumeratedSf1280
	BsrConfigPeriodicbsrTimerEnumeratedSf2560
	BsrConfigPeriodicbsrTimerEnumeratedInfinity
)
