package ies

import "rrc/utils"

// BSR-Config-retxBSR-Timer ::= ENUMERATED
type BsrConfigRetxbsrTimer struct {
	Value utils.ENUMERATED
}

const (
	BsrConfigRetxbsrTimerEnumeratedNothing = iota
	BsrConfigRetxbsrTimerEnumeratedSf10
	BsrConfigRetxbsrTimerEnumeratedSf20
	BsrConfigRetxbsrTimerEnumeratedSf40
	BsrConfigRetxbsrTimerEnumeratedSf80
	BsrConfigRetxbsrTimerEnumeratedSf160
	BsrConfigRetxbsrTimerEnumeratedSf320
	BsrConfigRetxbsrTimerEnumeratedSf640
	BsrConfigRetxbsrTimerEnumeratedSf1280
	BsrConfigRetxbsrTimerEnumeratedSf2560
	BsrConfigRetxbsrTimerEnumeratedSf5120
	BsrConfigRetxbsrTimerEnumeratedSf10240
	BsrConfigRetxbsrTimerEnumeratedSpare5
	BsrConfigRetxbsrTimerEnumeratedSpare4
	BsrConfigRetxbsrTimerEnumeratedSpare3
	BsrConfigRetxbsrTimerEnumeratedSpare2
	BsrConfigRetxbsrTimerEnumeratedSpare1
)
