package ies

import "rrc/utils"

// CA-ParametersNR-v1720-dynamicPUCCH-CellSwitchDiffLengthSingleGroup-r17-pucch-Group-r17 ::= ENUMERATED
type CaParametersnrV1720DynamicpucchCellswitchdifflengthsinglegroupR17PucchGroupR17 struct {
	Value utils.ENUMERATED
}

const (
	CaParametersnrV1720DynamicpucchCellswitchdifflengthsinglegroupR17PucchGroupR17EnumeratedNothing = iota
	CaParametersnrV1720DynamicpucchCellswitchdifflengthsinglegroupR17PucchGroupR17EnumeratedPrimarygrouponly
	CaParametersnrV1720DynamicpucchCellswitchdifflengthsinglegroupR17PucchGroupR17EnumeratedSecondarygrouponly
	CaParametersnrV1720DynamicpucchCellswitchdifflengthsinglegroupR17PucchGroupR17EnumeratedEitherprimaryorsecondarygroup
)
