package ies

import "rrc/utils"

// CA-ParametersNR-v1720-semiStaticPUCCH-CellSwitchSingleGroup-r17-pucch-Group-r17 ::= ENUMERATED
type CaParametersnrV1720SemistaticpucchCellswitchsinglegroupR17PucchGroupR17 struct {
	Value utils.ENUMERATED
}

const (
	CaParametersnrV1720SemistaticpucchCellswitchsinglegroupR17PucchGroupR17EnumeratedNothing = iota
	CaParametersnrV1720SemistaticpucchCellswitchsinglegroupR17PucchGroupR17EnumeratedPrimarygrouponly
	CaParametersnrV1720SemistaticpucchCellswitchsinglegroupR17PucchGroupR17EnumeratedSecondarygrouponly
	CaParametersnrV1720SemistaticpucchCellswitchsinglegroupR17PucchGroupR17EnumeratedEitherprimaryorsecondarygroup
)
