package ies

import "rrc/utils"

// CA-ParametersNR-v1610-pdcch-MonitoringCA-r16-supportedSpanArrangement-r16 ::= ENUMERATED
type CaParametersnrV1610PdcchMonitoringcaR16SupportedspanarrangementR16 struct {
	Value utils.ENUMERATED
}

const (
	CaParametersnrV1610PdcchMonitoringcaR16SupportedspanarrangementR16EnumeratedNothing = iota
	CaParametersnrV1610PdcchMonitoringcaR16SupportedspanarrangementR16EnumeratedAlignedonly
	CaParametersnrV1610PdcchMonitoringcaR16SupportedspanarrangementR16EnumeratedAlignedandnonaligned
)
