package ies

import "rrc/utils"

// CA-ParametersNR-v1630-intraBandFreqSeparationUL-AggBW-GapBW-r16 ::= ENUMERATED
type CaParametersnrV1630IntrabandfreqseparationulAggbwGapbwR16 struct {
	Value utils.ENUMERATED
}

const (
	CaParametersnrV1630IntrabandfreqseparationulAggbwGapbwR16EnumeratedNothing = iota
	CaParametersnrV1630IntrabandfreqseparationulAggbwGapbwR16EnumeratedClassi
	CaParametersnrV1630IntrabandfreqseparationulAggbwGapbwR16EnumeratedClassii
	CaParametersnrV1630IntrabandfreqseparationulAggbwGapbwR16EnumeratedClassiii
)
