package ies

import "rrc/utils"

// CA-ParametersNR-v1690-csi-ReportingCrossPUCCH-Grp-r16-computationTimeForA-CSI-r16 ::= ENUMERATED
type CaParametersnrV1690CsiReportingcrosspucchGrpR16ComputationtimeforaCsiR16 struct {
	Value utils.ENUMERATED
}

const (
	CaParametersnrV1690CsiReportingcrosspucchGrpR16ComputationtimeforaCsiR16EnumeratedNothing = iota
	CaParametersnrV1690CsiReportingcrosspucchGrpR16ComputationtimeforaCsiR16EnumeratedSameasnocross
	CaParametersnrV1690CsiReportingcrosspucchGrpR16ComputationtimeforaCsiR16EnumeratedRelaxed
)
