package ies

import "rrc/utils"

// CarrierFreqNBIOT-r16-carrierFreqOffset-r16 ::= ENUMERATED
type CarrierfreqnbiotR16CarrierfreqoffsetR16 struct {
	Value utils.ENUMERATED
}

const (
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedNothing = iota
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_10
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_9
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_8dot5
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_8
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_7
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_6
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_5
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_4dot5
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_4
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_3
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_2
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_1
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV_0dot5
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV0
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV1
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV2
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV3
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV3dot5
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV4
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV5
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV6
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV7
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV7dot5
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV8
	CarrierfreqnbiotR16CarrierfreqoffsetR16EnumeratedV9
)
