package ies

import "rrc/utils"

// CarrierBandwidthEUTRA-ul-Bandwidth ::= ENUMERATED
type CarrierbandwidtheutraUlBandwidth struct {
	Value utils.ENUMERATED
}

const (
	CarrierbandwidtheutraUlBandwidthEnumeratedNothing = iota
	CarrierbandwidtheutraUlBandwidthEnumeratedN6
	CarrierbandwidtheutraUlBandwidthEnumeratedN15
	CarrierbandwidtheutraUlBandwidthEnumeratedN25
	CarrierbandwidtheutraUlBandwidthEnumeratedN50
	CarrierbandwidtheutraUlBandwidthEnumeratedN75
	CarrierbandwidtheutraUlBandwidthEnumeratedN100
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare10
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare9
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare8
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare7
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare6
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare5
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare4
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare3
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare2
	CarrierbandwidtheutraUlBandwidthEnumeratedSpare1
)
