package ies

import "rrc/utils"

// CarrierFreq-NB-r13-carrierFreqOffset-r13 ::= ENUMERATED
type CarrierfreqNbR13CarrierfreqoffsetR13 struct {
	Value utils.ENUMERATED
}

const (
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedNothing = iota
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_10
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_9
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_8
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_7
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_6
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_5
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_4
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_3
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_2
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_1
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV_0dot5
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV0
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV1
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV2
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV3
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV4
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV5
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV6
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV7
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV8
	CarrierfreqNbR13CarrierfreqoffsetR13EnumeratedV9
)
