package ies

// CarrierAggregationVariant ::= SEQUENCE
type Carrieraggregationvariant struct {
	Fr1fddFr1tddCaSpcellonfr1fdd       *CarrieraggregationvariantFr1fddFr1tddCaSpcellonfr1fdd
	Fr1fddFr1tddCaSpcellonfr1tdd       *CarrieraggregationvariantFr1fddFr1tddCaSpcellonfr1tdd
	Fr1fddFr2tddCaSpcellonfr1fdd       *CarrieraggregationvariantFr1fddFr2tddCaSpcellonfr1fdd
	Fr1fddFr2tddCaSpcellonfr2tdd       *CarrieraggregationvariantFr1fddFr2tddCaSpcellonfr2tdd
	Fr1tddFr2tddCaSpcellonfr1tdd       *CarrieraggregationvariantFr1tddFr2tddCaSpcellonfr1tdd
	Fr1tddFr2tddCaSpcellonfr2tdd       *CarrieraggregationvariantFr1tddFr2tddCaSpcellonfr2tdd
	Fr1fddFr1tddFr2tddCaSpcellonfr1fdd *CarrieraggregationvariantFr1fddFr1tddFr2tddCaSpcellonfr1fdd
	Fr1fddFr1tddFr2tddCaSpcellonfr1tdd *CarrieraggregationvariantFr1fddFr1tddFr2tddCaSpcellonfr1tdd
	Fr1fddFr1tddFr2tddCaSpcellonfr2tdd *CarrieraggregationvariantFr1fddFr1tddFr2tddCaSpcellonfr2tdd
}
