package ies

// CE-ResourceResvParameters-r16 ::= SEQUENCE
type CeResourceresvparametersR16 struct {
	SubframeresourceresvdlCeModeaR16   *CeResourceresvparametersR16SubframeresourceresvdlCeModeaR16
	SubframeresourceresvdlCeModebR16   *CeResourceresvparametersR16SubframeresourceresvdlCeModebR16
	SubframeresourceresvulCeModeaR16   *CeResourceresvparametersR16SubframeresourceresvulCeModeaR16
	SubframeresourceresvulCeModebR16   *CeResourceresvparametersR16SubframeresourceresvulCeModebR16
	SlotsymbolresourceresvdlCeModeaR16 *CeResourceresvparametersR16SlotsymbolresourceresvdlCeModeaR16
	SlotsymbolresourceresvdlCeModebR16 *CeResourceresvparametersR16SlotsymbolresourceresvdlCeModebR16
	SlotsymbolresourceresvulCeModeaR16 *CeResourceresvparametersR16SlotsymbolresourceresvulCeModeaR16
	SlotsymbolresourceresvulCeModebR16 *CeResourceresvparametersR16SlotsymbolresourceresvulCeModebR16
	SubcarrierpuncturingceModeaR16     *CeResourceresvparametersR16SubcarrierpuncturingceModeaR16
	SubcarrierpuncturingceModebR16     *CeResourceresvparametersR16SubcarrierpuncturingceModebR16
}
