package ies

import "rrc/utils"

// CFRA-TwoStep-r16-occasionsTwoStepRA-r16-ssb-PerRACH-OccasionTwoStepRA-r16 ::= ENUMERATED
type CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16 struct {
	Value utils.ENUMERATED
}

const (
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedNothing = iota
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedOneeighth
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedOnefourth
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedOnehalf
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedOne
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedTwo
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedFour
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedEight
	CfraTwostepR16OccasionstwostepraR16SsbPerrachOccasiontwostepraR16EnumeratedSixteen
)
