package ies

import "rrc/utils"

// CG-SDT-Configuration-r17-sdt-Alpha-r17 ::= ENUMERATED
type CgSdtConfigurationR17SdtAlphaR17 struct {
	Value utils.ENUMERATED
}

const (
	CgSdtConfigurationR17SdtAlphaR17EnumeratedNothing = iota
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha0
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha04
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha05
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha06
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha07
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha08
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha09
	CgSdtConfigurationR17SdtAlphaR17EnumeratedAlpha1
)
