package ies

import "rrc/utils"

// CG-SDT-TA-ValidationConfig-r17-cg-SDT-RSRP-ChangeThreshold-r17 ::= ENUMERATED
type CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17 struct {
	Value utils.ENUMERATED
}

const (
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedNothing = iota
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb2
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb4
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb6
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb8
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb10
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb14
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb18
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb22
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb26
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb30
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedDb34
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedSpare5
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedSpare4
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedSpare3
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedSpare2
	CgSdtTaValidationconfigR17CgSdtRsrpChangethresholdR17EnumeratedSpare1
)
