package ies

import "rrc/utils"

// CI-ConfigurationPerServingCell-r16-ci-PayloadSize-r16 ::= ENUMERATED
type CiConfigurationperservingcellR16CiPayloadsizeR16 struct {
	Value utils.ENUMERATED
}

const (
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedNothing = iota
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN1
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN2
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN4
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN5
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN7
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN8
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN10
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN14
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN16
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN20
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN28
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN32
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN35
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN42
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN56
	CiConfigurationperservingcellR16CiPayloadsizeR16EnumeratedN112
)
