package ies

import "rrc/utils"

// CI-ConfigurationPerServingCell-r16-timeFrequencyRegion-r16-timeGranularityForCI-r16 ::= ENUMERATED
type CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16 struct {
	Value utils.ENUMERATED
}

const (
	CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16EnumeratedNothing = iota
	CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16EnumeratedN1
	CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16EnumeratedN2
	CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16EnumeratedN4
	CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16EnumeratedN7
	CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16EnumeratedN14
	CiConfigurationperservingcellR16TimefrequencyregionR16TimegranularityforciR16EnumeratedN28
)
