package ies

import "rrc/utils"

// CodebookConfig-r17-codebookType-type1-typeI-SinglePanel-Group1-r17-nrOfAntennaPorts-moreThanTwo-n1-n2 ::= CHOICE
const (
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceNothing = iota
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceTwoOneTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceTwoTwoTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceFourOneTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceThreeTwoTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceSixOneTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceFourTwoTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceEightOneTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceFourThreeTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceSixTwoTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceTwelveOneTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceFourFourTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceEightTwoTypeiSinglepanelRestriction1R17
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2ChoiceSixteenOneTypeiSinglepanelRestriction1R17
)

type CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwoN1N2 struct {
	Choice                                    uint64
	TwoOneTypeiSinglepanelRestriction1R17     *utils.BITSTRING `lb:8,ub:8`
	TwoTwoTypeiSinglepanelRestriction1R17     *utils.BITSTRING `lb:64,ub:64`
	FourOneTypeiSinglepanelRestriction1R17    *utils.BITSTRING `lb:16,ub:16`
	ThreeTwoTypeiSinglepanelRestriction1R17   *utils.BITSTRING `lb:96,ub:96`
	SixOneTypeiSinglepanelRestriction1R17     *utils.BITSTRING `lb:24,ub:24`
	FourTwoTypeiSinglepanelRestriction1R17    *utils.BITSTRING `lb:128,ub:128`
	EightOneTypeiSinglepanelRestriction1R17   *utils.BITSTRING `lb:32,ub:32`
	FourThreeTypeiSinglepanelRestriction1R17  *utils.BITSTRING `lb:192,ub:192`
	SixTwoTypeiSinglepanelRestriction1R17     *utils.BITSTRING `lb:192,ub:192`
	TwelveOneTypeiSinglepanelRestriction1R17  *utils.BITSTRING `lb:48,ub:48`
	FourFourTypeiSinglepanelRestriction1R17   *utils.BITSTRING `lb:256,ub:256`
	EightTwoTypeiSinglepanelRestriction1R17   *utils.BITSTRING `lb:256,ub:256`
	SixteenOneTypeiSinglepanelRestriction1R17 *utils.BITSTRING `lb:64,ub:64`
}
