package ies

// CodebookConfig-codebookType-type1-subType-typeI-SinglePanel-nrOfAntennaPorts ::= CHOICE
const (
	CodebookconfigCodebooktypeType1SubtypeTypeiSinglepanelNrofantennaportsChoiceNothing = iota
	CodebookconfigCodebooktypeType1SubtypeTypeiSinglepanelNrofantennaportsChoiceTwo
	CodebookconfigCodebooktypeType1SubtypeTypeiSinglepanelNrofantennaportsChoiceMorethantwo
)

type CodebookconfigCodebooktypeType1SubtypeTypeiSinglepanelNrofantennaports struct {
	Choice      uint64
	Two         *CodebookconfigCodebooktypeType1SubtypeTypeiSinglepanelNrofantennaportsTwo
	Morethantwo *CodebookconfigCodebooktypeType1SubtypeTypeiSinglepanelNrofantennaportsMorethantwo
}
