package ies

import "rrc/utils"

// CodebookConfig-r16-codebookType-type2-subType-typeII-PortSelection-r16-portSelectionSamplingSize-r16 ::= ENUMERATED
type CodebookconfigR16CodebooktypeType2SubtypeTypeiiPortselectionR16PortselectionsamplingsizeR16 struct {
	Value utils.ENUMERATED
}

const (
	CodebookconfigR16CodebooktypeType2SubtypeTypeiiPortselectionR16PortselectionsamplingsizeR16EnumeratedNothing = iota
	CodebookconfigR16CodebooktypeType2SubtypeTypeiiPortselectionR16PortselectionsamplingsizeR16EnumeratedN1
	CodebookconfigR16CodebooktypeType2SubtypeTypeiiPortselectionR16PortselectionsamplingsizeR16EnumeratedN2
	CodebookconfigR16CodebooktypeType2SubtypeTypeiiPortselectionR16PortselectionsamplingsizeR16EnumeratedN3
	CodebookconfigR16CodebooktypeType2SubtypeTypeiiPortselectionR16PortselectionsamplingsizeR16EnumeratedN4
)
