package ies

// CodebookConfig-r17-codebookType-type1-typeI-SinglePanel-Group1-r17-nrOfAntennaPorts ::= CHOICE
const (
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsChoiceNothing = iota
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsChoiceTwo
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsChoiceMorethantwo
)

type CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17Nrofantennaports struct {
	Choice      uint64
	Two         *CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsTwo
	Morethantwo *CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup1R17NrofantennaportsMorethantwo
}
