package ies

// CodebookConfig-r17-codebookType-type1-typeI-SinglePanel-Group2-r17-nrOfAntennaPorts ::= CHOICE
const (
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup2R17NrofantennaportsChoiceNothing = iota
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup2R17NrofantennaportsChoiceTwo
	CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup2R17NrofantennaportsChoiceMorethantwo
)

type CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup2R17Nrofantennaports struct {
	Choice      uint64
	Two         *CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup2R17NrofantennaportsTwo
	Morethantwo *CodebookconfigR17CodebooktypeType1TypeiSinglepanelGroup2R17NrofantennaportsMorethantwo
}
