package ies

import "rrc/utils"

// CodebookConfig-codebookType-type2-subType-typeII-PortSelection-portSelectionSamplingSize ::= ENUMERATED
type CodebookconfigCodebooktypeType2SubtypeTypeiiPortselectionPortselectionsamplingsize struct {
	Value utils.ENUMERATED
}

const (
	CodebookconfigCodebooktypeType2SubtypeTypeiiPortselectionPortselectionsamplingsizeEnumeratedNothing = iota
	CodebookconfigCodebooktypeType2SubtypeTypeiiPortselectionPortselectionsamplingsizeEnumeratedN1
	CodebookconfigCodebooktypeType2SubtypeTypeiiPortselectionPortselectionsamplingsizeEnumeratedN2
	CodebookconfigCodebooktypeType2SubtypeTypeiiPortselectionPortselectionsamplingsizeEnumeratedN3
	CodebookconfigCodebooktypeType2SubtypeTypeiiPortselectionPortselectionsamplingsizeEnumeratedN4
)
