package ies

import "rrc/utils"

// ConfiguredGrantConfig-cg-minDFI-Delay-r16 ::= ENUMERATED
type ConfiguredgrantconfigCgMindfiDelayR16 struct {
	Value utils.ENUMERATED
}

const (
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedNothing = iota
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym7
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym1x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym2x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym3x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym4x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym5x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym6x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym7x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym8x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym9x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym10x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym11x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym12x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym13x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym14x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym15x14
	ConfiguredgrantconfigCgMindfiDelayR16EnumeratedSym16x14
)
