package ies

import "rrc/utils"

// ConfiguredGrantConfig-rrc-ConfiguredUplinkGrant-frequencyHoppingPUSCH-RepTypeB-r16 ::= ENUMERATED
type ConfiguredgrantconfigRrcConfigureduplinkgrantFrequencyhoppingpuschReptypebR16 struct {
	Value utils.ENUMERATED
}

const (
	ConfiguredgrantconfigRrcConfigureduplinkgrantFrequencyhoppingpuschReptypebR16EnumeratedNothing = iota
	ConfiguredgrantconfigRrcConfigureduplinkgrantFrequencyhoppingpuschReptypebR16EnumeratedInterrepetition
	ConfiguredgrantconfigRrcConfigureduplinkgrantFrequencyhoppingpuschReptypebR16EnumeratedInterslot
)
