package ies

import "rrc/utils"

// ConfiguredGrantConfig-periodicity ::= ENUMERATED
type ConfiguredgrantconfigPeriodicity struct {
	Value utils.ENUMERATED
}

const (
	ConfiguredgrantconfigPeriodicityEnumeratedNothing = iota
	ConfiguredgrantconfigPeriodicityEnumeratedSym2
	ConfiguredgrantconfigPeriodicityEnumeratedSym7
	ConfiguredgrantconfigPeriodicityEnumeratedSym1x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym2x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym4x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym5x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym8x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym10x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym16x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym20x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym32x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym40x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym64x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym80x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym128x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym160x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym256x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym320x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym512x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym640x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym1024x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym1280x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym2560x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym5120x14
	ConfiguredgrantconfigPeriodicityEnumeratedSym6
	ConfiguredgrantconfigPeriodicityEnumeratedSym1x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym2x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym4x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym5x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym8x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym10x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym16x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym20x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym32x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym40x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym64x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym80x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym128x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym160x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym256x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym320x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym512x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym640x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym1280x12
	ConfiguredgrantconfigPeriodicityEnumeratedSym2560x12
)
