package ies

import "rrc/utils"

// ConnEstFailureControl-connEstFailOffsetValidity ::= ENUMERATED
type ConnestfailurecontrolConnestfailoffsetvalidity struct {
	Value utils.ENUMERATED
}

const (
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedNothing = iota
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS30
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS60
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS120
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS240
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS300
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS420
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS600
	ConnestfailurecontrolConnestfailoffsetvalidityEnumeratedS900
)
