package ies

import "rrc/utils"

// CQI-NPDCCH-NB-r14 ::= ENUMERATED
type CqiNpdcchNbR14 struct {
	Value utils.ENUMERATED
}

const (
	CqiNpdcchNbR14EnumeratedNothing = iota
	CqiNpdcchNbR14EnumeratedNomeasurements
	CqiNpdcchNbR14EnumeratedCandidaterep_A
	CqiNpdcchNbR14EnumeratedCandidaterep_B
	CqiNpdcchNbR14EnumeratedCandidaterep_C
	CqiNpdcchNbR14EnumeratedCandidaterep_D
	CqiNpdcchNbR14EnumeratedCandidaterep_E
	CqiNpdcchNbR14EnumeratedCandidaterep_F
	CqiNpdcchNbR14EnumeratedCandidaterep_G
	CqiNpdcchNbR14EnumeratedCandidaterep_H
	CqiNpdcchNbR14EnumeratedCandidaterep_I
	CqiNpdcchNbR14EnumeratedCandidaterep_J
	CqiNpdcchNbR14EnumeratedCandidaterep_K
	CqiNpdcchNbR14EnumeratedCandidaterep_L
)
