package ies

import "rrc/utils"

// CQI-ReportPeriodic-r10-setup-cqi-FormatIndicatorPeriodic-r10-widebandCQI-r10-csi-ReportMode-r10 ::= ENUMERATED
type CqiReportperiodicR10SetupCqiFormatindicatorperiodicR10WidebandcqiR10CsiReportmodeR10 struct {
	Value utils.ENUMERATED
}

const (
	CqiReportperiodicR10SetupCqiFormatindicatorperiodicR10WidebandcqiR10CsiReportmodeR10EnumeratedNothing = iota
	CqiReportperiodicR10SetupCqiFormatindicatorperiodicR10WidebandcqiR10CsiReportmodeR10EnumeratedSubmode1
	CqiReportperiodicR10SetupCqiFormatindicatorperiodicR10WidebandcqiR10CsiReportmodeR10EnumeratedSubmode2
)
