package ies

import "rrc/utils"

// CQI-ReportPeriodicSCell-r15-setup-cqi-FormatIndicatorDormant-r15-subbandCQI-r15-periodicityFactor-r15 ::= ENUMERATED
type CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15SubbandcqiR15PeriodicityfactorR15 struct {
	Value utils.ENUMERATED
}

const (
	CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15SubbandcqiR15PeriodicityfactorR15EnumeratedNothing = iota
	CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15SubbandcqiR15PeriodicityfactorR15EnumeratedN2
	CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15SubbandcqiR15PeriodicityfactorR15EnumeratedN4
)
