package ies

import "rrc/utils"

// CQI-ReportAperiodic-v1250-setup-aperiodicCSI-Trigger-v1250-trigger-SubframeSetIndicator-r12 ::= ENUMERATED
type CqiReportaperiodicV1250SetupAperiodiccsiTriggerV1250TriggerSubframesetindicatorR12 struct {
	Value utils.ENUMERATED
}

const (
	CqiReportaperiodicV1250SetupAperiodiccsiTriggerV1250TriggerSubframesetindicatorR12EnumeratedNothing = iota
	CqiReportaperiodicV1250SetupAperiodiccsiTriggerV1250TriggerSubframesetindicatorR12EnumeratedS1
	CqiReportaperiodicV1250SetupAperiodiccsiTriggerV1250TriggerSubframesetindicatorR12EnumeratedS2
)
