package ies

import "rrc/utils"

// CQI-ReportPeriodicSCell-r15-setup-cqi-FormatIndicatorDormant-r15-widebandCQI-r15-csi-ReportMode-r15 ::= ENUMERATED
type CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15WidebandcqiR15CsiReportmodeR15 struct {
	Value utils.ENUMERATED
}

const (
	CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15WidebandcqiR15CsiReportmodeR15EnumeratedNothing = iota
	CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15WidebandcqiR15CsiReportmodeR15EnumeratedSubmode1
	CqiReportperiodicscellR15SetupCqiFormatindicatordormantR15WidebandcqiR15CsiReportmodeR15EnumeratedSubmode2
)
