package ies

// CrossCarrierSchedulingConfig-r10-schedulingCellInfo-r10 ::= CHOICE
const (
	CrosscarrierschedulingconfigR10SchedulingcellinfoR10ChoiceNothing = iota
	CrosscarrierschedulingconfigR10SchedulingcellinfoR10ChoiceOwnR10
	CrosscarrierschedulingconfigR10SchedulingcellinfoR10ChoiceOtherR10
)

type CrosscarrierschedulingconfigR10SchedulingcellinfoR10 struct {
	Choice   uint64
	OwnR10   *CrosscarrierschedulingconfigR10SchedulingcellinfoR10OwnR10
	OtherR10 *CrosscarrierschedulingconfigR10SchedulingcellinfoR10OtherR10
}
