package ies

import "rrc/utils"

// CrossCarrierSchedulingConfig-ccs-BlindDetectionSplit-r17 ::= ENUMERATED
type CrosscarrierschedulingconfigCcsBlinddetectionsplitR17 struct {
	Value utils.ENUMERATED
}

const (
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedNothing = iota
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedOneseventh
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedThreefourteenth
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedTwoseventh
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedThreeseventh
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedOnehalf
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedFourseventh
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedFiveseventh
	CrosscarrierschedulingconfigCcsBlinddetectionsplitR17EnumeratedSpare1
)
