package ies

import "rrc/utils"

// CRS-ChEstMPDCCH-ConfigCommon-r16-powerRatio-r16 ::= ENUMERATED
type CrsChestmpdcchConfigcommonR16PowerratioR16 struct {
	Value utils.ENUMERATED
}

const (
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedNothing = iota
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb_4dot77
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb_3
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb_1dot77
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb0
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb1
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb2
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb3
	CrsChestmpdcchConfigcommonR16PowerratioR16EnumeratedDb4dot77
)
