package ies

import "rrc/utils"

// CRS-ChEstMPDCCH-ConfigDedicated-r16-localizedMappingType-r16 ::= ENUMERATED
type CrsChestmpdcchConfigdedicatedR16LocalizedmappingtypeR16 struct {
	Value utils.ENUMERATED
}

const (
	CrsChestmpdcchConfigdedicatedR16LocalizedmappingtypeR16EnumeratedNothing = iota
	CrsChestmpdcchConfigdedicatedR16LocalizedmappingtypeR16EnumeratedPredefined
	CrsChestmpdcchConfigdedicatedR16LocalizedmappingtypeR16EnumeratedCsi_Based
	CrsChestmpdcchConfigdedicatedR16LocalizedmappingtypeR16EnumeratedReciprocitybased
)
