package ies

import "rrc/utils"

// CRS-ChEstMPDCCH-ConfigDedicated-r16-powerRatio-r16 ::= ENUMERATED
type CrsChestmpdcchConfigdedicatedR16PowerratioR16 struct {
	Value utils.ENUMERATED
}

const (
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedNothing = iota
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb_4dot77
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb_3
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb_1dot77
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb0
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb1
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb2
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb3
	CrsChestmpdcchConfigdedicatedR16PowerratioR16EnumeratedDb4dot77
)
