package ies

// CSG-ProximityIndicationParameters-r9 ::= SEQUENCE
type CsgProximityindicationparametersR9 struct {
	IntrafreqproximityindicationR9 *CsgProximityindicationparametersR9IntrafreqproximityindicationR9
	InterfreqproximityindicationR9 *CsgProximityindicationparametersR9InterfreqproximityindicationR9
	UtranProximityindicationR9     *CsgProximityindicationparametersR9UtranProximityindicationR9
}
