package ies

import "rrc/utils"

// CSI-MultiTRP-SupportedCombinations-r17-maxNumTx-Ports-r17 ::= ENUMERATED
type CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17 struct {
	Value utils.ENUMERATED
}

const (
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedNothing = iota
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedN2
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedN4
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedN8
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedN12
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedN16
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedN24
	CsiMultitrpSupportedcombinationsR17MaxnumtxPortsR17EnumeratedN32
)
