package ies

import "rrc/utils"

// CSI-ReportFramework-maxNumberAperiodicCSI-triggeringStatePerCC ::= ENUMERATED
type CsiReportframeworkMaxnumberaperiodiccsiTriggeringstatepercc struct {
	Value utils.ENUMERATED
}

const (
	CsiReportframeworkMaxnumberaperiodiccsiTriggeringstateperccEnumeratedNothing = iota
	CsiReportframeworkMaxnumberaperiodiccsiTriggeringstateperccEnumeratedN3
	CsiReportframeworkMaxnumberaperiodiccsiTriggeringstateperccEnumeratedN7
	CsiReportframeworkMaxnumberaperiodiccsiTriggeringstateperccEnumeratedN15
	CsiReportframeworkMaxnumberaperiodiccsiTriggeringstateperccEnumeratedN31
	CsiReportframeworkMaxnumberaperiodiccsiTriggeringstateperccEnumeratedN63
	CsiReportframeworkMaxnumberaperiodiccsiTriggeringstateperccEnumeratedN128
)
