package ies

import "rrc/utils"

// CSI-ReportConfig-reportConfigType-semiPersistentOnPUSCH-reportSlotConfig ::= ENUMERATED
type CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfig struct {
	Value utils.ENUMERATED
}

const (
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedNothing = iota
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedSl5
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedSl10
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedSl20
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedSl40
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedSl80
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedSl160
	CsiReportconfigReportconfigtypeSemipersistentonpuschReportslotconfigEnumeratedSl320
)
