package ies

import "rrc/utils"

// CSI-ReportConfig-groupBasedBeamReporting-v1710-nrofReportedGroups-r17 ::= ENUMERATED
type CsiReportconfigGroupbasedbeamreportingV1710NrofreportedgroupsR17 struct {
	Value utils.ENUMERATED
}

const (
	CsiReportconfigGroupbasedbeamreportingV1710NrofreportedgroupsR17EnumeratedNothing = iota
	CsiReportconfigGroupbasedbeamreportingV1710NrofreportedgroupsR17EnumeratedN1
	CsiReportconfigGroupbasedbeamreportingV1710NrofreportedgroupsR17EnumeratedN2
	CsiReportconfigGroupbasedbeamreportingV1710NrofreportedgroupsR17EnumeratedN3
	CsiReportconfigGroupbasedbeamreportingV1710NrofreportedgroupsR17EnumeratedN4
)
