package ies

import "rrc/utils"

// DAPS-UplinkPowerConfig-r16-uplinkPowerSharingDAPS-Mode-r16 ::= ENUMERATED
type DapsUplinkpowerconfigR16UplinkpowersharingdapsModeR16 struct {
	Value utils.ENUMERATED
}

const (
	DapsUplinkpowerconfigR16UplinkpowersharingdapsModeR16EnumeratedNothing = iota
	DapsUplinkpowerconfigR16UplinkpowersharingdapsModeR16EnumeratedSemi_Static_Mode1
	DapsUplinkpowerconfigR16UplinkpowersharingdapsModeR16EnumeratedSemi_Static_Mode2
	DapsUplinkpowerconfigR16UplinkpowersharingdapsModeR16EnumeratedDynamic
)
