package ies

import "rrc/utils"

// DataInactivityTimer-r14 ::= ENUMERATED
type DatainactivitytimerR14 struct {
	Value utils.ENUMERATED
}

const (
	DatainactivitytimerR14EnumeratedNothing = iota
	DatainactivitytimerR14EnumeratedS1
	DatainactivitytimerR14EnumeratedS2
	DatainactivitytimerR14EnumeratedS3
	DatainactivitytimerR14EnumeratedS5
	DatainactivitytimerR14EnumeratedS7
	DatainactivitytimerR14EnumeratedS10
	DatainactivitytimerR14EnumeratedS15
	DatainactivitytimerR14EnumeratedS20
	DatainactivitytimerR14EnumeratedS40
	DatainactivitytimerR14EnumeratedS50
	DatainactivitytimerR14EnumeratedS60
	DatainactivitytimerR14EnumeratedS80
	DatainactivitytimerR14EnumeratedS100
	DatainactivitytimerR14EnumeratedS120
	DatainactivitytimerR14EnumeratedS150
	DatainactivitytimerR14EnumeratedS180
)
