package ies

import "rrc/utils"

// DataInactivityTimer ::= ENUMERATED
type Datainactivitytimer struct {
	Value utils.ENUMERATED
}

const (
	DatainactivitytimerEnumeratedNothing = iota
	DatainactivitytimerEnumeratedS1
	DatainactivitytimerEnumeratedS2
	DatainactivitytimerEnumeratedS3
	DatainactivitytimerEnumeratedS5
	DatainactivitytimerEnumeratedS7
	DatainactivitytimerEnumeratedS10
	DatainactivitytimerEnumeratedS15
	DatainactivitytimerEnumeratedS20
	DatainactivitytimerEnumeratedS40
	DatainactivitytimerEnumeratedS50
	DatainactivitytimerEnumeratedS60
	DatainactivitytimerEnumeratedS80
	DatainactivitytimerEnumeratedS100
	DatainactivitytimerEnumeratedS120
	DatainactivitytimerEnumeratedS150
	DatainactivitytimerEnumeratedS180
)
