package ies

import "rrc/utils"

// DeltaFList-SPUCCH-r15-setup-deltaF-slotSPUCCH-Format1a-r15 ::= ENUMERATED
type DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15 struct {
	Value utils.ENUMERATED
}

const (
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedNothing = iota
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf1
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf2
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf3
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf4
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf5
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf6
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf7
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1aR15EnumeratedDeltaf8
)
