package ies

import "rrc/utils"

// DeltaFList-SPUCCH-r15-setup-deltaF-slotSPUCCH-TBCC-Format4-r15 ::= ENUMERATED
type DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15 struct {
	Value utils.ENUMERATED
}

const (
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedNothing = iota
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf10
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf11
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf12
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf13
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf14
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf15
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf16
	DeltaflistSpucchR15SetupDeltafSlotspucchTbccFormat4R15EnumeratedDeltaf17
)
