package ies

import "rrc/utils"

// DeltaFList-SPUCCH-r15-setup-deltaF-subslotSPUCCH-Format1and1a-r15 ::= ENUMERATED
type DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15 struct {
	Value utils.ENUMERATED
}

const (
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedNothing = iota
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf5
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf6
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf7
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf8
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf9
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf10
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf11
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1and1aR15EnumeratedDeltaf12
)
