package ies

import "rrc/utils"

// DeltaFList-SPUCCH-r15-setup-deltaF-subslotSPUCCH-TBCC-Format4-r15 ::= ENUMERATED
type DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15 struct {
	Value utils.ENUMERATED
}

const (
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedNothing = iota
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf10
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf11
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf12
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf13
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf14
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf15
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf16
	DeltaflistSpucchR15SetupDeltafSubslotspucchTbccFormat4R15EnumeratedDeltaf17
)
