package ies

import "rrc/utils"

// DeltaFList-SPUCCH-r15-setup-deltaF-slotSPUCCH-Format1-r15 ::= ENUMERATED
type DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15 struct {
	Value utils.ENUMERATED
}

const (
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedNothing = iota
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf_1
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf0
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf1
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf2
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf3
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf4
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf5
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1R15EnumeratedDeltaf6
)
