package ies

import "rrc/utils"

// DeltaFList-SPUCCH-r15-setup-deltaF-subslotSPUCCH-Format1b-r15 ::= ENUMERATED
type DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15 struct {
	Value utils.ENUMERATED
}

const (
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedNothing = iota
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf6
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf7
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf8
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf9
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf10
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf11
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf12
	DeltaflistSpucchR15SetupDeltafSubslotspucchFormat1bR15EnumeratedDeltaf13
)
