package ies

import "rrc/utils"

// DeltaFList-SPUCCH-r15-setup-deltaF-slotSPUCCH-Format1b-r15 ::= ENUMERATED
type DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15 struct {
	Value utils.ENUMERATED
}

const (
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedNothing = iota
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf3
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf4
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf5
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf6
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf7
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf8
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf9
	DeltaflistSpucchR15SetupDeltafSlotspucchFormat1bR15EnumeratedDeltaf10
)
