package ies

import "rrc/utils"

// DL-CarrierConfigCommon-NB-r14-inbandCarrierInfo-r14-samePCI-Indicator-r14-differentPCI-r14-eutra-NumCRS-Ports-r14 ::= ENUMERATED
type DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14DifferentpciR14EutraNumcrsPortsR14 struct {
	Value utils.ENUMERATED
}

const (
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14DifferentpciR14EutraNumcrsPortsR14EnumeratedNothing = iota
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14DifferentpciR14EutraNumcrsPortsR14EnumeratedSame
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14DifferentpciR14EutraNumcrsPortsR14EnumeratedFour
)
