package ies

import "rrc/utils"

// DL-CarrierConfigDedicated-NB-r13-inbandCarrierInfo-r13-eutraControlRegionSize-r13 ::= ENUMERATED
type DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13EutracontrolregionsizeR13 struct {
	Value utils.ENUMERATED
}

const (
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13EutracontrolregionsizeR13EnumeratedNothing = iota
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13EutracontrolregionsizeR13EnumeratedN1
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13EutracontrolregionsizeR13EnumeratedN2
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13EutracontrolregionsizeR13EnumeratedN3
)
