package ies

import "rrc/utils"

// DL-CarrierConfigDedicated-NB-r13-inbandCarrierInfo-r13-samePCI-Indicator-r13-differentPCI-r13-eutra-NumCRS-Ports-r13 ::= ENUMERATED
type DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13DifferentpciR13EutraNumcrsPortsR13 struct {
	Value utils.ENUMERATED
}

const (
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13DifferentpciR13EutraNumcrsPortsR13EnumeratedNothing = iota
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13DifferentpciR13EutraNumcrsPortsR13EnumeratedSame
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13DifferentpciR13EutraNumcrsPortsR13EnumeratedFour
)
