package ies

// DL-CarrierConfigDedicated-NB-r13-inbandCarrierInfo-r13-samePCI-Indicator-r13 ::= CHOICE
const (
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13ChoiceNothing = iota
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13ChoiceSamepciR13
	DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13ChoiceDifferentpciR13
)

type DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13 struct {
	Choice          uint64
	SamepciR13      *DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13SamepciR13
	DifferentpciR13 *DlCarrierconfigdedicatedNbR13InbandcarrierinfoR13SamepciIndicatorR13DifferentpciR13
}
