package ies

// DL-CarrierConfigCommon-NB-r14-inbandCarrierInfo-r14-samePCI-Indicator-r14 ::= CHOICE
const (
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14ChoiceNothing = iota
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14ChoiceSamepciR14
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14ChoiceDifferentpciR14
)

type DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14 struct {
	Choice          uint64
	SamepciR14      *DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14SamepciR14
	DifferentpciR14 *DlCarrierconfigcommonNbR14InbandcarrierinfoR14SamepciIndicatorR14DifferentpciR14
}
