package ies

import "rrc/utils"

// DL-CarrierConfigCommon-NB-r14-inbandCarrierInfo-r14-eutraControlRegionSize-r14 ::= ENUMERATED
type DlCarrierconfigcommonNbR14InbandcarrierinfoR14EutracontrolregionsizeR14 struct {
	Value utils.ENUMERATED
}

const (
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14EutracontrolregionsizeR14EnumeratedNothing = iota
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14EutracontrolregionsizeR14EnumeratedN1
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14EutracontrolregionsizeR14EnumeratedN2
	DlCarrierconfigcommonNbR14InbandcarrierinfoR14EutracontrolregionsizeR14EnumeratedN3
)
