package ies

import "rrc/utils"

// DMRS-BundlingPUSCH-Config-r17-pusch-FrequencyHoppingInterval-r17 ::= ENUMERATED
type DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17 struct {
	Value utils.ENUMERATED
}

const (
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedNothing = iota
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS2
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS4
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS5
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS6
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS8
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS10
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS12
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS14
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS16
	DmrsBundlingpuschConfigR17PuschFrequencyhoppingintervalR17EnumeratedS20
)
