package ies

import "rrc/utils"

// DRX-ConfigSecondaryGroup-r16-drx-InactivityTimer-r16 ::= ENUMERATED
type DrxConfigsecondarygroupR16DrxInactivitytimerR16 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedNothing = iota
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs0
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs1
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs2
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs3
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs4
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs5
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs6
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs8
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs10
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs20
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs30
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs40
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs50
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs60
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs80
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs100
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs200
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs300
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs500
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs750
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs1280
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs1920
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedMs2560
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare9
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare8
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare7
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare6
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare5
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare4
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare3
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare2
	DrxConfigsecondarygroupR16DrxInactivitytimerR16EnumeratedSpare1
)
