package ies

import "rrc/utils"

// DRX-ConfigSL-r17-drx-RetransmissionTimerSL-r17 ::= ENUMERATED
type DrxConfigslR17DrxRetransmissiontimerslR17 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedNothing = iota
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl0
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl1
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl2
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl4
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl6
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl8
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl16
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl24
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl33
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl40
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl64
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl80
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl96
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl112
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl128
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl160
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSl320
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare15
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare14
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare13
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare12
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare11
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare10
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare9
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare8
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare7
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare6
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare5
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare4
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare3
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare2
	DrxConfigslR17DrxRetransmissiontimerslR17EnumeratedSpare1
)
