package ies

import "rrc/utils"

// DRX-Config-setup-shortDRX-shortDRX-Cycle ::= ENUMERATED
type DrxConfigSetupShortdrxShortdrxCycle struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedNothing = iota
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf2
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf5
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf8
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf10
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf16
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf20
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf32
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf40
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf64
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf80
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf128
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf160
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf256
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf320
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf512
	DrxConfigSetupShortdrxShortdrxCycleEnumeratedSf640
)
