package ies

import "rrc/utils"

// DRX-Config-drx-RetransmissionTimerDL ::= ENUMERATED
type DrxConfigDrxRetransmissiontimerdl struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigDrxRetransmissiontimerdlEnumeratedNothing = iota
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl0
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl1
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl2
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl4
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl6
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl8
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl16
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl24
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl33
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl40
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl64
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl80
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl96
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl112
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl128
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl160
	DrxConfigDrxRetransmissiontimerdlEnumeratedSl320
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare15
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare14
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare13
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare12
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare11
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare10
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare9
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare8
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare7
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare6
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare5
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare4
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare3
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare2
	DrxConfigDrxRetransmissiontimerdlEnumeratedSpare1
)
