package ies

import "rrc/utils"

// DRX-Config-shortDRX-drx-ShortCycle ::= ENUMERATED
type DrxConfigShortdrxDrxShortcycle struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigShortdrxDrxShortcycleEnumeratedNothing = iota
	DrxConfigShortdrxDrxShortcycleEnumeratedMs2
	DrxConfigShortdrxDrxShortcycleEnumeratedMs3
	DrxConfigShortdrxDrxShortcycleEnumeratedMs4
	DrxConfigShortdrxDrxShortcycleEnumeratedMs5
	DrxConfigShortdrxDrxShortcycleEnumeratedMs6
	DrxConfigShortdrxDrxShortcycleEnumeratedMs7
	DrxConfigShortdrxDrxShortcycleEnumeratedMs8
	DrxConfigShortdrxDrxShortcycleEnumeratedMs10
	DrxConfigShortdrxDrxShortcycleEnumeratedMs14
	DrxConfigShortdrxDrxShortcycleEnumeratedMs16
	DrxConfigShortdrxDrxShortcycleEnumeratedMs20
	DrxConfigShortdrxDrxShortcycleEnumeratedMs30
	DrxConfigShortdrxDrxShortcycleEnumeratedMs32
	DrxConfigShortdrxDrxShortcycleEnumeratedMs35
	DrxConfigShortdrxDrxShortcycleEnumeratedMs40
	DrxConfigShortdrxDrxShortcycleEnumeratedMs64
	DrxConfigShortdrxDrxShortcycleEnumeratedMs80
	DrxConfigShortdrxDrxShortcycleEnumeratedMs128
	DrxConfigShortdrxDrxShortcycleEnumeratedMs160
	DrxConfigShortdrxDrxShortcycleEnumeratedMs256
	DrxConfigShortdrxDrxShortcycleEnumeratedMs320
	DrxConfigShortdrxDrxShortcycleEnumeratedMs512
	DrxConfigShortdrxDrxShortcycleEnumeratedMs640
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare9
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare8
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare7
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare6
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare5
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare4
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare3
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare2
	DrxConfigShortdrxDrxShortcycleEnumeratedSpare1
)
