package ies

import "rrc/utils"

// DRX-Config-r13-drx-ULRetransmissionTimer-r13 ::= ENUMERATED
type DrxConfigR13DrxUlretransmissiontimerR13 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedNothing = iota
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf0
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf1
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf2
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf4
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf6
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf8
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf16
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf24
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf33
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf40
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf64
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf80
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf96
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf112
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf128
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf160
	DrxConfigR13DrxUlretransmissiontimerR13EnumeratedPsf320
)
