package ies

import "rrc/utils"

// DRX-Config-drx-RetransmissionTimerUL ::= ENUMERATED
type DrxConfigDrxRetransmissiontimerul struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigDrxRetransmissiontimerulEnumeratedNothing = iota
	DrxConfigDrxRetransmissiontimerulEnumeratedSl0
	DrxConfigDrxRetransmissiontimerulEnumeratedSl1
	DrxConfigDrxRetransmissiontimerulEnumeratedSl2
	DrxConfigDrxRetransmissiontimerulEnumeratedSl4
	DrxConfigDrxRetransmissiontimerulEnumeratedSl6
	DrxConfigDrxRetransmissiontimerulEnumeratedSl8
	DrxConfigDrxRetransmissiontimerulEnumeratedSl16
	DrxConfigDrxRetransmissiontimerulEnumeratedSl24
	DrxConfigDrxRetransmissiontimerulEnumeratedSl33
	DrxConfigDrxRetransmissiontimerulEnumeratedSl40
	DrxConfigDrxRetransmissiontimerulEnumeratedSl64
	DrxConfigDrxRetransmissiontimerulEnumeratedSl80
	DrxConfigDrxRetransmissiontimerulEnumeratedSl96
	DrxConfigDrxRetransmissiontimerulEnumeratedSl112
	DrxConfigDrxRetransmissiontimerulEnumeratedSl128
	DrxConfigDrxRetransmissiontimerulEnumeratedSl160
	DrxConfigDrxRetransmissiontimerulEnumeratedSl320
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare15
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare14
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare13
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare12
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare11
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare10
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare9
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare8
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare7
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare6
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare5
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare4
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare3
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare2
	DrxConfigDrxRetransmissiontimerulEnumeratedSpare1
)
