package ies

import "rrc/utils"

// DRX-ConfigPTM-r17-drx-RetransmissionTimerDL-PTM-r17 ::= ENUMERATED
type DrxConfigptmR17DrxRetransmissiontimerdlPtmR17 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedNothing = iota
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl0
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl1
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl2
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl4
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl6
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl8
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl16
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl24
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl33
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl40
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl64
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl80
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl96
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl112
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl128
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl160
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSl320
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare15
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare14
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare13
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare12
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare11
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare10
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare9
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare8
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare7
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare6
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare5
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare4
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare3
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare2
	DrxConfigptmR17DrxRetransmissiontimerdlPtmR17EnumeratedSpare1
)
