package ies

import "rrc/utils"

// DRX-Config-r15-drx-UL-RetransmissionTimerShortTTI-r15 ::= ENUMERATED
type DrxConfigR15DrxUlRetransmissiontimershortttiR15 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedNothing = iota
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti0
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti1
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti2
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti4
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti6
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti8
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti16
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti24
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti33
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti40
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti64
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti80
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti96
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti112
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti128
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti160
	DrxConfigR15DrxUlRetransmissiontimershortttiR15EnumeratedTti320
)
