package ies

import "rrc/utils"

// DRX-Config-NB-r13-setup-drx-RetransmissionTimer-r13 ::= ENUMERATED
type DrxConfigNbR13SetupDrxRetransmissiontimerR13 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedNothing = iota
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp0
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp1
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp2
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp4
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp6
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp8
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp16
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp24
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedPp33
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedSpare7
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedSpare6
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedSpare5
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedSpare4
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedSpare3
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedSpare2
	DrxConfigNbR13SetupDrxRetransmissiontimerR13EnumeratedSpare1
)
