package ies

import "rrc/utils"

// DRX-Config-setup-drx-InactivityTimer ::= ENUMERATED
type DrxConfigSetupDrxInactivitytimer struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigSetupDrxInactivitytimerEnumeratedNothing = iota
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf1
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf2
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf3
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf4
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf5
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf6
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf8
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf10
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf20
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf30
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf40
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf50
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf60
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf80
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf100
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf200
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf300
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf500
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf750
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf1280
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf1920
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf2560
	DrxConfigSetupDrxInactivitytimerEnumeratedPsf0_V1020
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare9
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare8
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare7
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare6
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare5
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare4
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare3
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare2
	DrxConfigSetupDrxInactivitytimerEnumeratedSpare1
)
