package ies

import "rrc/utils"

// DRX-Config-drx-InactivityTimer ::= ENUMERATED
type DrxConfigDrxInactivitytimer struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigDrxInactivitytimerEnumeratedNothing = iota
	DrxConfigDrxInactivitytimerEnumeratedMs0
	DrxConfigDrxInactivitytimerEnumeratedMs1
	DrxConfigDrxInactivitytimerEnumeratedMs2
	DrxConfigDrxInactivitytimerEnumeratedMs3
	DrxConfigDrxInactivitytimerEnumeratedMs4
	DrxConfigDrxInactivitytimerEnumeratedMs5
	DrxConfigDrxInactivitytimerEnumeratedMs6
	DrxConfigDrxInactivitytimerEnumeratedMs8
	DrxConfigDrxInactivitytimerEnumeratedMs10
	DrxConfigDrxInactivitytimerEnumeratedMs20
	DrxConfigDrxInactivitytimerEnumeratedMs30
	DrxConfigDrxInactivitytimerEnumeratedMs40
	DrxConfigDrxInactivitytimerEnumeratedMs50
	DrxConfigDrxInactivitytimerEnumeratedMs60
	DrxConfigDrxInactivitytimerEnumeratedMs80
	DrxConfigDrxInactivitytimerEnumeratedMs100
	DrxConfigDrxInactivitytimerEnumeratedMs200
	DrxConfigDrxInactivitytimerEnumeratedMs300
	DrxConfigDrxInactivitytimerEnumeratedMs500
	DrxConfigDrxInactivitytimerEnumeratedMs750
	DrxConfigDrxInactivitytimerEnumeratedMs1280
	DrxConfigDrxInactivitytimerEnumeratedMs1920
	DrxConfigDrxInactivitytimerEnumeratedMs2560
	DrxConfigDrxInactivitytimerEnumeratedSpare9
	DrxConfigDrxInactivitytimerEnumeratedSpare8
	DrxConfigDrxInactivitytimerEnumeratedSpare7
	DrxConfigDrxInactivitytimerEnumeratedSpare6
	DrxConfigDrxInactivitytimerEnumeratedSpare5
	DrxConfigDrxInactivitytimerEnumeratedSpare4
	DrxConfigDrxInactivitytimerEnumeratedSpare3
	DrxConfigDrxInactivitytimerEnumeratedSpare2
	DrxConfigDrxInactivitytimerEnumeratedSpare1
)
