package ies

import "rrc/utils"

// DRX-ConfigPTM-r17-drx-InactivityTimerPTM-r17 ::= ENUMERATED
type DrxConfigptmR17DrxInactivitytimerptmR17 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedNothing = iota
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs0
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs1
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs2
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs3
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs4
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs5
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs6
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs8
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs10
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs20
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs30
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs40
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs50
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs60
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs80
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs100
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs200
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs300
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs500
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs750
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs1280
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs1920
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedMs2560
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare9
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare8
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare7
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare6
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare5
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare4
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare3
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare2
	DrxConfigptmR17DrxInactivitytimerptmR17EnumeratedSpare1
)
