package ies

import "rrc/utils"

// DRX-Config-NB-r13-setup-drx-ULRetransmissionTimer-r13 ::= ENUMERATED
type DrxConfigNbR13SetupDrxUlretransmissiontimerR13 struct {
	Value utils.ENUMERATED
}

const (
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedNothing = iota
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp0
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp1
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp2
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp4
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp6
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp8
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp16
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp24
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp33
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp40
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp64
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp80
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp96
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp112
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp128
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp160
	DrxConfigNbR13SetupDrxUlretransmissiontimerR13EnumeratedPp320
)
