package ies

import "rrc/utils"

// DRX-Info-shortDRX-drx-ShortCycle ::= ENUMERATED
type DrxInfoShortdrxDrxShortcycle struct {
	Value utils.ENUMERATED
}

const (
	DrxInfoShortdrxDrxShortcycleEnumeratedNothing = iota
	DrxInfoShortdrxDrxShortcycleEnumeratedMs2
	DrxInfoShortdrxDrxShortcycleEnumeratedMs3
	DrxInfoShortdrxDrxShortcycleEnumeratedMs4
	DrxInfoShortdrxDrxShortcycleEnumeratedMs5
	DrxInfoShortdrxDrxShortcycleEnumeratedMs6
	DrxInfoShortdrxDrxShortcycleEnumeratedMs7
	DrxInfoShortdrxDrxShortcycleEnumeratedMs8
	DrxInfoShortdrxDrxShortcycleEnumeratedMs10
	DrxInfoShortdrxDrxShortcycleEnumeratedMs14
	DrxInfoShortdrxDrxShortcycleEnumeratedMs16
	DrxInfoShortdrxDrxShortcycleEnumeratedMs20
	DrxInfoShortdrxDrxShortcycleEnumeratedMs30
	DrxInfoShortdrxDrxShortcycleEnumeratedMs32
	DrxInfoShortdrxDrxShortcycleEnumeratedMs35
	DrxInfoShortdrxDrxShortcycleEnumeratedMs40
	DrxInfoShortdrxDrxShortcycleEnumeratedMs64
	DrxInfoShortdrxDrxShortcycleEnumeratedMs80
	DrxInfoShortdrxDrxShortcycleEnumeratedMs128
	DrxInfoShortdrxDrxShortcycleEnumeratedMs160
	DrxInfoShortdrxDrxShortcycleEnumeratedMs256
	DrxInfoShortdrxDrxShortcycleEnumeratedMs320
	DrxInfoShortdrxDrxShortcycleEnumeratedMs512
	DrxInfoShortdrxDrxShortcycleEnumeratedMs640
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare9
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare8
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare7
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare6
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare5
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare4
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare3
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare2
	DrxInfoShortdrxDrxShortcycleEnumeratedSpare1
)
