package ies

import "rrc/utils"

// DRX-Preference-r16-preferredDRX-ShortCycle-r16 ::= ENUMERATED
type DrxPreferenceR16PreferreddrxShortcycleR16 struct {
	Value utils.ENUMERATED
}

const (
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedNothing = iota
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs2
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs3
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs4
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs5
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs6
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs7
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs8
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs10
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs14
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs16
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs20
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs30
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs32
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs35
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs40
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs64
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs80
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs128
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs160
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs256
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs320
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs512
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedMs640
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare9
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare8
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare7
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare6
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare5
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare4
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare3
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare2
	DrxPreferenceR16PreferreddrxShortcycleR16EnumeratedSpare1
)
