package ies

import "rrc/utils"

// DRX-Preference-r16-preferredDRX-InactivityTimer-r16 ::= ENUMERATED
type DrxPreferenceR16PreferreddrxInactivitytimerR16 struct {
	Value utils.ENUMERATED
}

const (
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedNothing = iota
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs0
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs1
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs2
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs3
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs4
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs5
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs6
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs8
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs10
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs20
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs30
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs40
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs50
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs60
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs80
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs100
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs200
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs300
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs500
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs750
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs1280
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs1920
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedMs2560
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare9
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare8
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare7
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare6
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare5
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare4
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare3
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare2
	DrxPreferenceR16PreferreddrxInactivitytimerR16EnumeratedSpare1
)
