package ies

import "rrc/utils"

// DRX-PreferenceConfig-r16-drx-PreferenceProhibitTimer-r16 ::= ENUMERATED
type DrxPreferenceconfigR16DrxPreferenceprohibittimerR16 struct {
	Value utils.ENUMERATED
}

const (
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedNothing = iota
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS0
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS0dot5
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS1
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS2
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS3
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS4
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS5
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS6
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS7
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS8
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS9
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS10
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS20
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedS30
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedSpare2
	DrxPreferenceconfigR16DrxPreferenceprohibittimerR16EnumeratedSpare1
)
