package ies

import "rrc/utils"

// DummyB-maxNumberTxPortsPerResource ::= ENUMERATED
type DummybMaxnumbertxportsperresource struct {
	Value utils.ENUMERATED
}

const (
	DummybMaxnumbertxportsperresourceEnumeratedNothing = iota
	DummybMaxnumbertxportsperresourceEnumeratedP2
	DummybMaxnumbertxportsperresourceEnumeratedP4
	DummybMaxnumbertxportsperresourceEnumeratedP8
	DummybMaxnumbertxportsperresourceEnumeratedP12
	DummybMaxnumbertxportsperresourceEnumeratedP16
	DummybMaxnumbertxportsperresourceEnumeratedP24
	DummybMaxnumbertxportsperresourceEnumeratedP32
)
