package ies

import "rrc/utils"

// DummyA-totalNumberPortsSimultaneousCSI-RS-ActBWP-AllCC ::= ENUMERATED
type DummyaTotalnumberportssimultaneouscsiRsActbwpAllcc struct {
	Value utils.ENUMERATED
}

const (
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedNothing = iota
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP8
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP12
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP16
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP24
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP32
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP40
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP48
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP56
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP64
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP72
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP80
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP88
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP96
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP104
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP112
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP120
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP128
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP136
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP144
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP152
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP160
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP168
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP176
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP184
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP192
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP200
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP208
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP216
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP224
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP232
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP240
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP248
	DummyaTotalnumberportssimultaneouscsiRsActbwpAllccEnumeratedP256
)
