package ies

import "rrc/utils"

// DummyA-maxNumberSimultaneousCSI-RS-ActBWP-AllCC ::= ENUMERATED
type DummyaMaxnumbersimultaneouscsiRsActbwpAllcc struct {
	Value utils.ENUMERATED
}

const (
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedNothing = iota
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN5
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN6
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN7
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN8
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN9
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN10
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN12
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN14
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN16
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN18
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN20
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN22
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN24
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN26
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN28
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN30
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN32
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN34
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN36
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN38
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN40
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN42
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN44
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN46
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN48
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN50
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN52
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN54
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN56
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN58
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN60
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN62
	DummyaMaxnumbersimultaneouscsiRsActbwpAllccEnumeratedN64
)
