package ies

import "rrc/utils"

// DummyA-maxNumberPortsAcrossNZP-CSI-RS-PerCC ::= ENUMERATED
type DummyaMaxnumberportsacrossnzpCsiRsPercc struct {
	Value utils.ENUMERATED
}

const (
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedNothing = iota
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP2
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP4
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP8
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP12
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP16
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP24
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP32
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP40
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP48
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP56
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP64
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP72
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP80
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP88
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP96
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP104
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP112
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP120
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP128
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP136
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP144
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP152
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP160
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP168
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP176
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP184
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP192
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP200
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP208
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP216
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP224
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP232
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP240
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP248
	DummyaMaxnumberportsacrossnzpCsiRsPerccEnumeratedP256
)
