package ies

import "rrc/utils"

// EDT-PRACH-ParametersCE-r15-edt-PRACH-ParametersCE-r15-prach-StartingSubframe-r15 ::= ENUMERATED
type EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15 struct {
	Value utils.ENUMERATED
}

const (
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedNothing = iota
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf2
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf4
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf8
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf16
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf32
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf64
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf128
	EdtPrachParametersceR15EdtPrachParametersceR15PrachStartingsubframeR15EnumeratedSf256
)
