package ies

import "rrc/utils"

// EIMTA-MainConfigServCell-r12-setup-eimta-HARQ-ReferenceConfig-r12 ::= ENUMERATED
type EimtaMainconfigservcellR12SetupEimtaHarqReferenceconfigR12 struct {
	Value utils.ENUMERATED
}

const (
	EimtaMainconfigservcellR12SetupEimtaHarqReferenceconfigR12EnumeratedNothing = iota
	EimtaMainconfigservcellR12SetupEimtaHarqReferenceconfigR12EnumeratedSa2
	EimtaMainconfigservcellR12SetupEimtaHarqReferenceconfigR12EnumeratedSa4
	EimtaMainconfigservcellR12SetupEimtaHarqReferenceconfigR12EnumeratedSa5
)
