package ies

import "rrc/utils"

// EPDCCH-SetConfig-r11-resourceBlockAssignment-r11-numberPRB-Pairs-r11 ::= ENUMERATED
type EpdcchSetconfigR11ResourceblockassignmentR11NumberprbPairsR11 struct {
	Value utils.ENUMERATED
}

const (
	EpdcchSetconfigR11ResourceblockassignmentR11NumberprbPairsR11EnumeratedNothing = iota
	EpdcchSetconfigR11ResourceblockassignmentR11NumberprbPairsR11EnumeratedN2
	EpdcchSetconfigR11ResourceblockassignmentR11NumberprbPairsR11EnumeratedN4
	EpdcchSetconfigR11ResourceblockassignmentR11NumberprbPairsR11EnumeratedN8
)
