package ies

import "rrc/utils"

// EstablishmentCause ::= ENUMERATED
type Establishmentcause struct {
	Value utils.ENUMERATED
}

const (
	EstablishmentcauseEnumeratedNothing = iota
	EstablishmentcauseEnumeratedEmergency
	EstablishmentcauseEnumeratedHighpriorityaccess
	EstablishmentcauseEnumeratedMt_Access
	EstablishmentcauseEnumeratedMo_Signalling
	EstablishmentcauseEnumeratedMo_Data
	EstablishmentcauseEnumeratedMo_Voicecall
	EstablishmentcauseEnumeratedMo_Videocall
	EstablishmentcauseEnumeratedMo_Sms
	EstablishmentcauseEnumeratedMps_Priorityaccess
	EstablishmentcauseEnumeratedMcs_Priorityaccess
	EstablishmentcauseEnumeratedSpare6
	EstablishmentcauseEnumeratedSpare5
	EstablishmentcauseEnumeratedSpare4
	EstablishmentcauseEnumeratedSpare3
	EstablishmentcauseEnumeratedSpare2
	EstablishmentcauseEnumeratedSpare1
)
