package ies

import "rrc/utils"

// EUTRA-MBSFN-SubframeConfig-radioframeAllocationPeriod ::= ENUMERATED
type EutraMbsfnSubframeconfigRadioframeallocationperiod struct {
	Value utils.ENUMERATED
}

const (
	EutraMbsfnSubframeconfigRadioframeallocationperiodEnumeratedNothing = iota
	EutraMbsfnSubframeconfigRadioframeallocationperiodEnumeratedN1
	EutraMbsfnSubframeconfigRadioframeallocationperiodEnumeratedN2
	EutraMbsfnSubframeconfigRadioframeallocationperiodEnumeratedN4
	EutraMbsfnSubframeconfigRadioframeallocationperiodEnumeratedN8
	EutraMbsfnSubframeconfigRadioframeallocationperiodEnumeratedN16
	EutraMbsfnSubframeconfigRadioframeallocationperiodEnumeratedN32
)
