package ies

import "rrc/utils"

// ExcessDelay-DRB-IdentityInfo-r17-delayThreshold ::= ENUMERATED
type ExcessdelayDrbIdentityinfoR17Delaythreshold struct {
	Value utils.ENUMERATED
}

const (
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedNothing = iota
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs0dot25
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs0dot5
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs1
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs2
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs4
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs5
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs10
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs20
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs30
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs40
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs50
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs60
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs70
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs80
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs90
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs100
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs150
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs300
	ExcessdelayDrbIdentityinfoR17DelaythresholdEnumeratedMs500
)
