package ies

import "rrc/utils"

// FailureReportSCG-EUTRA-failureType ::= ENUMERATED
type FailurereportscgEutraFailuretype struct {
	Value utils.ENUMERATED
}

const (
	FailurereportscgEutraFailuretypeEnumeratedNothing = iota
	FailurereportscgEutraFailuretypeEnumeratedT313_Expiry
	FailurereportscgEutraFailuretypeEnumeratedRandomaccessproblem
	FailurereportscgEutraFailuretypeEnumeratedRlc_Maxnumretx
	FailurereportscgEutraFailuretypeEnumeratedScg_Changefailure
	FailurereportscgEutraFailuretypeEnumeratedSpare4
	FailurereportscgEutraFailuretypeEnumeratedSpare3
	FailurereportscgEutraFailuretypeEnumeratedSpare2
	FailurereportscgEutraFailuretypeEnumeratedSpare1
)
