package ies

import "rrc/utils"

// FailureReportMCG-r16-failureType-r16 ::= ENUMERATED
type FailurereportmcgR16FailuretypeR16 struct {
	Value utils.ENUMERATED
}

const (
	FailurereportmcgR16FailuretypeR16EnumeratedNothing = iota
	FailurereportmcgR16FailuretypeR16EnumeratedT310_Expiry
	FailurereportmcgR16FailuretypeR16EnumeratedRandomaccessproblem
	FailurereportmcgR16FailuretypeR16EnumeratedRlc_Maxnumretx
	FailurereportmcgR16FailuretypeR16EnumeratedT312_Expiry_R16
	FailurereportmcgR16FailuretypeR16EnumeratedLbt_Failure_R16
	FailurereportmcgR16FailuretypeR16EnumeratedBeamfailurerecoveryfailure_R16
	FailurereportmcgR16FailuretypeR16EnumeratedBh_Rlf_R16
	FailurereportmcgR16FailuretypeR16EnumeratedSpare1
)
