package ies

import "rrc/utils"

// FailureReportSCG-failureType ::= ENUMERATED
type FailurereportscgFailuretype struct {
	Value utils.ENUMERATED
}

const (
	FailurereportscgFailuretypeEnumeratedNothing = iota
	FailurereportscgFailuretypeEnumeratedT310_Expiry
	FailurereportscgFailuretypeEnumeratedRandomaccessproblem
	FailurereportscgFailuretypeEnumeratedRlc_Maxnumretx
	FailurereportscgFailuretypeEnumeratedSynchreconfigfailurescg
	FailurereportscgFailuretypeEnumeratedScg_Reconfigfailure
	FailurereportscgFailuretypeEnumeratedSrb3_Integrityfailure
	FailurereportscgFailuretypeEnumeratedOther_R16
	FailurereportscgFailuretypeEnumeratedSpare1
)
