package ies

import "rrc/utils"

// FeatureSetDownlinkPerCC-v1700-maxNumberMIMO-LayersMulticastPDSCH-r17 ::= ENUMERATED
type FeaturesetdownlinkperccV1700MaxnumbermimoLayersmulticastpdschR17 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkperccV1700MaxnumbermimoLayersmulticastpdschR17EnumeratedNothing = iota
	FeaturesetdownlinkperccV1700MaxnumbermimoLayersmulticastpdschR17EnumeratedN2
	FeaturesetdownlinkperccV1700MaxnumbermimoLayersmulticastpdschR17EnumeratedN4
	FeaturesetdownlinkperccV1700MaxnumbermimoLayersmulticastpdschR17EnumeratedN8
)
