package ies

import "rrc/utils"

// FeatureCombinationPreambles-r17-groupBconfigured-r17-ra-SizeGroupA-r17 ::= ENUMERATED
type FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17 struct {
	Value utils.ENUMERATED
}

const (
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedNothing = iota
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB56
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB144
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB208
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB256
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB282
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB480
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB640
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB800
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB1000
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedB72
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedSpare6
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedSpare5
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedSpare4
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedSpare3
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedSpare2
	FeaturecombinationpreamblesR17GroupbconfiguredR17RaSizegroupaR17EnumeratedSpare1
)
