package ies

import "rrc/utils"

// FeatureSetDownlinkPerCC-v1720-maxModulationOrderForMulticastDataRateCalculation-r17 ::= ENUMERATED
type FeaturesetdownlinkperccV1720MaxmodulationorderformulticastdataratecalculationR17 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkperccV1720MaxmodulationorderformulticastdataratecalculationR17EnumeratedNothing = iota
	FeaturesetdownlinkperccV1720MaxmodulationorderformulticastdataratecalculationR17EnumeratedQam64
	FeaturesetdownlinkperccV1720MaxmodulationorderformulticastdataratecalculationR17EnumeratedQam256
	FeaturesetdownlinkperccV1720MaxmodulationorderformulticastdataratecalculationR17EnumeratedQam1024
)
