package ies

import "rrc/utils"

// FeatureSetDownlink-pdsch-ProcessingType1-DifferentTB-PerSlot-scs-60kHz ::= ENUMERATED
type FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs60khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs60khzEnumeratedNothing = iota
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs60khzEnumeratedUpto2
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs60khzEnumeratedUpto4
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs60khzEnumeratedUpto7
)
