package ies

import "rrc/utils"

// FeatureSetUplink-v1720-phy-PrioritizationHighPriorityDG-LowPriorityCG-r17-additionalCancellationTime-r17-scs-15kHz-r17 ::= ENUMERATED
type FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs15khzR17 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs15khzR17EnumeratedNothing = iota
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs15khzR17EnumeratedSym0
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs15khzR17EnumeratedSym1
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs15khzR17EnumeratedSym2
)
