package ies

import "rrc/utils"

// FeatureSetDownlink-v1540-pdcch-MonitoringAnyOccasionsWithSpanGap-scs-60kHz ::= ENUMERATED
type FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs60khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs60khzEnumeratedNothing = iota
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs60khzEnumeratedSet1
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs60khzEnumeratedSet2
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs60khzEnumeratedSet3
)
