package ies

import "rrc/utils"

// FeatureSetUplink-pusch-ProcessingType1-DifferentTB-PerSlot-scs-60kHz ::= ENUMERATED
type FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs60khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs60khzEnumeratedNothing = iota
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs60khzEnumeratedUpto2
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs60khzEnumeratedUpto4
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs60khzEnumeratedUpto7
)
