package ies

import "rrc/utils"

// FeatureSetDownlink-v1540-pdcch-MonitoringAnyOccasionsWithSpanGap-scs-30kHz ::= ENUMERATED
type FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs30khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs30khzEnumeratedNothing = iota
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs30khzEnumeratedSet1
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs30khzEnumeratedSet2
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs30khzEnumeratedSet3
)
