package ies

import "rrc/utils"

// FeatureSetUplink-v1720-phy-PrioritizationHighPriorityDG-LowPriorityCG-r17-additionalCancellationTime-r17-scs-60kHz-r17 ::= ENUMERATED
type FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedNothing = iota
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym0
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym1
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym2
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym3
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym4
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym5
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym6
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym7
	FeaturesetuplinkV1720PhyPrioritizationhighprioritydgLowprioritycgR17AdditionalcancellationtimeR17Scs60khzR17EnumeratedSym8
)
