package ies

import "rrc/utils"

// FeatureSetUplink-pusch-ProcessingType1-DifferentTB-PerSlot-scs-30kHz ::= ENUMERATED
type FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs30khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs30khzEnumeratedNothing = iota
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs30khzEnumeratedUpto2
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs30khzEnumeratedUpto4
	FeaturesetuplinkPuschProcessingtype1DifferenttbPerslotScs30khzEnumeratedUpto7
)
