package ies

import "rrc/utils"

// FeatureSetUplink-v1610-ul-IntraUE-Mux-r16-pusch-PreparationHighPriority-r16 ::= ENUMERATED
type FeaturesetuplinkV1610UlIntraueMuxR16PuschPreparationhighpriorityR16 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkV1610UlIntraueMuxR16PuschPreparationhighpriorityR16EnumeratedNothing = iota
	FeaturesetuplinkV1610UlIntraueMuxR16PuschPreparationhighpriorityR16EnumeratedSym0
	FeaturesetuplinkV1610UlIntraueMuxR16PuschPreparationhighpriorityR16EnumeratedSym1
	FeaturesetuplinkV1610UlIntraueMuxR16PuschPreparationhighpriorityR16EnumeratedSym2
)
