package ies

import "rrc/utils"

// FeatureSetUplink-v1610-ul-FullPwrMode2-TPMIGroup-r16-fourPortsNonCoherent-r16 ::= ENUMERATED
type FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportsnoncoherentR16 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportsnoncoherentR16EnumeratedNothing = iota
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportsnoncoherentR16EnumeratedG0
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportsnoncoherentR16EnumeratedG1
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportsnoncoherentR16EnumeratedG2
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportsnoncoherentR16EnumeratedG3
)
