package ies

import "rrc/utils"

// FeatureSetUplink-v1610-ul-FullPwrMode2-SRSConfig-diffNumSRSPorts-r16 ::= ENUMERATED
type FeaturesetuplinkV1610UlFullpwrmode2SrsconfigDiffnumsrsportsR16 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkV1610UlFullpwrmode2SrsconfigDiffnumsrsportsR16EnumeratedNothing = iota
	FeaturesetuplinkV1610UlFullpwrmode2SrsconfigDiffnumsrsportsR16EnumeratedP1_2
	FeaturesetuplinkV1610UlFullpwrmode2SrsconfigDiffnumsrsportsR16EnumeratedP1_4
	FeaturesetuplinkV1610UlFullpwrmode2SrsconfigDiffnumsrsportsR16EnumeratedP1_2_4
)
