package ies

import "rrc/utils"

// FeatureSetDownlink-v1540-pdcch-MonitoringAnyOccasionsWithSpanGap-scs-120kHz ::= ENUMERATED
type FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs120khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs120khzEnumeratedNothing = iota
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs120khzEnumeratedSet1
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs120khzEnumeratedSet2
	FeaturesetdownlinkV1540PdcchMonitoringanyoccasionswithspangapScs120khzEnumeratedSet3
)
