package ies

import "rrc/utils"

// FeatureSetUplink-v1610-ul-FullPwrMode2-TPMIGroup-r16-fourPortsPartialCoherent-r16 ::= ENUMERATED
type FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16 struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedNothing = iota
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedG0
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedG1
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedG2
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedG3
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedG4
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedG5
	FeaturesetuplinkV1610UlFullpwrmode2TpmigroupR16FourportspartialcoherentR16EnumeratedG6
)
