package ies

import "rrc/utils"

// FeatureSetDownlink-pdsch-ProcessingType1-DifferentTB-PerSlot-scs-30kHz ::= ENUMERATED
type FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs30khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs30khzEnumeratedNothing = iota
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs30khzEnumeratedUpto2
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs30khzEnumeratedUpto4
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs30khzEnumeratedUpto7
)
