package ies

import "rrc/utils"

// FeatureCombinationPreambles-r17-groupBconfigured-r17-messagePowerOffsetGroupB-r17 ::= ENUMERATED
type FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17 struct {
	Value utils.ENUMERATED
}

const (
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedNothing = iota
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedMinusinfinity
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedDb0
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedDb5
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedDb8
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedDb10
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedDb12
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedDb15
	FeaturecombinationpreamblesR17GroupbconfiguredR17MessagepoweroffsetgroupbR17EnumeratedDb18
)
