package ies

import "rrc/utils"

// FeatureSetDownlink-pdsch-ProcessingType1-DifferentTB-PerSlot-scs-120kHz ::= ENUMERATED
type FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs120khz struct {
	Value utils.ENUMERATED
}

const (
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs120khzEnumeratedNothing = iota
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs120khzEnumeratedUpto2
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs120khzEnumeratedUpto4
	FeaturesetdownlinkPdschProcessingtype1DifferenttbPerslotScs120khzEnumeratedUpto7
)
