package ies

import "rrc/utils"

// GroupB-ConfiguredTwoStepRA-r16-ra-MsgA-SizeGroupA ::= ENUMERATED
type GroupbConfiguredtwostepraR16RaMsgaSizegroupa struct {
	Value utils.ENUMERATED
}

const (
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedNothing = iota
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB56
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB144
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB208
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB256
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB282
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB480
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB640
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB800
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB1000
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedB72
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedSpare6
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedSpare5
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedSpare4
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedSpare3
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedSpare2
	GroupbConfiguredtwostepraR16RaMsgaSizegroupaEnumeratedSpare1
)
