package ies

import "rrc/utils"

// HandoverPreparationInformation-v920-IEs-ue-ConfigRelease-r9 ::= utils.ENUMERATED // Extensible
type HandoverpreparationinformationV920IesUeConfigreleaseR9 struct {
	Value utils.ENUMERATED
}

const (
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedNothing = iota
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel9
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel10
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel11
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel12
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedV10j0
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedV11e0
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedV1280
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel13
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel14
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel15
	HandoverpreparationinformationV920IesUeConfigreleaseR9EnumeratedRel16
)
