package ies

import "rrc/utils"

// IDC-Config-r11-autonomousDenialParameters-r11-autonomousDenialSubframes-r11 ::= ENUMERATED
type IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11 struct {
	Value utils.ENUMERATED
}

const (
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedNothing = iota
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedN2
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedN5
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedN10
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedN15
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedN20
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedN30
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedSpare2
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialsubframesR11EnumeratedSpare1
)
