package ies

import "rrc/utils"

// IDC-Config-r11-autonomousDenialParameters-r11-autonomousDenialValidity-r11 ::= ENUMERATED
type IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11 struct {
	Value utils.ENUMERATED
}

const (
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedNothing = iota
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSf200
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSf500
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSf1000
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSf2000
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSpare4
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSpare3
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSpare2
	IdcConfigR11AutonomousdenialparametersR11AutonomousdenialvalidityR11EnumeratedSpare1
)
