package ies

// InterFreqRSTDMeasurementIndication-r10-IEs-rstd-InterFreqIndication-r10 ::= CHOICE
const (
	InterfreqrstdmeasurementindicationR10IesRstdInterfreqindicationR10ChoiceNothing = iota
	InterfreqrstdmeasurementindicationR10IesRstdInterfreqindicationR10ChoiceStart
	InterfreqrstdmeasurementindicationR10IesRstdInterfreqindicationR10ChoiceStop
)

type InterfreqrstdmeasurementindicationR10IesRstdInterfreqindicationR10 struct {
	Choice uint64
	Start  *InterfreqrstdmeasurementindicationR10IesRstdInterfreqindicationR10Start
	Stop   *struct{}
}
