package ies

import "rrc/utils"

// IntraFreqCellReselectionInfo-NB-v1430-ce-AuthorisationOffset-r14 ::= ENUMERATED
type IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14 struct {
	Value utils.ENUMERATED
}

const (
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedNothing = iota
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedDb5
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedDb10
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedDb15
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedDb20
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedDb25
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedDb30
	IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14EnumeratedDb35
)
