package ies

// IntraFreqCellReselectionInfo-NB-v1430 ::= SEQUENCE
type IntrafreqcellreselectioninfoNbV1430 struct {
	Powerclass14dbmOffsetR14 *IntrafreqcellreselectioninfoNbV1430Powerclass14dbmOffsetR14
	CeAuthorisationoffsetR14 *IntrafreqcellreselectioninfoNbV1430CeAuthorisationoffsetR14
}
