package ies

import "rrc/utils"

// LBT-FailureRecoveryConfig-r16-lbt-FailureInstanceMaxCount-r16 ::= ENUMERATED
type LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16 struct {
	Value utils.ENUMERATED
}

const (
	LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16EnumeratedNothing = iota
	LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16EnumeratedN4
	LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16EnumeratedN8
	LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16EnumeratedN16
	LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16EnumeratedN32
	LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16EnumeratedN64
	LbtFailurerecoveryconfigR16LbtFailureinstancemaxcountR16EnumeratedN128
)
