package ies

import "rrc/utils"

// LogicalChannelConfig-ul-SpecificParameters-prioritisedBitRate ::= ENUMERATED
type LogicalchannelconfigUlSpecificparametersPrioritisedbitrate struct {
	Value utils.ENUMERATED
}

const (
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedNothing = iota
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps0
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps8
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps16
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps32
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps64
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps128
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps256
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps512
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps1024
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps2048
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps4096
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps8192
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps16384
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps32768
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps65536
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedInfinity
)
