package ies

import "rrc/utils"

// LogicalChannelConfig-ul-SpecificParameters-bitRateQueryProhibitTimer ::= ENUMERATED
type LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimer struct {
	Value utils.ENUMERATED
}

const (
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedNothing = iota
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS0
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS0dot4
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS0dot8
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS1dot6
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS3
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS6
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS12
	LogicalchannelconfigUlSpecificparametersBitratequeryprohibittimerEnumeratedS30
)
