package ies

import "rrc/utils"

// LogicalChannelConfig-ul-SpecificParameters-bucketSizeDuration ::= ENUMERATED
type LogicalchannelconfigUlSpecificparametersBucketsizeduration struct {
	Value utils.ENUMERATED
}

const (
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedNothing = iota
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs5
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs10
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs20
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs50
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs100
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs150
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs300
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs500
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs1000
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare7
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare6
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare5
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare4
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare3
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare2
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare1
)
