package ies

import "rrc/utils"

// LogicalChannelConfig-ul-SpecificParameters-allowedPHY-PriorityIndex-r16 ::= ENUMERATED
type LogicalchannelconfigUlSpecificparametersAllowedphyPriorityindexR16 struct {
	Value utils.ENUMERATED
}

const (
	LogicalchannelconfigUlSpecificparametersAllowedphyPriorityindexR16EnumeratedNothing = iota
	LogicalchannelconfigUlSpecificparametersAllowedphyPriorityindexR16EnumeratedP0
	LogicalchannelconfigUlSpecificparametersAllowedphyPriorityindexR16EnumeratedP1
)
