package ies

import "rrc/utils"

// LogicalChannelConfig-ul-SpecificParameters-bucketSizeDuration ::= ENUMERATED
type LogicalchannelconfigUlSpecificparametersBucketsizeduration struct {
	Value utils.ENUMERATED
}

const (
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedNothing = iota
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs50
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs100
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs150
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs300
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs500
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedMs1000
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare2
	LogicalchannelconfigUlSpecificparametersBucketsizedurationEnumeratedSpare1
)
