package ies

import "rrc/utils"

// LogicalChannelConfig-ul-SpecificParameters-prioritisedBitRate ::= ENUMERATED
type LogicalchannelconfigUlSpecificparametersPrioritisedbitrate struct {
	Value utils.ENUMERATED
}

const (
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedNothing = iota
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps0
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps8
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps16
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps32
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps64
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps128
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps256
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedInfinity
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps512_V1020
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps1024_V1020
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedKbps2048_V1020
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedSpare5
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedSpare4
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedSpare3
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedSpare2
	LogicalchannelconfigUlSpecificparametersPrioritisedbitrateEnumeratedSpare1
)
