package ies

import "rrc/utils"

// LogicalChannelConfig-ul-SpecificParameters-maxPUSCH-Duration ::= ENUMERATED
type LogicalchannelconfigUlSpecificparametersMaxpuschDuration struct {
	Value utils.ENUMERATED
}

const (
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedNothing = iota
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedMs0p02
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedMs0p04
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedMs0p0625
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedMs0p125
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedMs0p25
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedMs0p5
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedMs0p01_V1700
	LogicalchannelconfigUlSpecificparametersMaxpuschDurationEnumeratedSpare1
)
