package ies

import "rrc/utils"

// MAC-MainConfig-ul-SCH-Config-maxHARQ-Tx ::= ENUMERATED
type MacMainconfigUlSchConfigMaxharqTx struct {
	Value utils.ENUMERATED
}

const (
	MacMainconfigUlSchConfigMaxharqTxEnumeratedNothing = iota
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN1
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN2
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN3
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN4
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN5
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN6
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN7
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN8
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN10
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN12
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN16
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN20
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN24
	MacMainconfigUlSchConfigMaxharqTxEnumeratedN28
	MacMainconfigUlSchConfigMaxharqTxEnumeratedSpare2
	MacMainconfigUlSchConfigMaxharqTxEnumeratedSpare1
)
