package ies

import "rrc/utils"

// MAC-MainConfig-NB-r13-logicalChannelSR-Config-r13-setup-logicalChannelSR-ProhibitTimer-r13 ::= ENUMERATED
type MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13 struct {
	Value utils.ENUMERATED
}

const (
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedNothing = iota
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedPp2
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedPp8
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedPp32
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedPp128
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedPp512
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedPp1024
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedPp2048
	MacMainconfigNbR13LogicalchannelsrConfigR13SetupLogicalchannelsrProhibittimerR13EnumeratedSpare
)
