package ies

import "rrc/utils"

// MasterInformationBlock-SL-V2X-r14-sl-Bandwidth-r14 ::= ENUMERATED
type MasterinformationblockSlV2xR14SlBandwidthR14 struct {
	Value utils.ENUMERATED
}

const (
	MasterinformationblockSlV2xR14SlBandwidthR14EnumeratedNothing = iota
	MasterinformationblockSlV2xR14SlBandwidthR14EnumeratedN6
	MasterinformationblockSlV2xR14SlBandwidthR14EnumeratedN15
	MasterinformationblockSlV2xR14SlBandwidthR14EnumeratedN25
	MasterinformationblockSlV2xR14SlBandwidthR14EnumeratedN50
	MasterinformationblockSlV2xR14SlBandwidthR14EnumeratedN75
	MasterinformationblockSlV2xR14SlBandwidthR14EnumeratedN100
)
