package ies

import "rrc/utils"

// MaxBW-PreferenceConfig-r16-maxBW-PreferenceProhibitTimer-r16 ::= ENUMERATED
type MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16 struct {
	Value utils.ENUMERATED
}

const (
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedNothing = iota
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS0
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS0dot5
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS1
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS2
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS3
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS4
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS5
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS6
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS7
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS8
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS9
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS10
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS20
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedS30
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedSpare2
	MaxbwPreferenceconfigR16MaxbwPreferenceprohibittimerR16EnumeratedSpare1
)
