package ies

import "rrc/utils"

// MaxCC-PreferenceConfig-r16-maxCC-PreferenceProhibitTimer-r16 ::= ENUMERATED
type MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16 struct {
	Value utils.ENUMERATED
}

const (
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedNothing = iota
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS0
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS0dot5
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS1
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS2
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS3
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS4
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS5
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS6
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS7
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS8
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS9
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS10
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS20
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedS30
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedSpare2
	MaxccPreferenceconfigR16MaxccPreferenceprohibittimerR16EnumeratedSpare1
)
