package ies

import "rrc/utils"

// MaxMIMO-LayerPreferenceConfig-r16-maxMIMO-LayerPreferenceProhibitTimer-r16 ::= ENUMERATED
type MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16 struct {
	Value utils.ENUMERATED
}

const (
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedNothing = iota
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS0
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS0dot5
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS1
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS2
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS3
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS4
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS5
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS6
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS7
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS8
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS9
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS10
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS20
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedS30
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedSpare2
	MaxmimoLayerpreferenceconfigR16MaxmimoLayerpreferenceprohibittimerR16EnumeratedSpare1
)
