package ies

import "rrc/utils"

// MBSFN-AreaInfo-r16-mcch-Config-r16-mcch-RepetitionPeriod-r16 ::= ENUMERATED
type MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16 struct {
	Value utils.ENUMERATED
}

const (
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedNothing = iota
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf1
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf2
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf4
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf8
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf16
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf32
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf64
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf128
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedRf256
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedSpare7
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedSpare6
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedSpare5
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedSpare4
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedSpare3
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedSpare2
	MbsfnAreainfoR16McchConfigR16McchRepetitionperiodR16EnumeratedSpare1
)
