package ies

import "rrc/utils"

// MBSFN-AreaInfo-r16-mcch-Config-r16-mcch-ModificationPeriod-r16 ::= ENUMERATED
type MbsfnAreainfoR16McchConfigR16McchModificationperiodR16 struct {
	Value utils.ENUMERATED
}

const (
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedNothing = iota
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf1
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf2
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf4
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf8
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf16
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf32
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf64
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf128
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf256
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf512
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedRf1024
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedSpare5
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedSpare4
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedSpare3
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedSpare2
	MbsfnAreainfoR16McchConfigR16McchModificationperiodR16EnumeratedSpare1
)
