package ies

import "rrc/utils"

// MBSFNAreaConfiguration-r9-commonSF-AllocPeriod-r9 ::= ENUMERATED
type MbsfnareaconfigurationR9CommonsfAllocperiodR9 struct {
	Value utils.ENUMERATED
}

const (
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedNothing = iota
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedRf4
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedRf8
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedRf16
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedRf32
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedRf64
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedRf128
	MbsfnareaconfigurationR9CommonsfAllocperiodR9EnumeratedRf256
)
