package ies

import "rrc/utils"

// MeasAndMobParametersMRDC-Common-v1610-condPSCellChangeParametersCommon-r16-condPSCellChangeFR1-FR2-r16 ::= ENUMERATED
type MeasandmobparametersmrdcCommonV1610CondpscellchangeparameterscommonR16Condpscellchangefr1Fr2R16 struct {
	Value utils.ENUMERATED
}

const (
	MeasandmobparametersmrdcCommonV1610CondpscellchangeparameterscommonR16Condpscellchangefr1Fr2R16EnumeratedNothing = iota
	MeasandmobparametersmrdcCommonV1610CondpscellchangeparameterscommonR16Condpscellchangefr1Fr2R16EnumeratedSupported
)
