package ies

// MeasAndMobParametersMRDC-Common-v1700-condPSCellChangeParameters-r17 ::= SEQUENCE
type MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17 struct {
	InterSnCondpscellchangefddTddNrdcR17     *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17InterSnCondpscellchangefddTddNrdcR17
	InterSnCondpscellchangefr1Fr2NrdcR17     *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17InterSnCondpscellchangefr1Fr2NrdcR17
	InterSnCondpscellchangefddTddEndcR17     *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17InterSnCondpscellchangefddTddEndcR17
	InterSnCondpscellchangefr1Fr2EndcR17     *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17InterSnCondpscellchangefr1Fr2EndcR17
	MnInitiatedcondpscellchangeFr1fddEndcR17 *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17MnInitiatedcondpscellchangeFr1fddEndcR17
	MnInitiatedcondpscellchangeFr1tddEndcR17 *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17MnInitiatedcondpscellchangeFr1tddEndcR17
	MnInitiatedcondpscellchangeFr2tddEndcR17 *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17MnInitiatedcondpscellchangeFr2tddEndcR17
	SnInitiatedcondpscellchangeFr1fddEndcR17 *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr1fddEndcR17
	SnInitiatedcondpscellchangeFr1tddEndcR17 *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr1tddEndcR17
	SnInitiatedcondpscellchangeFr2tddEndcR17 *MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr2tddEndcR17
}
