package ies

import "rrc/utils"

// MeasAndMobParametersMRDC-Common-v1700-condPSCellChangeParameters-r17-sn-InitiatedCondPSCellChange-FR1FDD-ENDC-r17 ::= ENUMERATED
type MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr1fddEndcR17 struct {
	Value utils.ENUMERATED
}

const (
	MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr1fddEndcR17EnumeratedNothing = iota
	MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr1fddEndcR17EnumeratedSupported
)
