package ies

import "rrc/utils"

// MeasReportAppLayer-r15-IEs-serviceType-r15 ::= ENUMERATED
type MeasreportapplayerR15IesServicetypeR15 struct {
	Value utils.ENUMERATED
}

const (
	MeasreportapplayerR15IesServicetypeR15EnumeratedNothing = iota
	MeasreportapplayerR15IesServicetypeR15EnumeratedQoe
	MeasreportapplayerR15IesServicetypeR15EnumeratedQoemtsi
	MeasreportapplayerR15IesServicetypeR15EnumeratedSpare6
	MeasreportapplayerR15IesServicetypeR15EnumeratedSpare5
	MeasreportapplayerR15IesServicetypeR15EnumeratedSpare4
	MeasreportapplayerR15IesServicetypeR15EnumeratedSpare3
	MeasreportapplayerR15IesServicetypeR15EnumeratedSpare2
	MeasreportapplayerR15IesServicetypeR15EnumeratedSpare1
)
