package ies

import "rrc/utils"

// MeasSensing-Config-r15-sensingPeriodicity-r15 ::= ENUMERATED
type MeassensingConfigR15SensingperiodicityR15 struct {
	Value utils.ENUMERATED
}

const (
	MeassensingConfigR15SensingperiodicityR15EnumeratedNothing = iota
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs20
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs50
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs100
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs200
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs300
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs400
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs500
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs600
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs700
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs800
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs900
	MeassensingConfigR15SensingperiodicityR15EnumeratedMs1000
)
