package ies

import "rrc/utils"

// MeasAndMobParametersMRDC-Common-v1700-condPSCellChangeParameters-r17-sn-InitiatedCondPSCellChange-FR2TDD-ENDC-r17 ::= ENUMERATED
type MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr2tddEndcR17 struct {
	Value utils.ENUMERATED
}

const (
	MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr2tddEndcR17EnumeratedNothing = iota
	MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17SnInitiatedcondpscellchangeFr2tddEndcR17EnumeratedSupported
)
