package ies

import "rrc/utils"

// MeasIdleConfigDedicated-r16-measIdleDuration-r16 ::= ENUMERATED
type MeasidleconfigdedicatedR16MeasidledurationR16 struct {
	Value utils.ENUMERATED
}

const (
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedNothing = iota
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSec10
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSec30
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSec60
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSec120
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSec180
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSec240
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSec300
	MeasidleconfigdedicatedR16MeasidledurationR16EnumeratedSpare
)
