package ies

import "rrc/utils"

// MeasAndMobParametersMRDC-Common-v1700-condPSCellChangeParameters-r17-mn-InitiatedCondPSCellChange-FR1TDD-ENDC-r17 ::= ENUMERATED
type MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17MnInitiatedcondpscellchangeFr1tddEndcR17 struct {
	Value utils.ENUMERATED
}

const (
	MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17MnInitiatedcondpscellchangeFr1tddEndcR17EnumeratedNothing = iota
	MeasandmobparametersmrdcCommonV1700CondpscellchangeparametersR17MnInitiatedcondpscellchangeFr1tddEndcR17EnumeratedSupported
)
