package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedSeparateTCI-InterCell-r17-k-UL-AcrossCC-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedseparatetciIntercellR17KUlAcrossccR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlAcrossccR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlAcrossccR17EnumeratedN0
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlAcrossccR17EnumeratedN1
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlAcrossccR17EnumeratedN2
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlAcrossccR17EnumeratedN4
)
