package ies

import "rrc/utils"

// MIMO-ParametersPerBand-supportInter-slotTDM-r16-supportRepNumPDSCH-TDRA-r16 ::= ENUMERATED
type MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedNothing = iota
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN2
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN3
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN4
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN5
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN6
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN7
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN8
	MimoParametersperbandSupportinterSlottdmR16SupportrepnumpdschTdraR16EnumeratedN16
)
