package ies

import "rrc/utils"

// MIMO-ParametersPerBand-beamSwitchTiming-scs-60kHz ::= ENUMERATED
type MimoParametersperbandBeamswitchtimingScs60khz struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandBeamswitchtimingScs60khzEnumeratedNothing = iota
	MimoParametersperbandBeamswitchtimingScs60khzEnumeratedSym14
	MimoParametersperbandBeamswitchtimingScs60khzEnumeratedSym28
	MimoParametersperbandBeamswitchtimingScs60khzEnumeratedSym48
	MimoParametersperbandBeamswitchtimingScs60khzEnumeratedSym224
	MimoParametersperbandBeamswitchtimingScs60khzEnumeratedSym336
)
