package ies

import "rrc/utils"

// MIMO-ParametersPerBand-maxNumberRxTxBeamSwitchDL-scs-120kHz ::= ENUMERATED
type MimoParametersperbandMaxnumberrxtxbeamswitchdlScs120khz struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMaxnumberrxtxbeamswitchdlScs120khzEnumeratedNothing = iota
	MimoParametersperbandMaxnumberrxtxbeamswitchdlScs120khzEnumeratedN4
	MimoParametersperbandMaxnumberrxtxbeamswitchdlScs120khzEnumeratedN7
	MimoParametersperbandMaxnumberrxtxbeamswitchdlScs120khzEnumeratedN14
)
