package ies

import "rrc/utils"

// MIMO-WeightedLayersCapabilities-r13-relWeightTwoLayers-r13 ::= ENUMERATED
type MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13 struct {
	Value utils.ENUMERATED
}

const (
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedNothing = iota
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV1
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV1dot25
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV1dot5
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV1dot75
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV2
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV2dot5
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV3
	MimoWeightedlayerscapabilitiesR13RelweighttwolayersR13EnumeratedV4
)
