package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedSeparateTCI-multiMAC-CE-r17-minBeamApplicationTime-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN1
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN2
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN4
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN7
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN14
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN28
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN42
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN56
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN70
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN84
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN98
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN112
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN224
	MimoParametersperbandUnifiedseparatetciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN336
)
