package ies

import "rrc/utils"

// MIMO-ParametersPerBand-mTRP-CSI-EnhancementPerBand-r17-codebookModeNCJT-r17 ::= ENUMERATED
type MimoParametersperbandMtrpCsiEnhancementperbandR17CodebookmodencjtR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMtrpCsiEnhancementperbandR17CodebookmodencjtR17EnumeratedNothing = iota
	MimoParametersperbandMtrpCsiEnhancementperbandR17CodebookmodencjtR17EnumeratedMode1
	MimoParametersperbandMtrpCsiEnhancementperbandR17CodebookmodencjtR17EnumeratedMode1and2
)
