package ies

import "rrc/utils"

// MIMO-ParametersPerBand-spatialRelations-v1640-maxNumberConfiguredSpatialRelations-v1640 ::= ENUMERATED
type MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedNothing = iota
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN96
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN128
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN160
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN192
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN224
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN256
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN288
	MimoParametersperbandSpatialrelationsV1640MaxnumberconfiguredspatialrelationsV1640EnumeratedN320
)
