package ies

import "rrc/utils"

// MIMO-ParametersPerBand-supportRepNumPDSCH-TDRA-DCI-1-2-r17 ::= ENUMERATED
type MimoParametersperbandSupportrepnumpdschTdraDci12R17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedNothing = iota
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN2
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN3
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN4
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN5
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN6
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN7
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN8
	MimoParametersperbandSupportrepnumpdschTdraDci12R17EnumeratedN16
)
