package ies

// MIMO-ParametersPerBand-ssb-csirs-SINR-measurement-r16 ::= SEQUENCE
type MimoParametersperbandSsbCsirsSinrMeasurementR16 struct {
	MaxnumberssbCsirsOnetxCmrR16  MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsOnetxCmrR16
	MaxnumbercsiImNzpImrResR16    MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumbercsiImNzpImrResR16
	Maxnumbercsirs2txResR16       MimoParametersperbandSsbCsirsSinrMeasurementR16Maxnumbercsirs2txResR16
	MaxnumberssbCsirsResR16       MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16
	MaxnumbercsiImNzpImrResMemR16 MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumbercsiImNzpImrResMemR16
	SupportedcsiRsDensityCmrR16   MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedcsiRsDensityCmrR16
	MaxnumberaperiodiccsiRsResR16 MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16
	SupportedsinrMeasR16          *MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedsinrMeasR16
}
