package ies

import "rrc/utils"

// MIMO-UE-ParametersPerTM-v1470-csi-ReportingAdvancedMaxPorts-r14 ::= ENUMERATED
type MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14 struct {
	Value utils.ENUMERATED
}

const (
	MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14EnumeratedNothing = iota
	MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14EnumeratedN8
	MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14EnumeratedN12
	MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14EnumeratedN16
	MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14EnumeratedN20
	MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14EnumeratedN24
	MimoUeParameterspertmV1470CsiReportingadvancedmaxportsR14EnumeratedN28
)
