package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedSeparateTCI-r17-maxConfiguredDL-TCI-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN4
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN8
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN12
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN16
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN24
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN32
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN48
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN64
	MimoParametersperbandUnifiedseparatetciR17MaxconfigureddlTciR17EnumeratedN128
)
