package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedSeparateTCI-InterCell-r17-k-UL-PerCC-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedseparatetciIntercellR17KUlPerccR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlPerccR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlPerccR17EnumeratedN0
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlPerccR17EnumeratedN1
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlPerccR17EnumeratedN2
	MimoParametersperbandUnifiedseparatetciIntercellR17KUlPerccR17EnumeratedN4
)
