package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedJointTCI-InterCell-r17-additionalMAC-CE-AcrossCC-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedjointtciIntercellR17AdditionalmacCeAcrossccR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedjointtciIntercellR17AdditionalmacCeAcrossccR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedjointtciIntercellR17AdditionalmacCeAcrossccR17EnumeratedN0
	MimoParametersperbandUnifiedjointtciIntercellR17AdditionalmacCeAcrossccR17EnumeratedN1
	MimoParametersperbandUnifiedjointtciIntercellR17AdditionalmacCeAcrossccR17EnumeratedN2
	MimoParametersperbandUnifiedjointtciIntercellR17AdditionalmacCeAcrossccR17EnumeratedN4
)
