package ies

import "rrc/utils"

// MIMO-ParametersPerBand-tci-StatePDSCH-maxNumberConfiguredTCI-StatesPerCC ::= ENUMERATED
type MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatespercc struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatesperccEnumeratedNothing = iota
	MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatesperccEnumeratedN4
	MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatesperccEnumeratedN8
	MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatesperccEnumeratedN16
	MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatesperccEnumeratedN32
	MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatesperccEnumeratedN64
	MimoParametersperbandTciStatepdschMaxnumberconfiguredtciStatesperccEnumeratedN128
)
