package ies

import "rrc/utils"

// MIMO-ParametersPerBand-mTRP-BFR-twoBFD-RS-Set-r17-maxBFD-RS-resourcesAcrossSetsPerBWP-r17 ::= ENUMERATED
type MimoParametersperbandMtrpBfrTwobfdRsSetR17MaxbfdRsResourcesacrosssetsperbwpR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMtrpBfrTwobfdRsSetR17MaxbfdRsResourcesacrosssetsperbwpR17EnumeratedNothing = iota
	MimoParametersperbandMtrpBfrTwobfdRsSetR17MaxbfdRsResourcesacrosssetsperbwpR17EnumeratedN2
	MimoParametersperbandMtrpBfrTwobfdRsSetR17MaxbfdRsResourcesacrosssetsperbwpR17EnumeratedN3
	MimoParametersperbandMtrpBfrTwobfdRsSetR17MaxbfdRsResourcesacrosssetsperbwpR17EnumeratedN4
)
