package ies

import "rrc/utils"

// MIMO-ParametersPerBand-multiDCI-multiTRP-Parameters-r16-overlapPDSCHsInTimePartiallyFreq-r16 ::= ENUMERATED
type MimoParametersperbandMultidciMultitrpParametersR16OverlappdschsintimepartiallyfreqR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMultidciMultitrpParametersR16OverlappdschsintimepartiallyfreqR16EnumeratedNothing = iota
	MimoParametersperbandMultidciMultitrpParametersR16OverlappdschsintimepartiallyfreqR16EnumeratedSupported
)
