package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedSeparateTCI-r17-maxConfiguredUL-TCI-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN4
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN8
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN12
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN16
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN24
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN32
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN48
	MimoParametersperbandUnifiedseparatetciR17MaxconfiguredulTciR17EnumeratedN64
)
