package ies

import "rrc/utils"

// MIMO-ParametersPerBand-ssb-csirs-SINR-measurement-r16-maxNumberSSB-CSIRS-res-r16 ::= ENUMERATED
type MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16EnumeratedNothing = iota
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16EnumeratedN8
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16EnumeratedN16
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16EnumeratedN32
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16EnumeratedN64
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsResR16EnumeratedN128
)
