package ies

import "rrc/utils"

// MIMO-ParametersPerBand-mTRP-BFD-RS-MAC-CE-r17 ::= ENUMERATED
type MimoParametersperbandMtrpBfdRsMacCeR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedNothing = iota
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedN4
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedN8
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedN12
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedN16
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedN32
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedN48
	MimoParametersperbandMtrpBfdRsMacCeR17EnumeratedN64
)
