package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedSeparateTCI-r17-maxActivatedDL-TCIAcrossCC-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedseparatetciR17MaxactivateddlTciacrossccR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedseparatetciR17MaxactivateddlTciacrossccR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedseparatetciR17MaxactivateddlTciacrossccR17EnumeratedN1
	MimoParametersperbandUnifiedseparatetciR17MaxactivateddlTciacrossccR17EnumeratedN2
	MimoParametersperbandUnifiedseparatetciR17MaxactivateddlTciacrossccR17EnumeratedN4
	MimoParametersperbandUnifiedseparatetciR17MaxactivateddlTciacrossccR17EnumeratedN8
	MimoParametersperbandUnifiedseparatetciR17MaxactivateddlTciacrossccR17EnumeratedN16
)
