package ies

import "rrc/utils"

// MIMO-ParametersPerBand-mpe-Mitigation-r17-maxNumConfRS-r17 ::= ENUMERATED
type MimoParametersperbandMpeMitigationR17MaxnumconfrsR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedNothing = iota
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN1
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN2
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN4
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN8
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN12
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN16
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN28
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN32
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN48
	MimoParametersperbandMpeMitigationR17MaxnumconfrsR17EnumeratedN64
)
