package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedSeparateTCI-InterCell-r17-k-DL-AcrossCC-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedseparatetciIntercellR17KDlAcrossccR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedseparatetciIntercellR17KDlAcrossccR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedseparatetciIntercellR17KDlAcrossccR17EnumeratedN0
	MimoParametersperbandUnifiedseparatetciIntercellR17KDlAcrossccR17EnumeratedN1
	MimoParametersperbandUnifiedseparatetciIntercellR17KDlAcrossccR17EnumeratedN2
	MimoParametersperbandUnifiedseparatetciIntercellR17KDlAcrossccR17EnumeratedN4
)
