package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedJointTCI-multiMAC-CE-r17-minBeamApplicationTime-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN1
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN2
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN4
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN7
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN14
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN28
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN42
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN56
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN70
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN84
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN98
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN112
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN224
	MimoParametersperbandUnifiedjointtciMultimacCeR17MinbeamapplicationtimeR17EnumeratedN336
)
