package ies

import "rrc/utils"

// MIMO-ParametersPerBand-ssb-csirs-SINR-measurement-r16-maxNumberAperiodicCSI-RS-Res-r16 ::= ENUMERATED
type MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16EnumeratedNothing = iota
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16EnumeratedN2
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16EnumeratedN4
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16EnumeratedN8
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16EnumeratedN16
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16EnumeratedN32
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberaperiodiccsiRsResR16EnumeratedN64
)
