package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedJointTCI-r17-maxActivatedTCIAcrossCC-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedjointtciR17MaxactivatedtciacrossccR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedjointtciR17MaxactivatedtciacrossccR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedjointtciR17MaxactivatedtciacrossccR17EnumeratedN1
	MimoParametersperbandUnifiedjointtciR17MaxactivatedtciacrossccR17EnumeratedN2
	MimoParametersperbandUnifiedjointtciR17MaxactivatedtciacrossccR17EnumeratedN4
	MimoParametersperbandUnifiedjointtciR17MaxactivatedtciacrossccR17EnumeratedN8
	MimoParametersperbandUnifiedjointtciR17MaxactivatedtciacrossccR17EnumeratedN16
)
