package ies

import "rrc/utils"

// MIMO-ParametersPerBand-unifiedJointTCI-r17-maxConfiguredJointTCI-r17 ::= ENUMERATED
type MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedNothing = iota
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN8
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN12
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN16
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN24
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN32
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN48
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN64
	MimoParametersperbandUnifiedjointtciR17MaxconfiguredjointtciR17EnumeratedN128
)
