package ies

import "rrc/utils"

// MIMO-ParametersPerBand-beamSwitchTiming-scs-120kHz ::= ENUMERATED
type MimoParametersperbandBeamswitchtimingScs120khz struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandBeamswitchtimingScs120khzEnumeratedNothing = iota
	MimoParametersperbandBeamswitchtimingScs120khzEnumeratedSym14
	MimoParametersperbandBeamswitchtimingScs120khzEnumeratedSym28
	MimoParametersperbandBeamswitchtimingScs120khzEnumeratedSym48
	MimoParametersperbandBeamswitchtimingScs120khzEnumeratedSym224
	MimoParametersperbandBeamswitchtimingScs120khzEnumeratedSym336
)
