package ies

import "rrc/utils"

// MIMO-ParametersPerBand-multiDCI-multiTRP-Parameters-r16-maxNumberActivatedTCI-States-r16-maxTotalNumberAcrossCORESET-Pool-r16 ::= ENUMERATED
type MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxtotalnumberacrosscoresetPoolR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxtotalnumberacrosscoresetPoolR16EnumeratedNothing = iota
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxtotalnumberacrosscoresetPoolR16EnumeratedN2
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxtotalnumberacrosscoresetPoolR16EnumeratedN4
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxtotalnumberacrosscoresetPoolR16EnumeratedN8
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxtotalnumberacrosscoresetPoolR16EnumeratedN16
)
