package ies

import "rrc/utils"

// MIMO-ParametersPerBand-ssb-csirs-SINR-measurement-r16-supportedSINR-meas-r16 ::= ENUMERATED
type MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedsinrMeasR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedsinrMeasR16EnumeratedNothing = iota
	MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedsinrMeasR16EnumeratedSsbwithcsi_Im
	MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedsinrMeasR16EnumeratedSsbwithnzp_Imr
	MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedsinrMeasR16EnumeratedCsirswithnzp_Imr
	MimoParametersperbandSsbCsirsSinrMeasurementR16SupportedsinrMeasR16EnumeratedCsi_Rswithoutimr
)
