package ies

import "rrc/utils"

// MIMO-ParametersPerBand-ssb-csirs-SINR-measurement-r16-maxNumberSSB-CSIRS-OneTx-CMR-r16 ::= ENUMERATED
type MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsOnetxCmrR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsOnetxCmrR16EnumeratedNothing = iota
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsOnetxCmrR16EnumeratedN8
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsOnetxCmrR16EnumeratedN16
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsOnetxCmrR16EnumeratedN32
	MimoParametersperbandSsbCsirsSinrMeasurementR16MaxnumberssbCsirsOnetxCmrR16EnumeratedN64
)
