package ies

import "rrc/utils"

// MIMO-ParametersPerBand-multiDCI-multiTRP-Parameters-r16-maxNumberActivatedTCI-States-r16-maxNumberPerCORESET-Pool-r16 ::= ENUMERATED
type MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxnumberpercoresetPoolR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxnumberpercoresetPoolR16EnumeratedNothing = iota
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxnumberpercoresetPoolR16EnumeratedN1
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxnumberpercoresetPoolR16EnumeratedN2
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxnumberpercoresetPoolR16EnumeratedN4
	MimoParametersperbandMultidciMultitrpParametersR16MaxnumberactivatedtciStatesR16MaxnumberpercoresetPoolR16EnumeratedN8
)
