package ies

import "rrc/utils"

// MIMO-ParametersPerBand-supportTDM-SchemeA-r16 ::= ENUMERATED
type MimoParametersperbandSupporttdmSchemeaR16 struct {
	Value utils.ENUMERATED
}

const (
	MimoParametersperbandSupporttdmSchemeaR16EnumeratedNothing = iota
	MimoParametersperbandSupporttdmSchemeaR16EnumeratedKb3
	MimoParametersperbandSupporttdmSchemeaR16EnumeratedKb5
	MimoParametersperbandSupporttdmSchemeaR16EnumeratedKb10
	MimoParametersperbandSupporttdmSchemeaR16EnumeratedKb20
	MimoParametersperbandSupporttdmSchemeaR16EnumeratedNorestriction
)
