package ies

import "rrc/utils"

// MinSchedulingOffsetPreferenceConfig-r16-minSchedulingOffsetPreferenceProhibitTimer-r16 ::= ENUMERATED
type MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16 struct {
	Value utils.ENUMERATED
}

const (
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedNothing = iota
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS0
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS0dot5
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS1
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS2
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS3
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS4
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS5
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS6
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS7
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS8
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS9
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS10
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS20
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedS30
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedSpare2
	MinschedulingoffsetpreferenceconfigR16MinschedulingoffsetpreferenceprohibittimerR16EnumeratedSpare1
)
