package ies

import "rrc/utils"

// MobilityStateParameters-t-HystNormal ::= ENUMERATED
type MobilitystateparametersTHystnormal struct {
	Value utils.ENUMERATED
}

const (
	MobilitystateparametersTHystnormalEnumeratedNothing = iota
	MobilitystateparametersTHystnormalEnumeratedS30
	MobilitystateparametersTHystnormalEnumeratedS60
	MobilitystateparametersTHystnormalEnumeratedS120
	MobilitystateparametersTHystnormalEnumeratedS180
	MobilitystateparametersTHystnormalEnumeratedS240
	MobilitystateparametersTHystnormalEnumeratedSpare3
	MobilitystateparametersTHystnormalEnumeratedSpare2
	MobilitystateparametersTHystnormalEnumeratedSpare1
)
