package ies

import "rrc/utils"

// MRB-PDCP-ConfigBroadcast-r17-t-Reordering-r17 ::= ENUMERATED
type MrbPdcpConfigbroadcastR17TReorderingR17 struct {
	Value utils.ENUMERATED
}

const (
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedNothing = iota
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs1
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs10
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs40
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs160
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs500
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs1000
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs1250
	MrbPdcpConfigbroadcastR17TReorderingR17EnumeratedMs2750
)
