package ies

import "rrc/utils"

// MRDC-Parameters-v1630-maxUplinkDutyCycle-interBandENDC-FDD-TDD-PC2-r16-maxUplinkDutyCycle-FDD-TDD-EN-DC2-r16 ::= ENUMERATED
type MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16 struct {
	Value utils.ENUMERATED
}

const (
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedNothing = iota
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN30
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN40
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN50
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN60
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN70
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN80
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN90
	MrdcParametersV1630MaxuplinkdutycycleInterbandendcFddTddPc2R16MaxuplinkdutycycleFddTddEnDc2R16EnumeratedN100
)
