package ies

import "rrc/utils"

// MUSIM-GapAssistanceConfig-r17-musim-GapProhibitTimer-r17 ::= ENUMERATED
type MusimGapassistanceconfigR17MusimGapprohibittimerR17 struct {
	Value utils.ENUMERATED
}

const (
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedNothing = iota
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS0
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS0dot1
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS0dot2
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS0dot3
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS0dot4
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS0dot5
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS1
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS2
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS3
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS4
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS5
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS6
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS7
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS8
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS9
	MusimGapassistanceconfigR17MusimGapprohibittimerR17EnumeratedS10
)
