package ies

import "rrc/utils"

// MUSIM-LeaveAssistanceConfig-r17-musim-LeaveWithoutResponseTimer-r17 ::= ENUMERATED
type MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17 struct {
	Value utils.ENUMERATED
}

const (
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedNothing = iota
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedMs10
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedMs20
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedMs40
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedMs60
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedMs80
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedMs100
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedSpare2
	MusimLeaveassistanceconfigR17MusimLeavewithoutresponsetimerR17EnumeratedSpare1
)
