package ies

import "rrc/utils"

// NAICS-Capability-Entry-r12-numberOfAggregatedPRB-r12 ::= ENUMERATED
type NaicsCapabilityEntryR12NumberofaggregatedprbR12 struct {
	Value utils.ENUMERATED
}

const (
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedNothing = iota
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN50
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN75
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN100
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN125
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN150
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN175
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN200
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN225
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN250
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN275
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN300
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN350
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN400
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN450
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedN500
	NaicsCapabilityEntryR12NumberofaggregatedprbR12EnumeratedSpare
)
