package ies

import "rrc/utils"

// NAICS-Capability-Entry-numberOfAggregatedPRB ::= ENUMERATED
type NaicsCapabilityEntryNumberofaggregatedprb struct {
	Value utils.ENUMERATED
}

const (
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedNothing = iota
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN50
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN75
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN100
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN125
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN150
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN175
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN200
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN225
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN250
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN275
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN300
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN350
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN400
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN450
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedN500
	NaicsCapabilityEntryNumberofaggregatedprbEnumeratedSpare
)
