package ies

// NeighCellSI-AcquisitionParameters-r9 ::= SEQUENCE
type NeighcellsiAcquisitionparametersR9 struct {
	IntrafreqsiAcquisitionforhoR9 *NeighcellsiAcquisitionparametersR9IntrafreqsiAcquisitionforhoR9
	InterfreqsiAcquisitionforhoR9 *NeighcellsiAcquisitionparametersR9InterfreqsiAcquisitionforhoR9
	UtranSiAcquisitionforhoR9     *NeighcellsiAcquisitionparametersR9UtranSiAcquisitionforhoR9
}
