package ies

import "rrc/utils"

// NonCellDefiningSSB-r17-ssb-Periodicity-r17 ::= ENUMERATED
type NoncelldefiningssbR17SsbPeriodicityR17 struct {
	Value utils.ENUMERATED
}

const (
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedNothing = iota
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedMs5
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedMs10
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedMs20
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedMs40
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedMs80
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedMs160
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedSpare2
	NoncelldefiningssbR17SsbPeriodicityR17EnumeratedSpare1
)
