package ies

import "rrc/utils"

// NPDCCH-SC-MCCH-Config-NB-r14-npdcch-Offset-SC-MCCH-r14 ::= ENUMERATED
type NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14 struct {
	Value utils.ENUMERATED
}

const (
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedNothing = iota
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedZero
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedOneeighth
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedOnequarter
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedThreeeighth
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedOnehalf
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedFiveeighth
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedThreequarter
	NpdcchScMcchConfigNbR14NpdcchOffsetScMcchR14EnumeratedSeveneighth
)
