package ies

import "rrc/utils"

// NPDCCH-ConfigDedicated-NB-r13-npdcch-NumRepetitions-r13 ::= ENUMERATED
type NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13 struct {
	Value utils.ENUMERATED
}

const (
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedNothing = iota
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR1
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR2
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR4
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR8
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR16
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR32
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR64
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR128
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR256
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR512
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR1024
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedR2048
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedSpare4
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedSpare3
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedSpare2
	NpdcchConfigdedicatedNbR13NpdcchNumrepetitionsR13EnumeratedSpare1
)
