package ies

import "rrc/utils"

// NPDCCH-SC-MCCH-Config-NB-r14-npdcch-StartSF-SC-MCCH-r14 ::= ENUMERATED
type NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14 struct {
	Value utils.ENUMERATED
}

const (
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedNothing = iota
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV1dot5
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV2
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV4
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV8
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV16
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV32
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV48
	NpdcchScMcchConfigNbR14NpdcchStartsfScMcchR14EnumeratedV64
)
