package ies

import "rrc/utils"

// NPDCCH-SC-MCCH-Config-NB-r14-npdcch-NumRepetitions-SC-MCCH-r14 ::= ENUMERATED
type NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14 struct {
	Value utils.ENUMERATED
}

const (
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedNothing = iota
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR1
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR2
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR4
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR8
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR16
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR32
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR64
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR128
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR256
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR512
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR1024
	NpdcchScMcchConfigNbR14NpdcchNumrepetitionsScMcchR14EnumeratedR2048
)
