package ies

import "rrc/utils"

// NPDCCH-ConfigDedicated-NB-r13-npdcch-StartSF-USS-r13 ::= ENUMERATED
type NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13 struct {
	Value utils.ENUMERATED
}

const (
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedNothing = iota
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV1dot5
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV2
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV4
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV8
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV16
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV32
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV48
	NpdcchConfigdedicatedNbR13NpdcchStartsfUssR13EnumeratedV64
)
