package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r13-nprach-SubcarrierOffset-r13 ::= ENUMERATED
type NprachParametersNbR13NprachSubcarrieroffsetR13 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedNothing = iota
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedN0
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedN12
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedN24
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedN36
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedN2
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedN18
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedN34
	NprachParametersNbR13NprachSubcarrieroffsetR13EnumeratedSpare1
)
