package ies

import "rrc/utils"

// NPRACH-ParametersFmt2-NB-r15-nprach-Parameters-r15-npdcch-NumRepetitions-RA-r15 ::= ENUMERATED
type NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedNothing = iota
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR1
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR2
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR4
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR8
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR16
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR32
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR64
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR128
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR256
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR512
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR1024
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR2048
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare4
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare3
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare2
	NprachParametersfmt2NbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare1
)
