package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r14-nprach-Parameters-r14-nprach-SubcarrierOffset-r14 ::= ENUMERATED
type NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedNothing = iota
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedN0
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedN12
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedN24
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedN36
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedN2
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedN18
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedN34
	NprachParametersNbR14NprachParametersR14NprachSubcarrieroffsetR14EnumeratedSpare1
)
