package ies

import "rrc/utils"

// NPRACH-ConfigSIB-NB-v1530-tdd-Parameters-r15-nprach-PreambleFormat-r15 ::= ENUMERATED
type NprachConfigsibNbV1530TddParametersR15NprachPreambleformatR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachConfigsibNbV1530TddParametersR15NprachPreambleformatR15EnumeratedNothing = iota
	NprachConfigsibNbV1530TddParametersR15NprachPreambleformatR15EnumeratedFmt0
	NprachConfigsibNbV1530TddParametersR15NprachPreambleformatR15EnumeratedFmt1
	NprachConfigsibNbV1530TddParametersR15NprachPreambleformatR15EnumeratedFmt2
	NprachConfigsibNbV1530TddParametersR15NprachPreambleformatR15EnumeratedFmt0_A
	NprachConfigsibNbV1530TddParametersR15NprachPreambleformatR15EnumeratedFmt1_A
)
