package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r13-nprach-StartTime-r13 ::= ENUMERATED
type NprachParametersNbR13NprachStarttimeR13 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR13NprachStarttimeR13EnumeratedNothing = iota
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs8
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs16
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs32
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs64
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs128
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs256
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs512
	NprachParametersNbR13NprachStarttimeR13EnumeratedMs1024
)
