package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r14-nprach-Parameters-r14-nprach-StartTime-r14 ::= ENUMERATED
type NprachParametersNbR14NprachParametersR14NprachStarttimeR14 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedNothing = iota
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs8
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs16
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs32
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs64
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs128
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs256
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs512
	NprachParametersNbR14NprachParametersR14NprachStarttimeR14EnumeratedMs1024
)
