package ies

import "rrc/utils"

// NPRACH-ParametersTDD-NB-r15-nprach-Parameters-r15-npdcch-StartSF-CSS-RA-r15 ::= ENUMERATED
type NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedNothing = iota
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV4
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV8
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV16
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV32
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV48
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV64
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV96
	NprachParameterstddNbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV128
)
