package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r14-nprach-Parameters-r14-npdcch-NumRepetitions-RA-r14 ::= ENUMERATED
type NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedNothing = iota
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR1
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR2
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR4
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR8
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR16
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR32
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR64
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR128
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR256
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR512
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR1024
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedR2048
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedSpare4
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedSpare3
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedSpare2
	NprachParametersNbR14NprachParametersR14NpdcchNumrepetitionsRaR14EnumeratedSpare1
)
