package ies

import "rrc/utils"

// NPRACH-ProbabilityAnchor-NB-r14-nprach-ProbabilityAnchor-r14 ::= ENUMERATED
type NprachProbabilityanchorNbR14NprachProbabilityanchorR14 struct {
	Value utils.ENUMERATED
}

const (
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedNothing = iota
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedZero
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnesixteenth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnefifteenth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnefourteenth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnethirteenth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnetwelfth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOneeleventh
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnetenth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOneninth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOneeighth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOneseventh
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnesixth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnefifth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnefourth
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnethird
	NprachProbabilityanchorNbR14NprachProbabilityanchorR14EnumeratedOnehalf
)
