package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r14-nprach-Parameters-r14-nprach-NumCBRA-StartSubcarriers-r14 ::= ENUMERATED
type NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedNothing = iota
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN8
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN10
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN11
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN12
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN20
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN22
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN23
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN24
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN32
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN34
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN35
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN36
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN40
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN44
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN46
	NprachParametersNbR14NprachParametersR14NprachNumcbraStartsubcarriersR14EnumeratedN48
)
