package ies

import "rrc/utils"

// NPRACH-ParametersFmt2-NB-r15-nprach-Parameters-r15-npdcch-StartSF-CSS-RA-r15 ::= ENUMERATED
type NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedNothing = iota
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV1dot5
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV2
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV4
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV8
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV16
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV32
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV48
	NprachParametersfmt2NbR15NprachParametersR15NpdcchStartsfCssRaR15EnumeratedV64
)
