package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r13-npdcch-NumRepetitions-RA-r13 ::= ENUMERATED
type NprachParametersNbR13NpdcchNumrepetitionsRaR13 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedNothing = iota
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR1
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR2
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR4
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR8
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR16
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR32
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR64
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR128
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR256
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR512
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR1024
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedR2048
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedSpare4
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedSpare3
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedSpare2
	NprachParametersNbR13NpdcchNumrepetitionsRaR13EnumeratedSpare1
)
