package ies

import "rrc/utils"

// NPRACH-ParametersTDD-NB-r15-nprach-Parameters-r15-nprach-NumCBRA-StartSubcarriers-r15 ::= ENUMERATED
type NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedNothing = iota
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN8
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN10
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN11
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN12
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN20
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN22
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN23
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN24
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN32
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN34
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN35
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN36
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN40
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN44
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN46
	NprachParameterstddNbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN48
)
