package ies

import "rrc/utils"

// NPRACH-ParametersTDD-NB-r15-nprach-Parameters-r15-nprach-StartTime-r15 ::= ENUMERATED
type NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedNothing = iota
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs10
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs20
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs40
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs80
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs160
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs320
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs640
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs1280
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs2560
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedMs5120
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedSpare6
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedSpare5
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedSpare4
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedSpare3
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedSpare2
	NprachParameterstddNbR15NprachParametersR15NprachStarttimeR15EnumeratedSpare1
)
