package ies

import "rrc/utils"

// NPRACH-ParametersTDD-NB-r15-nprach-Parameters-r15-npdcch-NumRepetitions-RA-r15 ::= ENUMERATED
type NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedNothing = iota
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR1
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR2
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR4
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR8
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR16
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR32
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR64
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR128
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR256
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR512
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR1024
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedR2048
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare4
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare3
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare2
	NprachParameterstddNbR15NprachParametersR15NpdcchNumrepetitionsRaR15EnumeratedSpare1
)
