package ies

import "rrc/utils"

// NPRACH-ParametersTDD-NB-r15-nprach-Parameters-r15-nprach-SubcarrierOffset-r15 ::= ENUMERATED
type NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedNothing = iota
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN0
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN12
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN24
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN36
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN2
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN18
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN34
	NprachParameterstddNbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedSpare1
)
