package ies

import "rrc/utils"

// NPRACH-ParametersTDD-NB-r15-nprach-Parameters-r15-nprach-Periodicity-r15 ::= ENUMERATED
type NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedNothing = iota
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs80
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs160
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs320
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs640
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs1280
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs2560
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs5120
	NprachParameterstddNbR15NprachParametersR15NprachPeriodicityR15EnumeratedMs10240
)
