package ies

import "rrc/utils"

// NPRACH-ParametersFmt2-NB-r15-nprach-Parameters-r15-nprach-NumSubcarriers-r15 ::= ENUMERATED
type NprachParametersfmt2NbR15NprachParametersR15NprachNumsubcarriersR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersfmt2NbR15NprachParametersR15NprachNumsubcarriersR15EnumeratedNothing = iota
	NprachParametersfmt2NbR15NprachParametersR15NprachNumsubcarriersR15EnumeratedN36
	NprachParametersfmt2NbR15NprachParametersR15NprachNumsubcarriersR15EnumeratedN72
	NprachParametersfmt2NbR15NprachParametersR15NprachNumsubcarriersR15EnumeratedN108
	NprachParametersfmt2NbR15NprachParametersR15NprachNumsubcarriersR15EnumeratedN144
)
