package ies

import "rrc/utils"

// NPRACH-ParametersFmt2-NB-r15-nprach-Parameters-r15-nprach-SubcarrierOffset-r15 ::= ENUMERATED
type NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedNothing = iota
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN0
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN36
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN72
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN108
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN6
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN54
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN102
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN42
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN78
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN90
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN12
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN24
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN48
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN84
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN60
	NprachParametersfmt2NbR15NprachParametersR15NprachSubcarrieroffsetR15EnumeratedN18
)
