package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r14-nprach-Parameters-r14-npdcch-StartSF-CSS-RA-r14 ::= ENUMERATED
type NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedNothing = iota
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV1dot5
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV2
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV4
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV8
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV16
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV32
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV48
	NprachParametersNbR14NprachParametersR14NpdcchStartsfCssRaR14EnumeratedV64
)
