package ies

import "rrc/utils"

// NPRACH-ParametersFmt2-NB-r15-nprach-Parameters-r15-nprach-NumCBRA-StartSubcarriers-r15 ::= ENUMERATED
type NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedNothing = iota
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN24
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN30
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN33
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN36
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN60
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN66
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN69
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN72
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN96
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN102
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN105
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN108
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN120
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN132
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN138
	NprachParametersfmt2NbR15NprachParametersR15NprachNumcbraStartsubcarriersR15EnumeratedN144
)
