package ies

import "rrc/utils"

// NPRACH-Parameters-NB-r14-nprach-Parameters-r14-nprach-Periodicity-r14 ::= ENUMERATED
type NprachParametersNbR14NprachParametersR14NprachPeriodicityR14 struct {
	Value utils.ENUMERATED
}

const (
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedNothing = iota
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs40
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs80
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs160
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs240
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs320
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs640
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs1280
	NprachParametersNbR14NprachParametersR14NprachPeriodicityR14EnumeratedMs2560
)
