package ies

import "rrc/utils"

// NPUSCH-ConfigCommon-NB-r13-srs-SubframeConfig-r13 ::= ENUMERATED
type NpuschConfigcommonNbR13SrsSubframeconfigR13 struct {
	Value utils.ENUMERATED
}

const (
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedNothing = iota
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc0
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc1
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc2
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc3
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc4
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc5
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc6
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc7
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc8
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc9
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc10
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc11
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc12
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc13
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc14
	NpuschConfigcommonNbR13SrsSubframeconfigR13EnumeratedSc15
)
