package ies

import "rrc/utils"

// NR-DL-PRS-PDC-ResourceSet-r17-numSymbols-r17 ::= ENUMERATED
type NrDlPrsPdcResourcesetR17NumsymbolsR17 struct {
	Value utils.ENUMERATED
}

const (
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedNothing = iota
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedN2
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedN4
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedN6
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedN12
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedSpare4
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedSpare3
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedSpare2
	NrDlPrsPdcResourcesetR17NumsymbolsR17EnumeratedSpare1
)
