package ies

// NR-DL-PRS-Periodicity-and-ResourceSetSlotOffset-r17 ::= CHOICE
// Extensible
const (
	NrDlPrsPeriodicityAndResourcesetslotoffsetR17ChoiceNothing = iota
	NrDlPrsPeriodicityAndResourcesetslotoffsetR17ChoiceScs15R17
	NrDlPrsPeriodicityAndResourcesetslotoffsetR17ChoiceScs30R17
	NrDlPrsPeriodicityAndResourcesetslotoffsetR17ChoiceScs60R17
	NrDlPrsPeriodicityAndResourcesetslotoffsetR17ChoiceScs120R17
)

type NrDlPrsPeriodicityAndResourcesetslotoffsetR17 struct {
	Choice    uint64
	Scs15R17  *NrDlPrsPeriodicityAndResourcesetslotoffsetR17Scs15R17
	Scs30R17  *NrDlPrsPeriodicityAndResourcesetslotoffsetR17Scs30R17
	Scs60R17  *NrDlPrsPeriodicityAndResourcesetslotoffsetR17Scs60R17
	Scs120R17 *NrDlPrsPeriodicityAndResourcesetslotoffsetR17Scs120R17
}
