package ies

import "rrc/utils"

// NR-PRS-MeasurementInfo-r16-nr-MeasPRS-length-r16 ::= ENUMERATED
type NrPrsMeasurementinfoR16NrMeasprsLengthR16 struct {
	Value utils.ENUMERATED
}

const (
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedNothing = iota
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs1dot5
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs3
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs3dot5
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs4
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs5dot5
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs6
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs10
	NrPrsMeasurementinfoR16NrMeasprsLengthR16EnumeratedMs20
)
