package ies

import "rrc/utils"

// NRSRP-ChangeThresh-NB-r16 ::= ENUMERATED
type NrsrpChangethreshNbR16 struct {
	Value utils.ENUMERATED
}

const (
	NrsrpChangethreshNbR16EnumeratedNothing = iota
	NrsrpChangethreshNbR16EnumeratedDb4
	NrsrpChangethreshNbR16EnumeratedDb6
	NrsrpChangethreshNbR16EnumeratedDb8
	NrsrpChangethreshNbR16EnumeratedDb10
	NrsrpChangethreshNbR16EnumeratedDb14
	NrsrpChangethreshNbR16EnumeratedDb18
	NrsrpChangethreshNbR16EnumeratedDb22
	NrsrpChangethreshNbR16EnumeratedDb26
	NrsrpChangethreshNbR16EnumeratedDb30
	NrsrpChangethreshNbR16EnumeratedDb34
	NrsrpChangethreshNbR16EnumeratedSpare6
	NrsrpChangethreshNbR16EnumeratedSpare5
	NrsrpChangethreshNbR16EnumeratedSpare4
	NrsrpChangethreshNbR16EnumeratedSpare3
	NrsrpChangethreshNbR16EnumeratedSpare2
	NrsrpChangethreshNbR16EnumeratedSpare1
)
