package ies

import "rrc/utils"

// NTN-Config-r17-ntn-UlSyncValidityDuration-r17 ::= ENUMERATED
type NtnConfigR17NtnUlsyncvaliditydurationR17 struct {
	Value utils.ENUMERATED
}

const (
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedNothing = iota
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS5
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS10
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS15
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS20
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS25
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS30
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS35
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS40
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS45
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS50
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS55
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS60
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS120
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS180
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS240
	NtnConfigR17NtnUlsyncvaliditydurationR17EnumeratedS900
)
