package ies

import "rrc/utils"

// OnDemandSIB-Request-r16-onDemandSIB-RequestProhibitTimer-r16 ::= ENUMERATED
type OndemandsibRequestR16OndemandsibRequestprohibittimerR16 struct {
	Value utils.ENUMERATED
}

const (
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedNothing = iota
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS0
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS0dot5
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS1
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS2
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS5
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS10
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS20
	OndemandsibRequestR16OndemandsibRequestprohibittimerR16EnumeratedS30
)
