package ies

// OtherConfig-delayBudgetReportingConfig-setup ::= SEQUENCE
type OtherconfigDelaybudgetreportingconfigSetup struct {
	Delaybudgetreportingprohibittimer OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimer
}
