package ies

import "rrc/utils"

// OtherConfig-delayBudgetReportingConfig-setup-delayBudgetReportingProhibitTimer ::= ENUMERATED
type OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimer struct {
	Value utils.ENUMERATED
}

const (
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedNothing = iota
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS0
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS0dot4
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS0dot8
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS1dot6
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS3
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS6
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS12
	OtherconfigDelaybudgetreportingconfigSetupDelaybudgetreportingprohibittimerEnumeratedS30
)
