package ies

import "rrc/utils"

// OverheatingAssistanceConfig-overheatingIndicationProhibitTimer ::= ENUMERATED
type OverheatingassistanceconfigOverheatingindicationprohibittimer struct {
	Value utils.ENUMERATED
}

const (
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedNothing = iota
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS0
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS0dot5
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS1
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS2
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS5
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS10
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS20
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS30
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS60
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS90
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS120
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS300
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedS600
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedSpare3
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedSpare2
	OverheatingassistanceconfigOverheatingindicationprohibittimerEnumeratedSpare1
)
