package ies

import "rrc/utils"

// PCCH-Config-NB-r14-npdcch-NumRepetitionPaging-r14 ::= ENUMERATED
type PcchConfigNbR14NpdcchNumrepetitionpagingR14 struct {
	Value utils.ENUMERATED
}

const (
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedNothing = iota
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR1
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR2
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR4
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR8
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR16
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR32
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR64
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR128
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR256
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR512
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR1024
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedR2048
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedSpare4
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedSpare3
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedSpare2
	PcchConfigNbR14NpdcchNumrepetitionpagingR14EnumeratedSpare1
)
