package ies

import "rrc/utils"

// PCCH-Config-NB-r13-npdcch-NumRepetitionPaging-r13 ::= ENUMERATED
type PcchConfigNbR13NpdcchNumrepetitionpagingR13 struct {
	Value utils.ENUMERATED
}

const (
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedNothing = iota
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR1
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR2
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR4
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR8
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR16
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR32
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR64
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR128
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR256
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR512
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR1024
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedR2048
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedSpare4
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedSpare3
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedSpare2
	PcchConfigNbR13NpdcchNumrepetitionpagingR13EnumeratedSpare1
)
