package ies

import "rrc/utils"

// PDCCH-RepetitionParameters-r17-limitX-AcrossCC-r17 ::= ENUMERATED
type PdcchRepetitionparametersR17LimitxAcrossccR17 struct {
	Value utils.ENUMERATED
}

const (
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedNothing = iota
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN4
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN8
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN16
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN32
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN44
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN64
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN128
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN256
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedN512
	PdcchRepetitionparametersR17LimitxAcrossccR17EnumeratedNolimit
)
