package ies

// PDCCH-CandidateReductions-r13-setup ::= SEQUENCE
type PdcchCandidatereductionsR13Setup struct {
	PdcchCandidatereductional1R13 PdcchCandidatereductionvalueR13
	PdcchCandidatereductional2R13 PdcchCandidatereductionvalueR13
	PdcchCandidatereductional3R13 PdcchCandidatereductionvalueR13
	PdcchCandidatereductional4R13 PdcchCandidatereductionvalueR13
	PdcchCandidatereductional5R13 PdcchCandidatereductionvalueR13
}
