package ies

// PDCCH-CandidateReductionsLAA-UL-r14-setup ::= SEQUENCE
type PdcchCandidatereductionslaaUlR14Setup struct {
	PdcchCandidatereductional1R14 PdcchCandidatereductionvalueR13
	PdcchCandidatereductional2R14 PdcchCandidatereductionvalueR13
	PdcchCandidatereductional3R14 PdcchCandidatereductionvalueR14
	PdcchCandidatereductional4R14 PdcchCandidatereductionvalueR14
	PdcchCandidatereductional5R14 PdcchCandidatereductionvalueR14
}
