package ies

import "rrc/utils"

// PDCP-Parameters-maxNumberROHC-ContextSessions ::= ENUMERATED
type PdcpParametersMaxnumberrohcContextsessions struct {
	Value utils.ENUMERATED
}

const (
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedNothing = iota
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs2
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs4
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs8
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs12
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs16
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs24
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs32
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs48
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs64
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs128
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs256
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs512
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs1024
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedCs16384
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedSpare2
	PdcpParametersMaxnumberrohcContextsessionsEnumeratedSpare1
)
