package ies

import "rrc/utils"

// PDCP-ParametersNR-r15-rohc-ContextMaxSessions-r15 ::= ENUMERATED
type PdcpParametersnrR15RohcContextmaxsessionsR15 struct {
	Value utils.ENUMERATED
}

const (
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedNothing = iota
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs2
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs4
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs8
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs12
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs16
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs24
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs32
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs48
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs64
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs128
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs256
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs512
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs1024
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedCs16384
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedSpare2
	PdcpParametersnrR15RohcContextmaxsessionsR15EnumeratedSpare1
)
