package ies

import "rrc/utils"

// PDCP-Config-t-Reordering ::= ENUMERATED
type PdcpConfigTReordering struct {
	Value utils.ENUMERATED
}

const (
	PdcpConfigTReorderingEnumeratedNothing = iota
	PdcpConfigTReorderingEnumeratedMs0
	PdcpConfigTReorderingEnumeratedMs1
	PdcpConfigTReorderingEnumeratedMs2
	PdcpConfigTReorderingEnumeratedMs4
	PdcpConfigTReorderingEnumeratedMs5
	PdcpConfigTReorderingEnumeratedMs8
	PdcpConfigTReorderingEnumeratedMs10
	PdcpConfigTReorderingEnumeratedMs15
	PdcpConfigTReorderingEnumeratedMs20
	PdcpConfigTReorderingEnumeratedMs30
	PdcpConfigTReorderingEnumeratedMs40
	PdcpConfigTReorderingEnumeratedMs50
	PdcpConfigTReorderingEnumeratedMs60
	PdcpConfigTReorderingEnumeratedMs80
	PdcpConfigTReorderingEnumeratedMs100
	PdcpConfigTReorderingEnumeratedMs120
	PdcpConfigTReorderingEnumeratedMs140
	PdcpConfigTReorderingEnumeratedMs160
	PdcpConfigTReorderingEnumeratedMs180
	PdcpConfigTReorderingEnumeratedMs200
	PdcpConfigTReorderingEnumeratedMs220
	PdcpConfigTReorderingEnumeratedMs240
	PdcpConfigTReorderingEnumeratedMs260
	PdcpConfigTReorderingEnumeratedMs280
	PdcpConfigTReorderingEnumeratedMs300
	PdcpConfigTReorderingEnumeratedMs500
	PdcpConfigTReorderingEnumeratedMs750
	PdcpConfigTReorderingEnumeratedMs1000
	PdcpConfigTReorderingEnumeratedMs1250
	PdcpConfigTReorderingEnumeratedMs1500
	PdcpConfigTReorderingEnumeratedMs1750
	PdcpConfigTReorderingEnumeratedMs2000
	PdcpConfigTReorderingEnumeratedMs2250
	PdcpConfigTReorderingEnumeratedMs2500
	PdcpConfigTReorderingEnumeratedMs2750
	PdcpConfigTReorderingEnumeratedMs3000
	PdcpConfigTReorderingEnumeratedSpare28
	PdcpConfigTReorderingEnumeratedSpare27
	PdcpConfigTReorderingEnumeratedSpare26
	PdcpConfigTReorderingEnumeratedSpare25
	PdcpConfigTReorderingEnumeratedSpare24
	PdcpConfigTReorderingEnumeratedSpare23
	PdcpConfigTReorderingEnumeratedSpare22
	PdcpConfigTReorderingEnumeratedSpare21
	PdcpConfigTReorderingEnumeratedSpare20
	PdcpConfigTReorderingEnumeratedSpare19
	PdcpConfigTReorderingEnumeratedSpare18
	PdcpConfigTReorderingEnumeratedSpare17
	PdcpConfigTReorderingEnumeratedSpare16
	PdcpConfigTReorderingEnumeratedSpare15
	PdcpConfigTReorderingEnumeratedSpare14
	PdcpConfigTReorderingEnumeratedSpare13
	PdcpConfigTReorderingEnumeratedSpare12
	PdcpConfigTReorderingEnumeratedSpare11
	PdcpConfigTReorderingEnumeratedSpare10
	PdcpConfigTReorderingEnumeratedSpare09
	PdcpConfigTReorderingEnumeratedSpare08
	PdcpConfigTReorderingEnumeratedSpare07
	PdcpConfigTReorderingEnumeratedSpare06
	PdcpConfigTReorderingEnumeratedSpare05
	PdcpConfigTReorderingEnumeratedSpare04
	PdcpConfigTReorderingEnumeratedSpare03
	PdcpConfigTReorderingEnumeratedSpare02
	PdcpConfigTReorderingEnumeratedSpare01
)
