package ies

import "rrc/utils"

// PDCP-Parameters-NB-r13-maxNumberROHC-ContextSessions-r13 ::= ENUMERATED
type PdcpParametersNbR13MaxnumberrohcContextsessionsR13 struct {
	Value utils.ENUMERATED
}

const (
	PdcpParametersNbR13MaxnumberrohcContextsessionsR13EnumeratedNothing = iota
	PdcpParametersNbR13MaxnumberrohcContextsessionsR13EnumeratedCs2
	PdcpParametersNbR13MaxnumberrohcContextsessionsR13EnumeratedCs4
	PdcpParametersNbR13MaxnumberrohcContextsessionsR13EnumeratedCs8
	PdcpParametersNbR13MaxnumberrohcContextsessionsR13EnumeratedCs12
)
