package ies

// PDSCH-RE-MappingQCL-Config-r11-optionalSetOfFields-r11-mbsfn-SubframeConfigList-r11 ::= CHOICE
const (
	PdschReMappingqclConfigR11OptionalsetoffieldsR11MbsfnSubframeconfiglistR11ChoiceNothing = iota
	PdschReMappingqclConfigR11OptionalsetoffieldsR11MbsfnSubframeconfiglistR11ChoiceRelease
	PdschReMappingqclConfigR11OptionalsetoffieldsR11MbsfnSubframeconfiglistR11ChoiceSetup
)

type PdschReMappingqclConfigR11OptionalsetoffieldsR11MbsfnSubframeconfiglistR11 struct {
	Choice  uint64
	Release *struct{}
	Setup   *PdschReMappingqclConfigR11OptionalsetoffieldsR11MbsfnSubframeconfiglistR11Setup
}
