package ies

import "rrc/utils"

// PDSCH-Config-resourceAllocationType1GranularityDCI-1-2-r16 ::= ENUMERATED
type PdschConfigResourceallocationtype1granularitydci12R16 struct {
	Value utils.ENUMERATED
}

const (
	PdschConfigResourceallocationtype1granularitydci12R16EnumeratedNothing = iota
	PdschConfigResourceallocationtype1granularitydci12R16EnumeratedN2
	PdschConfigResourceallocationtype1granularitydci12R16EnumeratedN4
	PdschConfigResourceallocationtype1granularitydci12R16EnumeratedN8
	PdschConfigResourceallocationtype1granularitydci12R16EnumeratedN16
)
