package ies

import "rrc/utils"

// PDSCH-ConfigDedicated-v1530-altMCS-TableScalingConfig-r15 ::= ENUMERATED
type PdschConfigdedicatedV1530AltmcsTablescalingconfigR15 struct {
	Value utils.ENUMERATED
}

const (
	PdschConfigdedicatedV1530AltmcsTablescalingconfigR15EnumeratedNothing = iota
	PdschConfigdedicatedV1530AltmcsTablescalingconfigR15EnumeratedOdot5
	PdschConfigdedicatedV1530AltmcsTablescalingconfigR15EnumeratedOdot625
	PdschConfigdedicatedV1530AltmcsTablescalingconfigR15EnumeratedOdot75
	PdschConfigdedicatedV1530AltmcsTablescalingconfigR15EnumeratedOdot875
)
