package ies

import "rrc/utils"

// PDSCH-ServingCellConfig-nrofHARQ-ProcessesForPDSCH ::= ENUMERATED
type PdschServingcellconfigNrofharqProcessesforpdsch struct {
	Value utils.ENUMERATED
}

const (
	PdschServingcellconfigNrofharqProcessesforpdschEnumeratedNothing = iota
	PdschServingcellconfigNrofharqProcessesforpdschEnumeratedN2
	PdschServingcellconfigNrofharqProcessesforpdschEnumeratedN4
	PdschServingcellconfigNrofharqProcessesforpdschEnumeratedN6
	PdschServingcellconfigNrofharqProcessesforpdschEnumeratedN10
	PdschServingcellconfigNrofharqProcessesforpdschEnumeratedN12
	PdschServingcellconfigNrofharqProcessesforpdschEnumeratedN16
)
