package ies

import "rrc/utils"

// PDSCH-Config-beamAppTime-r17 ::= ENUMERATED
type PdschConfigBeamapptimeR17 struct {
	Value utils.ENUMERATED
}

const (
	PdschConfigBeamapptimeR17EnumeratedNothing = iota
	PdschConfigBeamapptimeR17EnumeratedN1
	PdschConfigBeamapptimeR17EnumeratedN2
	PdschConfigBeamapptimeR17EnumeratedN4
	PdschConfigBeamapptimeR17EnumeratedN7
	PdschConfigBeamapptimeR17EnumeratedN14
	PdschConfigBeamapptimeR17EnumeratedN28
	PdschConfigBeamapptimeR17EnumeratedN42
	PdschConfigBeamapptimeR17EnumeratedN56
	PdschConfigBeamapptimeR17EnumeratedN70
	PdschConfigBeamapptimeR17EnumeratedN84
	PdschConfigBeamapptimeR17EnumeratedN98
	PdschConfigBeamapptimeR17EnumeratedN112
	PdschConfigBeamapptimeR17EnumeratedN224
	PdschConfigBeamapptimeR17EnumeratedN336
	PdschConfigBeamapptimeR17EnumeratedSpare2
	PdschConfigBeamapptimeR17EnumeratedSpare1
)
