package ies

import "rrc/utils"

// PDSCH-Config-prb-BundlingTypeDCI-1-2-r16-dynamicBundling-r16-bundleSizeSet1-r16 ::= ENUMERATED
type PdschConfigPrbBundlingtypedci12R16DynamicbundlingR16Bundlesizeset1R16 struct {
	Value utils.ENUMERATED
}

const (
	PdschConfigPrbBundlingtypedci12R16DynamicbundlingR16Bundlesizeset1R16EnumeratedNothing = iota
	PdschConfigPrbBundlingtypedci12R16DynamicbundlingR16Bundlesizeset1R16EnumeratedN4
	PdschConfigPrbBundlingtypedci12R16DynamicbundlingR16Bundlesizeset1R16EnumeratedWideband
	PdschConfigPrbBundlingtypedci12R16DynamicbundlingR16Bundlesizeset1R16EnumeratedN2_Wideband
	PdschConfigPrbBundlingtypedci12R16DynamicbundlingR16Bundlesizeset1R16EnumeratedN4_Wideband
)
