package ies

import "rrc/utils"

// PDSCH-RE-MappingQCL-Config-r11-optionalSetOfFields-r11-pdsch-Start-r11 ::= ENUMERATED
type PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11 struct {
	Value utils.ENUMERATED
}

const (
	PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11EnumeratedNothing = iota
	PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11EnumeratedReserved
	PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11EnumeratedN1
	PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11EnumeratedN2
	PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11EnumeratedN3
	PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11EnumeratedN4
	PdschReMappingqclConfigR11OptionalsetoffieldsR11PdschStartR11EnumeratedAssigned
)
