package ies

import "rrc/utils"

// PeriodicalReportConfigNR-SL-r16-reportAmount-r16 ::= ENUMERATED
type PeriodicalreportconfignrSlR16ReportamountR16 struct {
	Value utils.ENUMERATED
}

const (
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedNothing = iota
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedR1
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedR2
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedR4
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedR8
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedR16
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedR32
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedR64
	PeriodicalreportconfignrSlR16ReportamountR16EnumeratedInfinity
)
