package ies

import "rrc/utils"

// PeriodicBSR-Timer-r12 ::= ENUMERATED
type PeriodicbsrTimerR12 struct {
	Value utils.ENUMERATED
}

const (
	PeriodicbsrTimerR12EnumeratedNothing = iota
	PeriodicbsrTimerR12EnumeratedSf5
	PeriodicbsrTimerR12EnumeratedSf10
	PeriodicbsrTimerR12EnumeratedSf16
	PeriodicbsrTimerR12EnumeratedSf20
	PeriodicbsrTimerR12EnumeratedSf32
	PeriodicbsrTimerR12EnumeratedSf40
	PeriodicbsrTimerR12EnumeratedSf64
	PeriodicbsrTimerR12EnumeratedSf80
	PeriodicbsrTimerR12EnumeratedSf128
	PeriodicbsrTimerR12EnumeratedSf160
	PeriodicbsrTimerR12EnumeratedSf320
	PeriodicbsrTimerR12EnumeratedSf640
	PeriodicbsrTimerR12EnumeratedSf1280
	PeriodicbsrTimerR12EnumeratedSf2560
	PeriodicbsrTimerR12EnumeratedInfinity
	PeriodicbsrTimerR12EnumeratedSpare1
)
