package ies

import "rrc/utils"

// PhyLayerParameters-v1530-stti-SPT-Capabilities-r15-maxLayersSlotOrSubslotPUSCH-r15 ::= ENUMERATED
type PhylayerparametersV1530SttiSptCapabilitiesR15MaxlayersslotorsubslotpuschR15 struct {
	Value utils.ENUMERATED
}

const (
	PhylayerparametersV1530SttiSptCapabilitiesR15MaxlayersslotorsubslotpuschR15EnumeratedNothing = iota
	PhylayerparametersV1530SttiSptCapabilitiesR15MaxlayersslotorsubslotpuschR15EnumeratedOnelayer
	PhylayerparametersV1530SttiSptCapabilitiesR15MaxlayersslotorsubslotpuschR15EnumeratedTwolayers
	PhylayerparametersV1530SttiSptCapabilitiesR15MaxlayersslotorsubslotpuschR15EnumeratedFourlayers
)
