package ies

import "rrc/utils"

// Phy-ParametersCommon-maxNumberSRS-PosPathLossEstimateAllServingCells-r16 ::= ENUMERATED
type PhyParameterscommonMaxnumbersrsPospathlossestimateallservingcellsR16 struct {
	Value utils.ENUMERATED
}

const (
	PhyParameterscommonMaxnumbersrsPospathlossestimateallservingcellsR16EnumeratedNothing = iota
	PhyParameterscommonMaxnumbersrsPospathlossestimateallservingcellsR16EnumeratedN1
	PhyParameterscommonMaxnumbersrsPospathlossestimateallservingcellsR16EnumeratedN4
	PhyParameterscommonMaxnumbersrsPospathlossestimateallservingcellsR16EnumeratedN8
	PhyParameterscommonMaxnumbersrsPospathlossestimateallservingcellsR16EnumeratedN16
)
