package ies

import "rrc/utils"

// Phy-ParametersCommon-maxTotalResourcesForAcrossFreqRanges-r16-maxNumberResAcrossCC-AcrossFR-r16 ::= ENUMERATED
type PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16 struct {
	Value utils.ENUMERATED
}

const (
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedNothing = iota
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN2
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN4
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN8
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN12
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN16
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN32
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN40
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN48
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN64
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN72
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN80
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN96
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN128
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberresacrossccAcrossfrR16EnumeratedN256
)
