package ies

import "rrc/utils"

// Phy-ParametersCommon-supportedActivatedPRS-ProcessingWindow-r17 ::= ENUMERATED
type PhyParameterscommonSupportedactivatedprsProcessingwindowR17 struct {
	Value utils.ENUMERATED
}

const (
	PhyParameterscommonSupportedactivatedprsProcessingwindowR17EnumeratedNothing = iota
	PhyParameterscommonSupportedactivatedprsProcessingwindowR17EnumeratedN2
	PhyParameterscommonSupportedactivatedprsProcessingwindowR17EnumeratedN3
	PhyParameterscommonSupportedactivatedprsProcessingwindowR17EnumeratedN4
)
