package ies

import "rrc/utils"

// Phy-ParametersFRX-Diff-maxTotalResourcesForOneFreqRange-r16-maxNumberResAcrossCC-OneFR-r16 ::= ENUMERATED
type PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16 struct {
	Value utils.ENUMERATED
}

const (
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedNothing = iota
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN2
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN4
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN8
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN12
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN16
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN32
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN40
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN48
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN64
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN72
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN80
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN96
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN128
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberresacrossccOnefrR16EnumeratedN256
)
