package ies

import "rrc/utils"

// Phy-ParametersFR1-pdsch-RE-MappingFR1-PerSlot ::= ENUMERATED
type PhyParametersfr1PdschReMappingfr1Perslot struct {
	Value utils.ENUMERATED
}

const (
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedNothing = iota
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN16
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN32
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN48
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN64
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN80
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN96
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN112
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN128
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN144
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN160
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN176
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN192
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN208
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN224
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN240
	PhyParametersfr1PdschReMappingfr1PerslotEnumeratedN256
)
