package ies

import "rrc/utils"

// Phy-ParametersFRX-Diff-maxTotalResourcesForOneFreqRange-r16-maxNumberResWithinSlotAcrossCC-OneFR-r16 ::= ENUMERATED
type PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16 struct {
	Value utils.ENUMERATED
}

const (
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedNothing = iota
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN2
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN4
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN8
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN12
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN16
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN32
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN64
	PhyParametersfrxDiffMaxtotalresourcesforonefreqrangeR16MaxnumberreswithinslotacrossccOnefrR16EnumeratedN128
)
