package ies

import "rrc/utils"

// Phy-ParametersCommon-maxTotalResourcesForAcrossFreqRanges-r16-maxNumberResWithinSlotAcrossCC-AcrossFR-r16 ::= ENUMERATED
type PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16 struct {
	Value utils.ENUMERATED
}

const (
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedNothing = iota
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN2
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN4
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN8
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN12
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN16
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN32
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN64
	PhyParameterscommonMaxtotalresourcesforacrossfreqrangesR16MaxnumberreswithinslotacrossccAcrossfrR16EnumeratedN128
)
