package ies

import "rrc/utils"

// Phy-ParametersFR2-maxNumberSRS-PosSpatialRelationsAllServingCells-r16 ::= ENUMERATED
type PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16 struct {
	Value utils.ENUMERATED
}

const (
	PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16EnumeratedNothing = iota
	PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16EnumeratedN0
	PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16EnumeratedN1
	PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16EnumeratedN2
	PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16EnumeratedN4
	PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16EnumeratedN8
	PhyParametersfr2MaxnumbersrsPosspatialrelationsallservingcellsR16EnumeratedN16
)
