package ies

import "rrc/utils"

// Phy-ParametersFR2-pdsch-RE-MappingFR2-PerSlot ::= ENUMERATED
type PhyParametersfr2PdschReMappingfr2Perslot struct {
	Value utils.ENUMERATED
}

const (
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedNothing = iota
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN16
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN32
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN48
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN64
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN80
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN96
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN112
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN128
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN144
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN160
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN176
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN192
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN208
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN224
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN240
	PhyParametersfr2PdschReMappingfr2PerslotEnumeratedN256
)
