package ies

import "rrc/utils"

// Phy-ParametersCommon-harqACK-separateMultiDCI-MultiTRP-r16-maxNumberLongPUCCHs-r16 ::= ENUMERATED
type PhyParameterscommonHarqackSeparatemultidciMultitrpR16MaxnumberlongpucchsR16 struct {
	Value utils.ENUMERATED
}

const (
	PhyParameterscommonHarqackSeparatemultidciMultitrpR16MaxnumberlongpucchsR16EnumeratedNothing = iota
	PhyParameterscommonHarqackSeparatemultidciMultitrpR16MaxnumberlongpucchsR16EnumeratedLongandlong
	PhyParameterscommonHarqackSeparatemultidciMultitrpR16MaxnumberlongpucchsR16EnumeratedLongandshort
	PhyParameterscommonHarqackSeparatemultidciMultitrpR16MaxnumberlongpucchsR16EnumeratedShortandshort
)
