package ies

import "rrc/utils"

// PhysCellIdRange-range ::= ENUMERATED
type PhyscellidrangeRange struct {
	Value utils.ENUMERATED
}

const (
	PhyscellidrangeRangeEnumeratedNothing = iota
	PhyscellidrangeRangeEnumeratedN4
	PhyscellidrangeRangeEnumeratedN8
	PhyscellidrangeRangeEnumeratedN12
	PhyscellidrangeRangeEnumeratedN16
	PhyscellidrangeRangeEnumeratedN24
	PhyscellidrangeRangeEnumeratedN32
	PhyscellidrangeRangeEnumeratedN48
	PhyscellidrangeRangeEnumeratedN64
	PhyscellidrangeRangeEnumeratedN84
	PhyscellidrangeRangeEnumeratedN96
	PhyscellidrangeRangeEnumeratedN128
	PhyscellidrangeRangeEnumeratedN168
	PhyscellidrangeRangeEnumeratedN252
	PhyscellidrangeRangeEnumeratedN504
	PhyscellidrangeRangeEnumeratedSpare2
	PhyscellidrangeRangeEnumeratedSpare1
)
