package ies

import "rrc/utils"

// PhysicalCellGroupConfig-harq-ACK-SpatialBundlingPUSCH-secondaryPUCCHgroup-r16 ::= ENUMERATED
type PhysicalcellgroupconfigHarqAckSpatialbundlingpuschSecondarypucchgroupR16 struct {
	Value utils.ENUMERATED
}

const (
	PhysicalcellgroupconfigHarqAckSpatialbundlingpuschSecondarypucchgroupR16EnumeratedNothing = iota
	PhysicalcellgroupconfigHarqAckSpatialbundlingpuschSecondarypucchgroupR16EnumeratedEnabled
	PhysicalcellgroupconfigHarqAckSpatialbundlingpuschSecondarypucchgroupR16EnumeratedDisabled
)
