package ies

import "rrc/utils"

// PMCH-Config-r12-mch-SchedulingPeriod-r12 ::= ENUMERATED
type PmchConfigR12MchSchedulingperiodR12 struct {
	Value utils.ENUMERATED
}

const (
	PmchConfigR12MchSchedulingperiodR12EnumeratedNothing = iota
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf4
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf8
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf16
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf32
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf64
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf128
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf256
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf512
	PmchConfigR12MchSchedulingperiodR12EnumeratedRf1024
)
