package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxNumOfPeriodicSRSposResourcesPerSlot-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN1
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN2
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN3
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN4
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN5
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN6
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN8
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN10
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN12
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesperslotR17EnumeratedN14
)
