package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxSRSposBandwidthForEachSCS-withinCC-FR2-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr2R17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr2R17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr2R17EnumeratedBw50
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr2R17EnumeratedBw100
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr2R17EnumeratedBw200
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr2R17EnumeratedBw400
)
