package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxNumOfSemiPersistentSRSposResourcesPerSlot-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN1
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN2
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN3
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN4
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN5
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN6
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN8
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN10
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN12
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesperslotR17EnumeratedN14
)
