package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxNumOfPeriodicSRSposResources-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedN1
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedN2
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedN4
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedN8
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedN16
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedN32
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicsrsposresourcesR17EnumeratedN64
)
