package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-switchingTimeSRS-TX-OtherTX-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17SwitchingtimesrsTxOthertxR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17SwitchingtimesrsTxOthertxR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17SwitchingtimesrsTxOthertxR17EnumeratedUs100
	PossrsRrcInactiveOutsideinitialulBwpR17SwitchingtimesrsTxOthertxR17EnumeratedUs140
	PossrsRrcInactiveOutsideinitialulBwpR17SwitchingtimesrsTxOthertxR17EnumeratedUs200
	PossrsRrcInactiveOutsideinitialulBwpR17SwitchingtimesrsTxOthertxR17EnumeratedUs300
	PossrsRrcInactiveOutsideinitialulBwpR17SwitchingtimesrsTxOthertxR17EnumeratedUs500
)
