package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-differentNumerologyBetweenSRSposAndInitialBWP-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17DifferentnumerologybetweensrsposandinitialbwpR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17DifferentnumerologybetweensrsposandinitialbwpR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17DifferentnumerologybetweensrsposandinitialbwpR17EnumeratedSupported
)
