package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxNumOfPeriodicAndSemipersistentSRSposResources-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedN1
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedN2
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedN4
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedN8
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedN16
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedN32
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesR17EnumeratedN64
)
