package ies

import "rrc/utils"

// PosSchedulingInfo-r15-posSI-Periodicity-r15 ::= ENUMERATED
type PosschedulinginfoR15PossiPeriodicityR15 struct {
	Value utils.ENUMERATED
}

const (
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedNothing = iota
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedRf8
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedRf16
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedRf32
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedRf64
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedRf128
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedRf256
	PosschedulinginfoR15PossiPeriodicityR15EnumeratedRf512
)
