package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxSRSposBandwidthForEachSCS-withinCC-FR1-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw5
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw10
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw15
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw20
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw25
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw30
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw35
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw40
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw45
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw50
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw60
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw70
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw80
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw90
	PossrsRrcInactiveOutsideinitialulBwpR17MaxsrsposbandwidthforeachscsWithinccFr1R17EnumeratedBw100
)
