package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxNumOfSemiPersistentSRSposResources-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN1
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN2
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN4
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN8
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN16
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN32
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofsemipersistentsrsposresourcesR17EnumeratedN64
)
