package ies

import "rrc/utils"

// PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17-maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot-r17 ::= ENUMERATED
type PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17 struct {
	Value utils.ENUMERATED
}

const (
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedNothing = iota
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN1
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN2
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN3
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN4
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN5
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN6
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN8
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN10
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN12
	PossrsRrcInactiveOutsideinitialulBwpR17MaxnumofperiodicandsemipersistentsrsposresourcesperslotR17EnumeratedN14
)
