package ies

import "rrc/utils"

// PowerRampingParameters-preambleInitialReceivedTargetPower ::= ENUMERATED
type PowerrampingparametersPreambleinitialreceivedtargetpower struct {
	Value utils.ENUMERATED
}

const (
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedNothing = iota
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_120
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_118
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_116
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_114
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_112
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_110
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_108
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_106
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_104
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_102
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_100
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_98
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_96
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_94
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_92
	PowerrampingparametersPreambleinitialreceivedtargetpowerEnumeratedDbm_90
)
