package ies

import "rrc/utils"

// PowerPrefIndicationConfig-r11-setup-powerPrefIndicationTimer-r11 ::= ENUMERATED
type PowerprefindicationconfigR11SetupPowerprefindicationtimerR11 struct {
	Value utils.ENUMERATED
}

const (
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedNothing = iota
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS0
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS0dot5
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS1
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS2
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS5
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS10
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS20
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS30
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS60
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS90
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS120
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS300
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedS600
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedSpare3
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedSpare2
	PowerprefindicationconfigR11SetupPowerprefindicationtimerR11EnumeratedSpare1
)
