package ies

import "rrc/utils"

// PRACH-ParametersCE-r13-prach-StartingSubframe-r13 ::= ENUMERATED
type PrachParametersceR13PrachStartingsubframeR13 struct {
	Value utils.ENUMERATED
}

const (
	PrachParametersceR13PrachStartingsubframeR13EnumeratedNothing = iota
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf2
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf4
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf8
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf16
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf32
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf64
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf128
	PrachParametersceR13PrachStartingsubframeR13EnumeratedSf256
)
