package ies

import "rrc/utils"

// PRACH-ParametersCE-r13-maxNumPreambleAttemptCE-r13 ::= ENUMERATED
type PrachParametersceR13MaxnumpreambleattemptceR13 struct {
	Value utils.ENUMERATED
}

const (
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedNothing = iota
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedN3
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedN4
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedN5
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedN6
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedN7
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedN8
	PrachParametersceR13MaxnumpreambleattemptceR13EnumeratedN10
)
