package ies

import "rrc/utils"

// PropDelayDiffReportConfig-r17-threshPropDelayDiff-r17 ::= ENUMERATED
type PropdelaydiffreportconfigR17ThreshpropdelaydiffR17 struct {
	Value utils.ENUMERATED
}

const (
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedNothing = iota
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs0dot5
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs1
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs2
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs3
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs4
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs5
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs6
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs7
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs8
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs9
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedMs10
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedSpare5
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedSpare4
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedSpare3
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedSpare2
	PropdelaydiffreportconfigR17ThreshpropdelaydiffR17EnumeratedSpare1
)
