package ies

import (
	"github.com/lvdund/asn1go/aper"
	"github.com/lvdund/rrc/utils"
)

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_msDot125 aper.Enumerated = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_msDot25  aper.Enumerated = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_msDot5   aper.Enumerated = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms1      aper.Enumerated = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms2      aper.Enumerated = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms4      aper.Enumerated = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms6      aper.Enumerated = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms8      aper.Enumerated = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms12     aper.Enumerated = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms16     aper.Enumerated = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms20     aper.Enumerated = 10
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms25     aper.Enumerated = 11
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms30     aper.Enumerated = 12
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms32     aper.Enumerated = 13
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms35     aper.Enumerated = 14
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms40     aper.Enumerated = 15
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms45     aper.Enumerated = 16
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms50     aper.Enumerated = 17
)

type PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17 struct {
	Value aper.Enumerated `lb:0,ub:17,madatory`
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17) Encode(w *aper.AperWriter) error {
	var err error
	if err = w.WriteEnumerate(uint64(ie.Value), aper.Constraint{Lb: 0, Ub: 17}, false); err != nil {
		return utils.WrapError("Encode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17", err)
	}
	return nil
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17) Decode(r *aper.AperReader) error {
	var err error
	var v uint64
	if v, err = r.ReadEnumerate(aper.Constraint{Lb: 0, Ub: 17}, false); err != nil {
		return utils.WrapError("Decode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17", err)
	}
	ie.Value = aper.Enumerated(v)
	return nil
}
