// Code generated from docs/NR-RRC-Definitions.asn by codegen.
// DO NOT EDIT.

package ies

import (
	"github.com/lvdund/asn1go/per"
)

// Source: PRS-ProcessingCapabilityOutsideMGinPPWperType-r17 (line 23491).

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17Constraints = per.SequenceConstraints{
	Extensible: false,
	RootComponents: []per.ComponentInfo{
		{Name: "prsProcessingType-r17"},
		{Name: "ppw-dl-PRS-BufferType-r17"},
		{Name: "ppw-durationOfPRS-Processing-r17", Optional: true},
		{Name: "ppw-maxNumOfDL-PRS-ResProcessedPerSlot-r17"},
		{Name: "ppw-maxNumOfDL-Bandwidth-r17", Optional: true},
	},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_PrsProcessingType_r17_Type1A = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_PrsProcessingType_r17_Type1B = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_PrsProcessingType_r17_Type2  = 2
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PrsProcessingTypeR17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_PrsProcessingType_r17_Type1A, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_PrsProcessingType_r17_Type1B, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_PrsProcessingType_r17_Type2},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_Dl_PRS_BufferType_r17_Type1 = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_Dl_PRS_BufferType_r17_Type2 = 1
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDlPRSBufferTypeR17Constraints = per.EnumeratedConstraints{
	Extensible: true,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_Dl_PRS_BufferType_r17_Type1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_Dl_PRS_BufferType_r17_Type2},
}

var pRS_ProcessingCapabilityOutsideMGinPPWperType_r17PpwDurationOfPRSProcessingR17Constraints = per.ChoiceConstraints{
	Extensible: false,
	RootAlternatives: []per.AlternativeInfo{
		{Name: "ppw-durationOfPRS-Processing1-r17"},
		{Name: "ppw-durationOfPRS-Processing2-r17"},
	},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17 = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17 = 1
)

var pRS_ProcessingCapabilityOutsideMGinPPWperType_r17PpwMaxNumOfDLBandwidthR17Constraints = per.ChoiceConstraints{
	Extensible: false,
	RootAlternatives: []per.AlternativeInfo{
		{Name: "fr1-r17"},
		{Name: "fr2-r17"},
	},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17 = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17 = 1
)

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_MsDot125 = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_MsDot25  = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_MsDot5   = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms1      = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms2      = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms4      = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms6      = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms8      = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms12     = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms16     = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms20     = 10
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms25     = 11
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms30     = 12
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms32     = 13
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms35     = 14
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms40     = 15
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms45     = 16
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms50     = 17
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing1R17PpwDurationOfPRSProcessingSymbolsNR17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_MsDot125, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_MsDot25, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_MsDot5, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms2, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms6, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms8, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms12, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms16, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms20, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms25, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms30, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms32, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms35, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms40, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms45, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsN_r17_Ms50},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms1    = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms2    = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms4    = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms8    = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms16   = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms20   = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms30   = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms40   = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms80   = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms160  = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms320  = 10
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms640  = 11
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms1280 = 12
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing1R17PpwDurationOfPRSProcessingSymbolsTR17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms2, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms8, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms16, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms20, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms30, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms40, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms80, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms160, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms320, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms640, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17_Ppw_DurationOfPRS_ProcessingSymbolsT_r17_Ms1280},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_MsDot125 = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_MsDot25  = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_MsDot5   = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms1      = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms2      = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms3      = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms4      = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms5      = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms6      = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms8      = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms12     = 10
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing2R17PpwDurationOfPRSProcessingSymbolsN2R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_MsDot125, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_MsDot25, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_MsDot5, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms2, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms3, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms5, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms6, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms8, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsN2_r17_Ms12},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms4 = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms5 = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms6 = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms8 = 3
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing2R17PpwDurationOfPRSProcessingSymbolsT2R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms5, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms6, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17_Ppw_DurationOfPRS_ProcessingSymbolsT2_r17_Ms8},
}

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Constraints = per.SequenceConstraints{
	Extensible: true,
	RootComponents: []per.ComponentInfo{
		{Name: "scs15-r17", Optional: true},
		{Name: "scs30-r17", Optional: true},
		{Name: "scs60-r17", Optional: true},
		{Name: "scs120-r17", Optional: true},
	},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N1  = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N2  = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N4  = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N6  = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N8  = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N12 = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N16 = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N24 = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N32 = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N48 = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N64 = 10
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs15R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N2, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N6, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N8, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N12, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N16, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N24, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N32, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N48, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs15_r17_N64},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N1  = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N2  = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N4  = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N6  = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N8  = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N12 = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N16 = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N24 = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N32 = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N48 = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N64 = 10
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs30R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N2, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N6, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N8, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N12, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N16, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N24, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N32, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N48, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs30_r17_N64},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N1  = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N2  = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N4  = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N6  = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N8  = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N12 = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N16 = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N24 = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N32 = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N48 = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N64 = 10
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs60R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N2, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N6, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N8, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N12, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N16, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N24, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N32, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N48, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs60_r17_N64},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N1  = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N2  = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N4  = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N6  = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N8  = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N12 = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N16 = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N24 = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N32 = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N48 = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N64 = 10
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs120R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N1, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N2, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N4, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N6, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N8, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N12, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N16, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N24, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N32, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N48, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17_Scs120_r17_N64},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz5   = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz10  = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz20  = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz40  = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz50  = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz80  = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz100 = 6
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLBandwidthR17Fr1R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz5, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz10, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz20, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz40, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz50, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz80, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17_Mhz100},
}

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz50  = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz100 = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz200 = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz400 = 3
)

var pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLBandwidthR17Fr2R17Constraints = per.EnumeratedConstraints{
	Extensible: false,
	RootValues: []int64{PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz50, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz100, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz200, PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17_Mhz400},
}

type PRS_ProcessingCapabilityOutsideMGinPPWperType_r17 struct {
	PrsProcessingType_r17            int64
	Ppw_Dl_PRS_BufferType_r17        int64
	Ppw_DurationOfPRS_Processing_r17 *struct {
		Choice                            int
		Ppw_DurationOfPRS_Processing1_r17 *struct {
			Ppw_DurationOfPRS_ProcessingSymbolsN_r17 int64
			Ppw_DurationOfPRS_ProcessingSymbolsT_r17 int64
		}
		Ppw_DurationOfPRS_Processing2_r17 *struct {
			Ppw_DurationOfPRS_ProcessingSymbolsN2_r17 int64
			Ppw_DurationOfPRS_ProcessingSymbolsT2_r17 int64
		}
	}
	Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17 struct {
		Scs15_r17  *int64
		Scs30_r17  *int64
		Scs60_r17  *int64
		Scs120_r17 *int64
	}
	Ppw_MaxNumOfDL_Bandwidth_r17 *struct {
		Choice  int
		Fr1_r17 *int64
		Fr2_r17 *int64
	}
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17) Encode(e *per.Encoder) error {
	seq := e.NewSequenceEncoder(pRSProcessingCapabilityOutsideMGinPPWperTypeR17Constraints)

	// 1. Root OPTIONAL bitmap, one bit per optional/default field.
	if err := seq.EncodePreamble([]bool{ie.Ppw_DurationOfPRS_Processing_r17 != nil, ie.Ppw_MaxNumOfDL_Bandwidth_r17 != nil}); err != nil {
		return err
	}

	// 2. prsProcessingType-r17: enumerated
	{
		if err := e.EncodeEnumerated(ie.PrsProcessingType_r17, pRSProcessingCapabilityOutsideMGinPPWperTypeR17PrsProcessingTypeR17Constraints); err != nil {
			return err
		}
	}

	// 3. ppw-dl-PRS-BufferType-r17: enumerated
	{
		if err := e.EncodeEnumerated(ie.Ppw_Dl_PRS_BufferType_r17, pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDlPRSBufferTypeR17Constraints); err != nil {
			return err
		}
	}

	// 4. ppw-durationOfPRS-Processing-r17: choice
	{
		if ie.Ppw_DurationOfPRS_Processing_r17 != nil {
			choiceEnc := e.NewChoiceEncoder(pRS_ProcessingCapabilityOutsideMGinPPWperType_r17PpwDurationOfPRSProcessingR17Constraints)
			if err := choiceEnc.EncodeChoice(int64((*ie.Ppw_DurationOfPRS_Processing_r17).Choice), false, nil); err != nil {
				return err
			}
			switch (*ie.Ppw_DurationOfPRS_Processing_r17).Choice {
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17:
				c := (*(*ie.Ppw_DurationOfPRS_Processing_r17).Ppw_DurationOfPRS_Processing1_r17)
				if err := e.EncodeEnumerated(c.Ppw_DurationOfPRS_ProcessingSymbolsN_r17, pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing1R17PpwDurationOfPRSProcessingSymbolsNR17Constraints); err != nil {
					return err
				}
				if err := e.EncodeEnumerated(c.Ppw_DurationOfPRS_ProcessingSymbolsT_r17, pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing1R17PpwDurationOfPRSProcessingSymbolsTR17Constraints); err != nil {
					return err
				}
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17:
				c := (*(*ie.Ppw_DurationOfPRS_Processing_r17).Ppw_DurationOfPRS_Processing2_r17)
				if err := e.EncodeEnumerated(c.Ppw_DurationOfPRS_ProcessingSymbolsN2_r17, pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing2R17PpwDurationOfPRSProcessingSymbolsN2R17Constraints); err != nil {
					return err
				}
				if err := e.EncodeEnumerated(c.Ppw_DurationOfPRS_ProcessingSymbolsT2_r17, pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing2R17PpwDurationOfPRSProcessingSymbolsT2R17Constraints); err != nil {
					return err
				}
			default:
				return &per.ConstraintViolationError{TypeName: "choice", Value: int64((*ie.Ppw_DurationOfPRS_Processing_r17).Choice), Constraint: "index out of range"}
			}
		}
	}

	// 5. ppw-maxNumOfDL-PRS-ResProcessedPerSlot-r17: sequence
	{
		{
			c := &ie.Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17
			pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq := e.NewSequenceEncoder(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Constraints)
			if err := pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.EncodeExtensionBit(false); err != nil {
				return err
			}
			if err := pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.EncodePreamble([]bool{c.Scs15_r17 != nil, c.Scs30_r17 != nil, c.Scs60_r17 != nil, c.Scs120_r17 != nil}); err != nil {
				return err
			}
			if c.Scs15_r17 != nil {
				if err := e.EncodeEnumerated((*c.Scs15_r17), pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs15R17Constraints); err != nil {
					return err
				}
			}
			if c.Scs30_r17 != nil {
				if err := e.EncodeEnumerated((*c.Scs30_r17), pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs30R17Constraints); err != nil {
					return err
				}
			}
			if c.Scs60_r17 != nil {
				if err := e.EncodeEnumerated((*c.Scs60_r17), pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs60R17Constraints); err != nil {
					return err
				}
			}
			if c.Scs120_r17 != nil {
				if err := e.EncodeEnumerated((*c.Scs120_r17), pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs120R17Constraints); err != nil {
					return err
				}
			}
		}
	}

	// 6. ppw-maxNumOfDL-Bandwidth-r17: choice
	{
		if ie.Ppw_MaxNumOfDL_Bandwidth_r17 != nil {
			choiceEnc := e.NewChoiceEncoder(pRS_ProcessingCapabilityOutsideMGinPPWperType_r17PpwMaxNumOfDLBandwidthR17Constraints)
			if err := choiceEnc.EncodeChoice(int64((*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Choice), false, nil); err != nil {
				return err
			}
			switch (*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Choice {
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17:
				if err := e.EncodeEnumerated((*(*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Fr1_r17), pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLBandwidthR17Fr1R17Constraints); err != nil {
					return err
				}
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17:
				if err := e.EncodeEnumerated((*(*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Fr2_r17), pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLBandwidthR17Fr2R17Constraints); err != nil {
					return err
				}
			default:
				return &per.ConstraintViolationError{TypeName: "choice", Value: int64((*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Choice), Constraint: "index out of range"}
			}
		}
	}

	return nil
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17) Decode(d *per.Decoder) error {
	seq := d.NewSequenceDecoder(pRSProcessingCapabilityOutsideMGinPPWperTypeR17Constraints)

	// 1. Decode root OPTIONAL bitmap.
	if err := seq.DecodePreamble(); err != nil {
		return err
	}

	// 2. prsProcessingType-r17: enumerated
	{
		v0, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PrsProcessingTypeR17Constraints)
		if err != nil {
			return err
		}
		ie.PrsProcessingType_r17 = v0
	}

	// 3. ppw-dl-PRS-BufferType-r17: enumerated
	{
		v1, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDlPRSBufferTypeR17Constraints)
		if err != nil {
			return err
		}
		ie.Ppw_Dl_PRS_BufferType_r17 = v1
	}

	// 4. ppw-durationOfPRS-Processing-r17: choice
	{
		if seq.IsComponentPresent(2) {
			ie.Ppw_DurationOfPRS_Processing_r17 = &struct {
				Choice                            int
				Ppw_DurationOfPRS_Processing1_r17 *struct {
					Ppw_DurationOfPRS_ProcessingSymbolsN_r17 int64
					Ppw_DurationOfPRS_ProcessingSymbolsT_r17 int64
				}
				Ppw_DurationOfPRS_Processing2_r17 *struct {
					Ppw_DurationOfPRS_ProcessingSymbolsN2_r17 int64
					Ppw_DurationOfPRS_ProcessingSymbolsT2_r17 int64
				}
			}{}
			choiceDec := d.NewChoiceDecoder(pRS_ProcessingCapabilityOutsideMGinPPWperType_r17PpwDurationOfPRSProcessingR17Constraints)
			index, isExt, _, err := choiceDec.DecodeChoice()
			if err != nil {
				return err
			}
			(*ie.Ppw_DurationOfPRS_Processing_r17).Choice = int(index)
			if isExt {
				return &per.DecodeError{TypeName: "choice", Reason: "extension alternative not supported"}
			}
			switch index {
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing1_r17:
				(*ie.Ppw_DurationOfPRS_Processing_r17).Ppw_DurationOfPRS_Processing1_r17 = &struct {
					Ppw_DurationOfPRS_ProcessingSymbolsN_r17 int64
					Ppw_DurationOfPRS_ProcessingSymbolsT_r17 int64
				}{}
				c := (*(*ie.Ppw_DurationOfPRS_Processing_r17).Ppw_DurationOfPRS_Processing1_r17)
				{
					v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing1R17PpwDurationOfPRSProcessingSymbolsNR17Constraints)
					if err != nil {
						return err
					}
					c.Ppw_DurationOfPRS_ProcessingSymbolsN_r17 = v
				}
				{
					v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing1R17PpwDurationOfPRSProcessingSymbolsTR17Constraints)
					if err != nil {
						return err
					}
					c.Ppw_DurationOfPRS_ProcessingSymbolsT_r17 = v
				}
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_DurationOfPRS_Processing_r17_Ppw_DurationOfPRS_Processing2_r17:
				(*ie.Ppw_DurationOfPRS_Processing_r17).Ppw_DurationOfPRS_Processing2_r17 = &struct {
					Ppw_DurationOfPRS_ProcessingSymbolsN2_r17 int64
					Ppw_DurationOfPRS_ProcessingSymbolsT2_r17 int64
				}{}
				c := (*(*ie.Ppw_DurationOfPRS_Processing_r17).Ppw_DurationOfPRS_Processing2_r17)
				{
					v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing2R17PpwDurationOfPRSProcessingSymbolsN2R17Constraints)
					if err != nil {
						return err
					}
					c.Ppw_DurationOfPRS_ProcessingSymbolsN2_r17 = v
				}
				{
					v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwDurationOfPRSProcessingR17PpwDurationOfPRSProcessing2R17PpwDurationOfPRSProcessingSymbolsT2R17Constraints)
					if err != nil {
						return err
					}
					c.Ppw_DurationOfPRS_ProcessingSymbolsT2_r17 = v
				}
			}
		}
	}

	// 5. ppw-maxNumOfDL-PRS-ResProcessedPerSlot-r17: sequence
	{
		{
			c := &ie.Ppw_MaxNumOfDL_PRS_ResProcessedPerSlot_r17
			pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq := d.NewSequenceDecoder(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Constraints)
			if err := pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.DecodeExtensionBit(); err != nil {
				return err
			}
			if err := pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.DecodePreamble(); err != nil {
				return err
			}
			if pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.IsComponentPresent(0) {
				c.Scs15_r17 = new(int64)
				v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs15R17Constraints)
				if err != nil {
					return err
				}
				(*c.Scs15_r17) = v
			}
			if pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.IsComponentPresent(1) {
				c.Scs30_r17 = new(int64)
				v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs30R17Constraints)
				if err != nil {
					return err
				}
				(*c.Scs30_r17) = v
			}
			if pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.IsComponentPresent(2) {
				c.Scs60_r17 = new(int64)
				v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs60R17Constraints)
				if err != nil {
					return err
				}
				(*c.Scs60_r17) = v
			}
			if pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Seq.IsComponentPresent(3) {
				c.Scs120_r17 = new(int64)
				v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLPRSResProcessedPerSlotR17Scs120R17Constraints)
				if err != nil {
					return err
				}
				(*c.Scs120_r17) = v
			}
		}
	}

	// 6. ppw-maxNumOfDL-Bandwidth-r17: choice
	{
		if seq.IsComponentPresent(4) {
			ie.Ppw_MaxNumOfDL_Bandwidth_r17 = &struct {
				Choice  int
				Fr1_r17 *int64
				Fr2_r17 *int64
			}{}
			choiceDec := d.NewChoiceDecoder(pRS_ProcessingCapabilityOutsideMGinPPWperType_r17PpwMaxNumOfDLBandwidthR17Constraints)
			index, isExt, _, err := choiceDec.DecodeChoice()
			if err != nil {
				return err
			}
			(*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Choice = int(index)
			if isExt {
				return &per.DecodeError{TypeName: "choice", Reason: "extension alternative not supported"}
			}
			switch index {
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr1_r17:
				(*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Fr1_r17 = new(int64)
				v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLBandwidthR17Fr1R17Constraints)
				if err != nil {
					return err
				}
				(*(*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Fr1_r17) = v
			case PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_Ppw_MaxNumOfDL_Bandwidth_r17_Fr2_r17:
				(*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Fr2_r17 = new(int64)
				v, err := d.DecodeEnumerated(pRSProcessingCapabilityOutsideMGinPPWperTypeR17PpwMaxNumOfDLBandwidthR17Fr2R17Constraints)
				if err != nil {
					return err
				}
				(*(*ie.Ppw_MaxNumOfDL_Bandwidth_r17).Fr2_r17) = v
			}
		}
	}

	return nil
}
