package ies

import (
	"github.com/lvdund/asn1go/aper"
	"github.com/lvdund/rrc/utils"
)

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_msDot125 aper.Enumerated = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_msDot25  aper.Enumerated = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_msDot5   aper.Enumerated = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms1      aper.Enumerated = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms2      aper.Enumerated = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms3      aper.Enumerated = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms4      aper.Enumerated = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms5      aper.Enumerated = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms6      aper.Enumerated = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms8      aper.Enumerated = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17_Enum_ms12     aper.Enumerated = 10
)

type PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17 struct {
	Value aper.Enumerated `lb:0,ub:10,madatory`
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17) Encode(w *aper.AperWriter) error {
	var err error
	if err = w.WriteEnumerate(uint64(ie.Value), aper.Constraint{Lb: 0, Ub: 10}, false); err != nil {
		return utils.WrapError("Encode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17", err)
	}
	return nil
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17) Decode(r *aper.AperReader) error {
	var err error
	var v uint64
	if v, err = r.ReadEnumerate(aper.Constraint{Lb: 0, Ub: 10}, false); err != nil {
		return utils.WrapError("Decode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing2_r17_ppw_durationOfPRS_ProcessingSymbolsN2_r17", err)
	}
	ie.Value = aper.Enumerated(v)
	return nil
}
