package ies

import "rrc/utils"

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-durationOfPRS-Processing-r17-ppw-durationOfPRS-Processing1-r17-ppw-durationOfPRS-ProcessingSymbolsT-r17 ::= ENUMERATED
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17 struct {
	Value utils.ENUMERATED
}

const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs1
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs2
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs4
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs8
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs16
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs20
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs30
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs40
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs80
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs160
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs320
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs640
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17EnumeratedMs1280
)
