package ies

import "rrc/utils"

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-durationOfPRS-Processing-r17-ppw-durationOfPRS-Processing2-r17-ppw-durationOfPRS-ProcessingSymbolsN2-r17 ::= ENUMERATED
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17 struct {
	Value utils.ENUMERATED
}

const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMsdot125
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMsdot25
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMsdot5
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs1
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs2
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs3
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs4
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs5
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs6
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs8
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17EnumeratedMs12
)
