package ies

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-durationOfPRS-Processing-r17-ppw-durationOfPRS-Processing1-r17 ::= SEQUENCE
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17 struct {
	PpwDurationofprsProcessingsymbolsnR17 PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17
	PpwDurationofprsProcessingsymbolstR17 PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolstR17
}
