package ies

import "rrc/utils"

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-maxNumOfDL-PRS-ResProcessedPerSlot-r17-scs15-r17 ::= ENUMERATED
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17 struct {
	Value utils.ENUMERATED
}

const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN1
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN2
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN4
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN6
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN8
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN12
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN16
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN24
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN32
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN48
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17EnumeratedN64
)
