package ies

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-durationOfPRS-Processing-r17 ::= CHOICE
const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17ChoiceNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17ChoicePpwDurationofprsProcessing1R17
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17ChoicePpwDurationofprsProcessing2R17
)

type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17 struct {
	Choice                         uint64
	PpwDurationofprsProcessing1R17 *PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17
	PpwDurationofprsProcessing2R17 *PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17
}
