package ies

import "rrc/utils"

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-maxNumOfDL-PRS-ResProcessedPerSlot-r17-scs120-r17 ::= ENUMERATED
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17 struct {
	Value utils.ENUMERATED
}

const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN1
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN2
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN4
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN6
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN8
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN12
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN16
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN24
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN32
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN48
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17EnumeratedN64
)
