package ies

import "rrc/utils"

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-durationOfPRS-Processing-r17-ppw-durationOfPRS-Processing1-r17-ppw-durationOfPRS-ProcessingSymbolsN-r17 ::= ENUMERATED
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17 struct {
	Value utils.ENUMERATED
}

const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMsdot125
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMsdot25
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMsdot5
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs1
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs2
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs4
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs6
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs8
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs12
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs16
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs20
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs25
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs30
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs32
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs35
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs40
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs45
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing1R17PpwDurationofprsProcessingsymbolsnR17EnumeratedMs50
)
