package ies

import "rrc/utils"

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-maxNumOfDL-PRS-ResProcessedPerSlot-r17-scs60-r17 ::= ENUMERATED
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17 struct {
	Value utils.ENUMERATED
}

const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN1
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN2
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN4
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN6
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN8
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN12
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN16
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN24
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN32
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN48
	PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17EnumeratedN64
)
