package ies

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-maxNumOfDL-PRS-ResProcessedPerSlot-r17 ::= SEQUENCE
// Extensible
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17 struct {
	Scs15R17  *PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs15R17
	Scs30R17  *PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs30R17
	Scs60R17  *PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs60R17
	Scs120R17 *PrsProcessingcapabilityoutsidemginppwpertypeR17PpwMaxnumofdlPrsResprocessedperslotR17Scs120R17
}
