package ies

import "rrc/utils"

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-prsProcessingType-r17 ::= ENUMERATED
type PrsProcessingcapabilityoutsidemginppwpertypeR17PrsprocessingtypeR17 struct {
	Value utils.ENUMERATED
}

const (
	PrsProcessingcapabilityoutsidemginppwpertypeR17PrsprocessingtypeR17EnumeratedNothing = iota
	PrsProcessingcapabilityoutsidemginppwpertypeR17PrsprocessingtypeR17EnumeratedType1a
	PrsProcessingcapabilityoutsidemginppwpertypeR17PrsprocessingtypeR17EnumeratedType1b
	PrsProcessingcapabilityoutsidemginppwpertypeR17PrsprocessingtypeR17EnumeratedType2
)
