package ies

// PRS-ProcessingCapabilityOutsideMGinPPWperType-r17-ppw-durationOfPRS-Processing-r17-ppw-durationOfPRS-Processing2-r17 ::= SEQUENCE
type PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17 struct {
	PpwDurationofprsProcessingsymbolsn2R17 PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolsn2R17
	PpwDurationofprsProcessingsymbolst2R17 PrsProcessingcapabilityoutsidemginppwpertypeR17PpwDurationofprsProcessingR17PpwDurationofprsProcessing2R17PpwDurationofprsProcessingsymbolst2R17
}
