package ies

// PUCCH-ConfigDedicated-r13-pucch-Format-r13-format3-r13-twoAntennaPortActivatedPUCCH-Format3-r13 ::= CHOICE
const (
	PucchConfigdedicatedR13PucchFormatR13Format3R13TwoantennaportactivatedpucchFormat3R13ChoiceNothing = iota
	PucchConfigdedicatedR13PucchFormatR13Format3R13TwoantennaportactivatedpucchFormat3R13ChoiceRelease
	PucchConfigdedicatedR13PucchFormatR13Format3R13TwoantennaportactivatedpucchFormat3R13ChoiceSetup
)

type PucchConfigdedicatedR13PucchFormatR13Format3R13TwoantennaportactivatedpucchFormat3R13 struct {
	Choice  uint64
	Release *struct{}
	Setup   *PucchConfigdedicatedR13PucchFormatR13Format3R13TwoantennaportactivatedpucchFormat3R13Setup
}
