package ies

import "rrc/utils"

// PUCCH-ConfigCommon-additionalPRBOffset-r17 ::= ENUMERATED
type PucchConfigcommonAdditionalprboffsetR17 struct {
	Value utils.ENUMERATED
}

const (
	PucchConfigcommonAdditionalprboffsetR17EnumeratedNothing = iota
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN2
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN3
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN4
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN6
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN8
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN9
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN10
	PucchConfigcommonAdditionalprboffsetR17EnumeratedN12
)
