package ies

import "rrc/utils"

// PUCCH-ConfigDedicated-r13-pucch-NumRepetitionCE-r13-setup-modeB-pucch-NumRepetitionCE-format2-r13 ::= ENUMERATED
type PucchConfigdedicatedR13PucchNumrepetitionceR13SetupModebPucchNumrepetitionceFormat2R13 struct {
	Value utils.ENUMERATED
}

const (
	PucchConfigdedicatedR13PucchNumrepetitionceR13SetupModebPucchNumrepetitionceFormat2R13EnumeratedNothing = iota
	PucchConfigdedicatedR13PucchNumrepetitionceR13SetupModebPucchNumrepetitionceFormat2R13EnumeratedR4
	PucchConfigdedicatedR13PucchNumrepetitionceR13SetupModebPucchNumrepetitionceFormat2R13EnumeratedR8
	PucchConfigdedicatedR13PucchNumrepetitionceR13SetupModebPucchNumrepetitionceFormat2R13EnumeratedR16
	PucchConfigdedicatedR13PucchNumrepetitionceR13SetupModebPucchNumrepetitionceFormat2R13EnumeratedR32
)
