package ies

import "rrc/utils"

// PURConfigurationRequest-r16-IEs-pur-ConfigRequest-r16-pur-SetupRequest-requestedTBS-r16 ::= ENUMERATED
type PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16 struct {
	Value utils.ENUMERATED
}

const (
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedNothing = iota
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB328
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB344
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB376
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB392
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB408
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB424
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB440
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB456
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB472
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB488
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB504
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB536
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB568
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB584
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB616
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB648
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB680
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB712
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB744
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB776
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB808
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB840
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB872
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB904
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB936
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB968
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1000
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1032
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1064
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1096
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1128
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1160
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1192
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1224
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1256
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1288
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1320
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1352
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1384
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1416
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1480
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1544
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1608
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1672
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1736
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1800
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1864
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1928
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB1992
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2024
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2088
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2152
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2216
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2280
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2344
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2408
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2472
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2536
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2600
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2664
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2728
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2792
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2856
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestedtbsR16EnumeratedB2984
)
