package ies

import "rrc/utils"

// PURConfigurationRequest-r16-IEs-pur-ConfigRequest-r16-pur-SetupRequest-requestedNumOccasions-r16 ::= ENUMERATED
type PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestednumoccasionsR16 struct {
	Value utils.ENUMERATED
}

const (
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestednumoccasionsR16EnumeratedNothing = iota
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestednumoccasionsR16EnumeratedOne
	PurconfigurationrequestR16IesPurConfigrequestR16PurSetuprequestRequestednumoccasionsR16EnumeratedInfinite
)
