package ies

import "rrc/utils"

// PUR-MPDCCH-Config-r16-mpdcch-PRB-PairsConfig-r16-numberPRB-Pairs-r16 ::= ENUMERATED
type PurMpdcchConfigR16MpdcchPrbPairsconfigR16NumberprbPairsR16 struct {
	Value utils.ENUMERATED
}

const (
	PurMpdcchConfigR16MpdcchPrbPairsconfigR16NumberprbPairsR16EnumeratedNothing = iota
	PurMpdcchConfigR16MpdcchPrbPairsconfigR16NumberprbPairsR16EnumeratedN2
	PurMpdcchConfigR16MpdcchPrbPairsconfigR16NumberprbPairsR16EnumeratedN4
	PurMpdcchConfigR16MpdcchPrbPairsconfigR16NumberprbPairsR16EnumeratedN6
	PurMpdcchConfigR16MpdcchPrbPairsconfigR16NumberprbPairsR16EnumeratedSpare1
)
