package ies

import "rrc/utils"

// PUSCH-Allocation-r16-numberOfRepetitionsExt-r17 ::= ENUMERATED
type PuschAllocationR16NumberofrepetitionsextR17 struct {
	Value utils.ENUMERATED
}

const (
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedNothing = iota
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN1
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN2
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN3
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN4
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN7
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN8
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN12
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN16
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN20
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN24
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN28
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedN32
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedSpare4
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedSpare3
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedSpare2
	PuschAllocationR16NumberofrepetitionsextR17EnumeratedSpare1
)
