package ies

import "rrc/utils"

// PUSCH-Allocation-r16-numberOfSlotsTBoMS-r17 ::= ENUMERATED
type PuschAllocationR16NumberofslotstbomsR17 struct {
	Value utils.ENUMERATED
}

const (
	PuschAllocationR16NumberofslotstbomsR17EnumeratedNothing = iota
	PuschAllocationR16NumberofslotstbomsR17EnumeratedN1
	PuschAllocationR16NumberofslotstbomsR17EnumeratedN2
	PuschAllocationR16NumberofslotstbomsR17EnumeratedN4
	PuschAllocationR16NumberofslotstbomsR17EnumeratedN8
	PuschAllocationR16NumberofslotstbomsR17EnumeratedSpare4
	PuschAllocationR16NumberofslotstbomsR17EnumeratedSpare3
	PuschAllocationR16NumberofslotstbomsR17EnumeratedSpare2
	PuschAllocationR16NumberofslotstbomsR17EnumeratedSpare1
)
