package ies

import "rrc/utils"

// PUSCH-Config-resourceAllocationType1GranularityDCI-0-2-r16 ::= ENUMERATED
type PuschConfigResourceallocationtype1granularitydci02R16 struct {
	Value utils.ENUMERATED
}

const (
	PuschConfigResourceallocationtype1granularitydci02R16EnumeratedNothing = iota
	PuschConfigResourceallocationtype1granularitydci02R16EnumeratedN2
	PuschConfigResourceallocationtype1granularitydci02R16EnumeratedN4
	PuschConfigResourceallocationtype1granularitydci02R16EnumeratedN8
	PuschConfigResourceallocationtype1granularitydci02R16EnumeratedN16
)
