package ies

import "rrc/utils"

// PUSCH-Allocation-r16-numberOfRepetitions-r16 ::= ENUMERATED
type PuschAllocationR16NumberofrepetitionsR16 struct {
	Value utils.ENUMERATED
}

const (
	PuschAllocationR16NumberofrepetitionsR16EnumeratedNothing = iota
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN1
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN2
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN3
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN4
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN7
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN8
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN12
	PuschAllocationR16NumberofrepetitionsR16EnumeratedN16
)
