package ies

import "rrc/utils"

// RACH-ConfigCommonTwoStepRA-r16-msgA-RestrictedSetConfig-r16 ::= ENUMERATED
type RachConfigcommontwostepraR16MsgaRestrictedsetconfigR16 struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommontwostepraR16MsgaRestrictedsetconfigR16EnumeratedNothing = iota
	RachConfigcommontwostepraR16MsgaRestrictedsetconfigR16EnumeratedUnrestrictedset
	RachConfigcommontwostepraR16MsgaRestrictedsetconfigR16EnumeratedRestrictedsettypea
	RachConfigcommontwostepraR16MsgaRestrictedsetconfigR16EnumeratedRestrictedsettypeb
)
