package ies

import "rrc/utils"

// RACH-ConfigCommonTwoStepRA-r16-ra-ContentionResolutionTimer-r16 ::= ENUMERATED
type RachConfigcommontwostepraR16RaContentionresolutiontimerR16 struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedNothing = iota
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf8
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf16
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf24
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf32
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf40
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf48
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf56
	RachConfigcommontwostepraR16RaContentionresolutiontimerR16EnumeratedSf64
)
