package ies

import "rrc/utils"

// RACH-ConfigCommon-preambleInfo-numberOfRA-Preambles ::= ENUMERATED
type RachConfigcommonPreambleinfoNumberofraPreambles struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedNothing = iota
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN4
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN8
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN12
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN16
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN20
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN24
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN28
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN32
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN36
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN40
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN44
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN48
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN52
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN56
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN60
	RachConfigcommonPreambleinfoNumberofraPreamblesEnumeratedN64
)
