package ies

import "rrc/utils"

// RACH-ConfigGeneric-preambleTransMax ::= ENUMERATED
type RachConfiggenericPreambletransmax struct {
	Value utils.ENUMERATED
}

const (
	RachConfiggenericPreambletransmaxEnumeratedNothing = iota
	RachConfiggenericPreambletransmaxEnumeratedN3
	RachConfiggenericPreambletransmaxEnumeratedN4
	RachConfiggenericPreambletransmaxEnumeratedN5
	RachConfiggenericPreambletransmaxEnumeratedN6
	RachConfiggenericPreambletransmaxEnumeratedN7
	RachConfiggenericPreambletransmaxEnumeratedN8
	RachConfiggenericPreambletransmaxEnumeratedN10
	RachConfiggenericPreambletransmaxEnumeratedN20
	RachConfiggenericPreambletransmaxEnumeratedN50
	RachConfiggenericPreambletransmaxEnumeratedN100
	RachConfiggenericPreambletransmaxEnumeratedN200
)
