package ies

import "rrc/utils"

// RACH-ConfigCommon-ra-SupervisionInfo-mac-ContentionResolutionTimer ::= ENUMERATED
type RachConfigcommonRaSupervisioninfoMacContentionresolutiontimer struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedNothing = iota
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf8
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf16
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf24
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf32
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf40
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf48
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf56
	RachConfigcommonRaSupervisioninfoMacContentionresolutiontimerEnumeratedSf64
)
