package ies

import "rrc/utils"

// RACH-CE-LevelInfo-r13-mac-ContentionResolutionTimer-r13 ::= ENUMERATED
type RachCeLevelinfoR13MacContentionresolutiontimerR13 struct {
	Value utils.ENUMERATED
}

const (
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedNothing = iota
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf80
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf100
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf120
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf160
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf200
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf240
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf480
	RachCeLevelinfoR13MacContentionresolutiontimerR13EnumeratedSf960
)
