package ies

import "rrc/utils"

// RACH-ConfigCommonTwoStepRA-r16-msgA-TransMax-r16 ::= ENUMERATED
type RachConfigcommontwostepraR16MsgaTransmaxR16 struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedNothing = iota
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN1
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN2
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN4
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN6
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN8
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN10
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN20
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN50
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN100
	RachConfigcommontwostepraR16MsgaTransmaxR16EnumeratedN200
)
