package ies

import "rrc/utils"

// RACH-ConfigCommon-preambleInfo-preamblesGroupAConfig-sizeOfRA-PreamblesGroupA ::= ENUMERATED
type RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupa struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedNothing = iota
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN4
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN8
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN12
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN16
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN20
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN24
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN28
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN32
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN36
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN40
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN44
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN48
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN52
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN56
	RachConfigcommonPreambleinfoPreamblesgroupaconfigSizeofraPreamblesgroupaEnumeratedN60
)
