package ies

import "rrc/utils"

// RACH-ConfigCommon-groupBconfigured-messagePowerOffsetGroupB ::= ENUMERATED
type RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupb struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedNothing = iota
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedMinusinfinity
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedDb0
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedDb5
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedDb8
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedDb10
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedDb12
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedDb15
	RachConfigcommonGroupbconfiguredMessagepoweroffsetgroupbEnumeratedDb18
)
