package ies

import "rrc/utils"

// RACH-ConfigCommon-groupBconfigured-ra-Msg3SizeGroupA ::= ENUMERATED
type RachConfigcommonGroupbconfiguredRaMsg3sizegroupa struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedNothing = iota
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB56
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB144
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB208
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB256
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB282
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB480
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB640
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB800
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB1000
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedB72
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedSpare6
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedSpare5
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedSpare4
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedSpare3
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedSpare2
	RachConfigcommonGroupbconfiguredRaMsg3sizegroupaEnumeratedSpare1
)
