package ies

import "rrc/utils"

// RACH-ConfigCommon-preambleInfo-preamblesGroupAConfig-messagePowerOffsetGroupB ::= ENUMERATED
type RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupb struct {
	Value utils.ENUMERATED
}

const (
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedNothing = iota
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedMinusinfinity
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedDb0
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedDb5
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedDb8
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedDb10
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedDb12
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedDb15
	RachConfigcommonPreambleinfoPreamblesgroupaconfigMessagepoweroffsetgroupbEnumeratedDb18
)
