package ies

import "rrc/utils"

// RACH-ConfigGenericTwoStepRA-r16-preambleTransMax-r16 ::= ENUMERATED
type RachConfiggenerictwostepraR16PreambletransmaxR16 struct {
	Value utils.ENUMERATED
}

const (
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedNothing = iota
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN3
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN4
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN5
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN6
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN7
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN8
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN10
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN20
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN50
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN100
	RachConfiggenerictwostepraR16PreambletransmaxR16EnumeratedN200
)
