package ies

import "rrc/utils"

// RACH-CE-LevelInfo-r13-ra-ResponseWindowSize-r13 ::= ENUMERATED
type RachCeLevelinfoR13RaResponsewindowsizeR13 struct {
	Value utils.ENUMERATED
}

const (
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedNothing = iota
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf20
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf50
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf80
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf120
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf180
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf240
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf320
	RachCeLevelinfoR13RaResponsewindowsizeR13EnumeratedSf400
)
