package ies

import "rrc/utils"

// RACH-ConfigGenericTwoStepRA-r16-msgB-ResponseWindow-r16 ::= ENUMERATED
type RachConfiggenerictwostepraR16MsgbResponsewindowR16 struct {
	Value utils.ENUMERATED
}

const (
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedNothing = iota
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl1
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl2
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl4
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl8
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl10
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl20
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl40
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl80
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl160
	RachConfiggenerictwostepraR16MsgbResponsewindowR16EnumeratedSl320
)
