package ies

import "rrc/utils"

// RadioResourceConfigCommonSCell-r10-ul-Configuration-r10-ul-FreqInfo-r10-ul-Bandwidth-r10 ::= ENUMERATED
type RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10 struct {
	Value utils.ENUMERATED
}

const (
	RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10EnumeratedNothing = iota
	RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10EnumeratedN6
	RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10EnumeratedN15
	RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10EnumeratedN25
	RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10EnumeratedN50
	RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10EnumeratedN75
	RadioresourceconfigcommonscellR10UlConfigurationR10UlFreqinfoR10UlBandwidthR10EnumeratedN100
)
