package ies

import "rrc/utils"

// RA-InformationCommon-r16-msgA-TransMax-r17 ::= ENUMERATED
type RaInformationcommonR16MsgaTransmaxR17 struct {
	Value utils.ENUMERATED
}

const (
	RaInformationcommonR16MsgaTransmaxR17EnumeratedNothing = iota
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN1
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN2
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN4
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN6
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN8
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN10
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN20
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN50
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN100
	RaInformationcommonR16MsgaTransmaxR17EnumeratedN200
)
