package ies

import "rrc/utils"

// RA-InformationCommon-r16-msg1-SCS-From-prach-ConfigurationIndex-r16 ::= ENUMERATED
type RaInformationcommonR16Msg1ScsFromPrachConfigurationindexR16 struct {
	Value utils.ENUMERATED
}

const (
	RaInformationcommonR16Msg1ScsFromPrachConfigurationindexR16EnumeratedNothing = iota
	RaInformationcommonR16Msg1ScsFromPrachConfigurationindexR16EnumeratedKhz1dot25
	RaInformationcommonR16Msg1ScsFromPrachConfigurationindexR16EnumeratedKhz5
	RaInformationcommonR16Msg1ScsFromPrachConfigurationindexR16EnumeratedSpare2
	RaInformationcommonR16Msg1ScsFromPrachConfigurationindexR16EnumeratedSpare1
)
