package ies

import "rrc/utils"

// RAN-VisibleParameters-r17-ran-VisiblePeriodicity-r17 ::= ENUMERATED
type RanVisibleparametersR17RanVisibleperiodicityR17 struct {
	Value utils.ENUMERATED
}

const (
	RanVisibleparametersR17RanVisibleperiodicityR17EnumeratedNothing = iota
	RanVisibleparametersR17RanVisibleperiodicityR17EnumeratedMs120
	RanVisibleparametersR17RanVisibleperiodicityR17EnumeratedMs240
	RanVisibleparametersR17RanVisibleperiodicityR17EnumeratedMs480
	RanVisibleparametersR17RanVisibleperiodicityR17EnumeratedMs640
	RanVisibleparametersR17RanVisibleperiodicityR17EnumeratedMs1024
)
