package ies

import "rrc/utils"

// RedCap-ConfigCommonSIB-r17-cellBarredRedCap-r17-cellBarredRedCap2Rx-r17 ::= ENUMERATED
type RedcapConfigcommonsibR17CellbarredredcapR17Cellbarredredcap2rxR17 struct {
	Value utils.ENUMERATED
}

const (
	RedcapConfigcommonsibR17CellbarredredcapR17Cellbarredredcap2rxR17EnumeratedNothing = iota
	RedcapConfigcommonsibR17CellbarredredcapR17Cellbarredredcap2rxR17EnumeratedBarred
	RedcapConfigcommonsibR17CellbarredredcapR17Cellbarredredcap2rxR17EnumeratedNotbarred
)
