package ies

import "rrc/utils"

// RedirectedCarrierInfo-NB-v1430-redirectedCarrierOffsetDedicated-r14 ::= ENUMERATED
type RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14 struct {
	Value utils.ENUMERATED
}

const (
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedNothing = iota
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb1
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb2
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb3
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb4
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb5
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb6
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb8
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb10
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb12
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb14
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb16
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb18
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb20
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb22
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb24
	RedirectedcarrierinfoNbV1430RedirectedcarrieroffsetdedicatedR14EnumeratedDb26
)
