package ies

import "rrc/utils"

// ReducedAggregatedBandwidth ::= ENUMERATED
type Reducedaggregatedbandwidth struct {
	Value utils.ENUMERATED
}

const (
	ReducedaggregatedbandwidthEnumeratedNothing = iota
	ReducedaggregatedbandwidthEnumeratedMhz0
	ReducedaggregatedbandwidthEnumeratedMhz10
	ReducedaggregatedbandwidthEnumeratedMhz20
	ReducedaggregatedbandwidthEnumeratedMhz30
	ReducedaggregatedbandwidthEnumeratedMhz40
	ReducedaggregatedbandwidthEnumeratedMhz50
	ReducedaggregatedbandwidthEnumeratedMhz60
	ReducedaggregatedbandwidthEnumeratedMhz80
	ReducedaggregatedbandwidthEnumeratedMhz100
	ReducedaggregatedbandwidthEnumeratedMhz200
	ReducedaggregatedbandwidthEnumeratedMhz300
	ReducedaggregatedbandwidthEnumeratedMhz400
)
