package ies

import "rrc/utils"

// ReleasePreferenceConfig-r16-releasePreferenceProhibitTimer-r16 ::= ENUMERATED
type ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16 struct {
	Value utils.ENUMERATED
}

const (
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedNothing = iota
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS0
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS0dot5
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS1
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS2
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS3
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS4
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS5
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS6
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS7
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS8
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS9
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS10
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS20
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedS30
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedInfinity
	ReleasepreferenceconfigR16ReleasepreferenceprohibittimerR16EnumeratedSpare1
)
