package ies

import "rrc/utils"

// RepFactorAndTimeGap-r17-timeGap-r17 ::= ENUMERATED
type RepfactorandtimegapR17TimegapR17 struct {
	Value utils.ENUMERATED
}

const (
	RepfactorandtimegapR17TimegapR17EnumeratedNothing = iota
	RepfactorandtimegapR17TimegapR17EnumeratedS1
	RepfactorandtimegapR17TimegapR17EnumeratedS2
	RepfactorandtimegapR17TimegapR17EnumeratedS4
	RepfactorandtimegapR17TimegapR17EnumeratedS8
	RepfactorandtimegapR17TimegapR17EnumeratedS16
	RepfactorandtimegapR17TimegapR17EnumeratedS32
	RepfactorandtimegapR17TimegapR17EnumeratedSpare2
	RepfactorandtimegapR17TimegapR17EnumeratedSpare1
)
