package ies

// ReportConfigEUTRA-triggerType-event-eventId ::= CHOICE
// Extensible
const (
	ReportconfigeutraTriggertypeEventEventidChoiceNothing = iota
	ReportconfigeutraTriggertypeEventEventidChoiceEventa1
	ReportconfigeutraTriggertypeEventEventidChoiceEventa2
	ReportconfigeutraTriggertypeEventEventidChoiceEventa3
	ReportconfigeutraTriggertypeEventEventidChoiceEventa4
	ReportconfigeutraTriggertypeEventEventidChoiceEventa5
	ReportconfigeutraTriggertypeEventEventidChoiceEventa6R10
	ReportconfigeutraTriggertypeEventEventidChoiceEventc1R12
	ReportconfigeutraTriggertypeEventEventidChoiceEventc2R12
	ReportconfigeutraTriggertypeEventEventidChoiceEventv1R14
	ReportconfigeutraTriggertypeEventEventidChoiceEventv2R14
	ReportconfigeutraTriggertypeEventEventidChoiceEventh1R15
	ReportconfigeutraTriggertypeEventEventidChoiceEventh2R15
)

type ReportconfigeutraTriggertypeEventEventid struct {
	Choice     uint64
	Eventa1    *ReportconfigeutraTriggertypeEventEventidEventa1
	Eventa2    *ReportconfigeutraTriggertypeEventEventidEventa2
	Eventa3    *ReportconfigeutraTriggertypeEventEventidEventa3
	Eventa4    *ReportconfigeutraTriggertypeEventEventidEventa4
	Eventa5    *ReportconfigeutraTriggertypeEventEventidEventa5
	Eventa6R10 *ReportconfigeutraTriggertypeEventEventidEventa6R10
	Eventc1R12 *ReportconfigeutraTriggertypeEventEventidEventc1R12
	Eventc2R12 *ReportconfigeutraTriggertypeEventEventidEventc2R12
	Eventv1R14 *ReportconfigeutraTriggertypeEventEventidEventv1R14
	Eventv2R14 *ReportconfigeutraTriggertypeEventEventidEventv2R14
	Eventh1R15 *ReportconfigeutraTriggertypeEventEventidEventh1R15
	Eventh2R15 *ReportconfigeutraTriggertypeEventEventidEventh2R15
}
