package ies

// ReportConfigInterRAT-triggerType-event-eventId ::= CHOICE
// Extensible
const (
	ReportconfiginterratTriggertypeEventEventidChoiceNothing = iota
	ReportconfiginterratTriggertypeEventEventidChoiceEventb1
	ReportconfiginterratTriggertypeEventEventidChoiceEventb2
	ReportconfiginterratTriggertypeEventEventidChoiceEventw1R13
	ReportconfiginterratTriggertypeEventEventidChoiceEventw2R13
	ReportconfiginterratTriggertypeEventEventidChoiceEventw3R13
	ReportconfiginterratTriggertypeEventEventidChoiceEventb1NrR15
	ReportconfiginterratTriggertypeEventEventidChoiceEventb2NrR15
)

type ReportconfiginterratTriggertypeEventEventid struct {
	Choice       uint64
	Eventb1      *ReportconfiginterratTriggertypeEventEventidEventb1
	Eventb2      *ReportconfiginterratTriggertypeEventEventidEventb2
	Eventw1R13   *ReportconfiginterratTriggertypeEventEventidEventw1R13
	Eventw2R13   *ReportconfiginterratTriggertypeEventEventidEventw2R13
	Eventw3R13   *ReportconfiginterratTriggertypeEventEventidEventw3R13
	Eventb1NrR15 *ReportconfiginterratTriggertypeEventEventidEventb1NrR15
	Eventb2NrR15 *ReportconfiginterratTriggertypeEventEventidEventb2NrR15
}
