package ies

import "rrc/utils"

// ResourceReservationConfig-NB-r16-periodicity-r16 ::= ENUMERATED
type ResourcereservationconfigNbR16PeriodicityR16 struct {
	Value utils.ENUMERATED
}

const (
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedNothing = iota
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedMs10
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedMs20
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedMs40
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedMs80
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedMs160
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedSpare3
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedSpare2
	ResourcereservationconfigNbR16PeriodicityR16EnumeratedSpare1
)
