package ies

import "rrc/utils"

// RLM-RelaxationReportingConfig-r17-rlm-RelaxtionReportingProhibitTimer ::= ENUMERATED
type RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimer struct {
	Value utils.ENUMERATED
}

const (
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedNothing = iota
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS0
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS0dot5
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS1
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS2
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS5
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS10
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS20
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS30
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS60
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS90
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS120
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS300
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedS600
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedInfinity
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedSpare2
	RlmRelaxationreportingconfigR17RlmRelaxtionreportingprohibittimerEnumeratedSpare1
)
