package ies

import "rrc/utils"

// RN-SubframeConfig-r10-rpdcch-Config-r10-resourceAllocationType-r10 ::= ENUMERATED
type RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10 struct {
	Value utils.ENUMERATED
}

const (
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedNothing = iota
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedType0
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedType1
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedType2localized
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedType2distributed
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedSpare4
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedSpare3
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedSpare2
	RnSubframeconfigR10RpdcchConfigR10ResourceallocationtypeR10EnumeratedSpare1
)
