package ies

import "rrc/utils"

// RRCConnectionRequest-5GC-NB-r16-IEs-establishmentCause-r16 ::= ENUMERATED
type Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16 struct {
	Value utils.ENUMERATED
}

const (
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedNothing = iota
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedMt_Access
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedMo_Signalling
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedMo_Data
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedMo_Exceptiondata
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedSpare4
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedSpare3
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedSpare2
	Rrcconnectionrequest5gcNbR16IesEstablishmentcauseR16EnumeratedSpare1
)
