package ies

import "rrc/utils"

// RRCEarlyDataRequest-5GC-NB-r16-IEs-establishmentCause-r16 ::= ENUMERATED
type Rrcearlydatarequest5gcNbR16IesEstablishmentcauseR16 struct {
	Value utils.ENUMERATED
}

const (
	Rrcearlydatarequest5gcNbR16IesEstablishmentcauseR16EnumeratedNothing = iota
	Rrcearlydatarequest5gcNbR16IesEstablishmentcauseR16EnumeratedMo_Data
	Rrcearlydatarequest5gcNbR16IesEstablishmentcauseR16EnumeratedMo_Exceptiondata
	Rrcearlydatarequest5gcNbR16IesEstablishmentcauseR16EnumeratedMt_Access
	Rrcearlydatarequest5gcNbR16IesEstablishmentcauseR16EnumeratedSpare1
)
