package ies

// RRCSystemInfoRequest-criticalExtensions-criticalExtensionsFuture-r16-criticalExtensionsFuture ::= SEQUENCE
type RrcsysteminforequestCriticalextensionsCriticalextensionsfutureR16Criticalextensionsfuture struct{}
