package ies

import "rrc/utils"

// RRM-Config-NB-ue-InactiveTime ::= ENUMERATED
type RrmConfigNbUeInactivetime struct {
	Value utils.ENUMERATED
}

const (
	RrmConfigNbUeInactivetimeEnumeratedNothing = iota
	RrmConfigNbUeInactivetimeEnumeratedS1
	RrmConfigNbUeInactivetimeEnumeratedS2
	RrmConfigNbUeInactivetimeEnumeratedS3
	RrmConfigNbUeInactivetimeEnumeratedS5
	RrmConfigNbUeInactivetimeEnumeratedS7
	RrmConfigNbUeInactivetimeEnumeratedS10
	RrmConfigNbUeInactivetimeEnumeratedS15
	RrmConfigNbUeInactivetimeEnumeratedS20
	RrmConfigNbUeInactivetimeEnumeratedS25
	RrmConfigNbUeInactivetimeEnumeratedS30
	RrmConfigNbUeInactivetimeEnumeratedS40
	RrmConfigNbUeInactivetimeEnumeratedS50
	RrmConfigNbUeInactivetimeEnumeratedMin1
	RrmConfigNbUeInactivetimeEnumeratedMin1s20
	RrmConfigNbUeInactivetimeEnumeratedMin1s40
	RrmConfigNbUeInactivetimeEnumeratedMin2
	RrmConfigNbUeInactivetimeEnumeratedMin2s30
	RrmConfigNbUeInactivetimeEnumeratedMin3
	RrmConfigNbUeInactivetimeEnumeratedMin3s30
	RrmConfigNbUeInactivetimeEnumeratedMin4
	RrmConfigNbUeInactivetimeEnumeratedMin5
	RrmConfigNbUeInactivetimeEnumeratedMin6
	RrmConfigNbUeInactivetimeEnumeratedMin7
	RrmConfigNbUeInactivetimeEnumeratedMin8
	RrmConfigNbUeInactivetimeEnumeratedMin9
	RrmConfigNbUeInactivetimeEnumeratedMin10
	RrmConfigNbUeInactivetimeEnumeratedMin12
	RrmConfigNbUeInactivetimeEnumeratedMin14
	RrmConfigNbUeInactivetimeEnumeratedMin17
	RrmConfigNbUeInactivetimeEnumeratedMin20
	RrmConfigNbUeInactivetimeEnumeratedMin24
	RrmConfigNbUeInactivetimeEnumeratedMin28
	RrmConfigNbUeInactivetimeEnumeratedMin33
	RrmConfigNbUeInactivetimeEnumeratedMin38
	RrmConfigNbUeInactivetimeEnumeratedMin44
	RrmConfigNbUeInactivetimeEnumeratedMin50
	RrmConfigNbUeInactivetimeEnumeratedHr1
	RrmConfigNbUeInactivetimeEnumeratedHr1min30
	RrmConfigNbUeInactivetimeEnumeratedHr2
	RrmConfigNbUeInactivetimeEnumeratedHr2min30
	RrmConfigNbUeInactivetimeEnumeratedHr3
	RrmConfigNbUeInactivetimeEnumeratedHr3min30
	RrmConfigNbUeInactivetimeEnumeratedHr4
	RrmConfigNbUeInactivetimeEnumeratedHr5
	RrmConfigNbUeInactivetimeEnumeratedHr6
	RrmConfigNbUeInactivetimeEnumeratedHr8
	RrmConfigNbUeInactivetimeEnumeratedHr10
	RrmConfigNbUeInactivetimeEnumeratedHr13
	RrmConfigNbUeInactivetimeEnumeratedHr16
	RrmConfigNbUeInactivetimeEnumeratedHr20
	RrmConfigNbUeInactivetimeEnumeratedDay1
	RrmConfigNbUeInactivetimeEnumeratedDay1hr12
	RrmConfigNbUeInactivetimeEnumeratedDay2
	RrmConfigNbUeInactivetimeEnumeratedDay2hr12
	RrmConfigNbUeInactivetimeEnumeratedDay3
	RrmConfigNbUeInactivetimeEnumeratedDay4
	RrmConfigNbUeInactivetimeEnumeratedDay5
	RrmConfigNbUeInactivetimeEnumeratedDay7
	RrmConfigNbUeInactivetimeEnumeratedDay10
	RrmConfigNbUeInactivetimeEnumeratedDay14
	RrmConfigNbUeInactivetimeEnumeratedDay19
	RrmConfigNbUeInactivetimeEnumeratedDay24
	RrmConfigNbUeInactivetimeEnumeratedDay30
	RrmConfigNbUeInactivetimeEnumeratedDaymorethan30
)
