package ies

import "rrc/utils"

// RRM-Config-ue-InactiveTime ::= ENUMERATED
type RrmConfigUeInactivetime struct {
	Value utils.ENUMERATED
}

const (
	RrmConfigUeInactivetimeEnumeratedNothing = iota
	RrmConfigUeInactivetimeEnumeratedS1
	RrmConfigUeInactivetimeEnumeratedS2
	RrmConfigUeInactivetimeEnumeratedS3
	RrmConfigUeInactivetimeEnumeratedS5
	RrmConfigUeInactivetimeEnumeratedS7
	RrmConfigUeInactivetimeEnumeratedS10
	RrmConfigUeInactivetimeEnumeratedS15
	RrmConfigUeInactivetimeEnumeratedS20
	RrmConfigUeInactivetimeEnumeratedS25
	RrmConfigUeInactivetimeEnumeratedS30
	RrmConfigUeInactivetimeEnumeratedS40
	RrmConfigUeInactivetimeEnumeratedS50
	RrmConfigUeInactivetimeEnumeratedMin1
	RrmConfigUeInactivetimeEnumeratedMin1s20c
	RrmConfigUeInactivetimeEnumeratedMin1s40
	RrmConfigUeInactivetimeEnumeratedMin2
	RrmConfigUeInactivetimeEnumeratedMin2s30
	RrmConfigUeInactivetimeEnumeratedMin3
	RrmConfigUeInactivetimeEnumeratedMin3s30
	RrmConfigUeInactivetimeEnumeratedMin4
	RrmConfigUeInactivetimeEnumeratedMin5
	RrmConfigUeInactivetimeEnumeratedMin6
	RrmConfigUeInactivetimeEnumeratedMin7
	RrmConfigUeInactivetimeEnumeratedMin8
	RrmConfigUeInactivetimeEnumeratedMin9
	RrmConfigUeInactivetimeEnumeratedMin10
	RrmConfigUeInactivetimeEnumeratedMin12
	RrmConfigUeInactivetimeEnumeratedMin14
	RrmConfigUeInactivetimeEnumeratedMin17
	RrmConfigUeInactivetimeEnumeratedMin20
	RrmConfigUeInactivetimeEnumeratedMin24
	RrmConfigUeInactivetimeEnumeratedMin28
	RrmConfigUeInactivetimeEnumeratedMin33
	RrmConfigUeInactivetimeEnumeratedMin38
	RrmConfigUeInactivetimeEnumeratedMin44
	RrmConfigUeInactivetimeEnumeratedMin50
	RrmConfigUeInactivetimeEnumeratedHr1
	RrmConfigUeInactivetimeEnumeratedHr1min30
	RrmConfigUeInactivetimeEnumeratedHr2
	RrmConfigUeInactivetimeEnumeratedHr2min30
	RrmConfigUeInactivetimeEnumeratedHr3
	RrmConfigUeInactivetimeEnumeratedHr3min30
	RrmConfigUeInactivetimeEnumeratedHr4
	RrmConfigUeInactivetimeEnumeratedHr5
	RrmConfigUeInactivetimeEnumeratedHr6
	RrmConfigUeInactivetimeEnumeratedHr8
	RrmConfigUeInactivetimeEnumeratedHr10
	RrmConfigUeInactivetimeEnumeratedHr13
	RrmConfigUeInactivetimeEnumeratedHr16
	RrmConfigUeInactivetimeEnumeratedHr20
	RrmConfigUeInactivetimeEnumeratedDay1
	RrmConfigUeInactivetimeEnumeratedDay1hr12
	RrmConfigUeInactivetimeEnumeratedDay2
	RrmConfigUeInactivetimeEnumeratedDay2hr12
	RrmConfigUeInactivetimeEnumeratedDay3
	RrmConfigUeInactivetimeEnumeratedDay4
	RrmConfigUeInactivetimeEnumeratedDay5
	RrmConfigUeInactivetimeEnumeratedDay7
	RrmConfigUeInactivetimeEnumeratedDay10
	RrmConfigUeInactivetimeEnumeratedDay14
	RrmConfigUeInactivetimeEnumeratedDay19
	RrmConfigUeInactivetimeEnumeratedDay24
	RrmConfigUeInactivetimeEnumeratedDay30
	RrmConfigUeInactivetimeEnumeratedDaymorethan30
)
