package ies

import "rrc/utils"

// RRM-MeasRelaxationReportingConfig-r17-s-SearchDeltaP-Stationary-r17 ::= ENUMERATED
type RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17 struct {
	Value utils.ENUMERATED
}

const (
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedNothing = iota
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedDb2
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedDb3
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedDb6
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedDb9
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedDb12
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedDb15
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedSpare2
	RrmMeasrelaxationreportingconfigR17SSearchdeltapStationaryR17EnumeratedSpare1
)
