package ies

import "rrc/utils"

// RRM-MeasRelaxationReportingConfig-r17-t-SearchDeltaP-Stationary-r17 ::= ENUMERATED
type RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17 struct {
	Value utils.ENUMERATED
}

const (
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedNothing = iota
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS5
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS10
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS20
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS30
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS60
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS120
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS180
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS240
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedS300
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedSpare7
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedSpare6
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedSpare5
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedSpare4
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedSpare3
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedSpare2
	RrmMeasrelaxationreportingconfigR17TSearchdeltapStationaryR17EnumeratedSpare1
)
