package ies

import "rrc/utils"

// RSRP-ChangeThreshold-r17 ::= ENUMERATED
type RsrpChangethresholdR17 struct {
	Value utils.ENUMERATED
}

const (
	RsrpChangethresholdR17EnumeratedNothing = iota
	RsrpChangethresholdR17EnumeratedDb4
	RsrpChangethresholdR17EnumeratedDb6
	RsrpChangethresholdR17EnumeratedDb8
	RsrpChangethresholdR17EnumeratedDb10
	RsrpChangethresholdR17EnumeratedDb14
	RsrpChangethresholdR17EnumeratedDb18
	RsrpChangethresholdR17EnumeratedDb22
	RsrpChangethresholdR17EnumeratedDb26
	RsrpChangethresholdR17EnumeratedDb30
	RsrpChangethresholdR17EnumeratedDb34
	RsrpChangethresholdR17EnumeratedSpare6
	RsrpChangethresholdR17EnumeratedSpare5
	RsrpChangethresholdR17EnumeratedSpare4
	RsrpChangethresholdR17EnumeratedSpare3
	RsrpChangethresholdR17EnumeratedSpare2
	RsrpChangethresholdR17EnumeratedSpare1
)
