package ies

import "rrc/utils"

// RSRP-ChangeThresh-r16 ::= ENUMERATED
type RsrpChangethreshR16 struct {
	Value utils.ENUMERATED
}

const (
	RsrpChangethreshR16EnumeratedNothing = iota
	RsrpChangethreshR16EnumeratedDb4
	RsrpChangethreshR16EnumeratedDb6
	RsrpChangethreshR16EnumeratedDb8
	RsrpChangethreshR16EnumeratedDb10
	RsrpChangethreshR16EnumeratedDb14
	RsrpChangethreshR16EnumeratedDb18
	RsrpChangethreshR16EnumeratedDb22
	RsrpChangethreshR16EnumeratedDb26
	RsrpChangethreshR16EnumeratedDb30
	RsrpChangethreshR16EnumeratedDb34
	RsrpChangethreshR16EnumeratedSpare6
	RsrpChangethreshR16EnumeratedSpare5
	RsrpChangethreshR16EnumeratedSpare4
	RsrpChangethreshR16EnumeratedSpare3
	RsrpChangethreshR16EnumeratedSpare2
	RsrpChangethreshR16EnumeratedSpare1
)
