package ies

import "rrc/utils"

// RxTxPeriodical-r17-reportAmount-r17 ::= ENUMERATED
type RxtxperiodicalR17ReportamountR17 struct {
	Value utils.ENUMERATED
}

const (
	RxtxperiodicalR17ReportamountR17EnumeratedNothing = iota
	RxtxperiodicalR17ReportamountR17EnumeratedR1
	RxtxperiodicalR17ReportamountR17EnumeratedInfinity
	RxtxperiodicalR17ReportamountR17EnumeratedSpare6
	RxtxperiodicalR17ReportamountR17EnumeratedSpare5
	RxtxperiodicalR17ReportamountR17EnumeratedSpare4
	RxtxperiodicalR17ReportamountR17EnumeratedSpare3
	RxtxperiodicalR17ReportamountR17EnumeratedSpare2
	RxtxperiodicalR17ReportamountR17EnumeratedSpare1
)
