package ies

import "rrc/utils"

// SCG-DeactivationPreferenceConfig-r17-scg-DeactivationPreferenceProhibitTimer-r17 ::= ENUMERATED
type ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17 struct {
	Value utils.ENUMERATED
}

const (
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedNothing = iota
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS0
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS1
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS2
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS4
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS8
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS10
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS15
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS30
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS60
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS120
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS180
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS240
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS300
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS600
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS900
	ScgDeactivationpreferenceconfigR17ScgDeactivationpreferenceprohibittimerR17EnumeratedS1800
)
