package ies

import "rrc/utils"

// SchedulingRequestConfig-v1530-setup-dssr-TransMax-r15 ::= ENUMERATED
type SchedulingrequestconfigV1530SetupDssrTransmaxR15 struct {
	Value utils.ENUMERATED
}

const (
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedNothing = iota
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedN4
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedN8
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedN16
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedN32
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedN64
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedSpare3
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedSpare2
	SchedulingrequestconfigV1530SetupDssrTransmaxR15EnumeratedSpare1
)
