package ies

import "rrc/utils"

// SC-MCCH-SchedulingInfo-r14-drx-InactivityTimerSCPTM-r14 ::= ENUMERATED
type ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedNothing = iota
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf0
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf1
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf2
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf4
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf8
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf16
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf32
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf64
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf128
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf256
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPs512
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf1024
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf2048
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf4096
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf8192
	ScMcchSchedulinginfoR14DrxInactivitytimerscptmR14EnumeratedPsf16384
)
