package ies

import "rrc/utils"

// SC-MCCH-SchedulingInfo-NB-r14-onDurationTimerSCPTM-r14 ::= ENUMERATED
type ScMcchSchedulinginfoNbR14OndurationtimerscptmR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedNothing = iota
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp1
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp2
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp3
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp4
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp8
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp16
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp32
	ScMcchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedSpare
)
