package ies

import "rrc/utils"

// SC-MCCH-SchedulingInfo-NB-r14-drx-InactivityTimerSCPTM-r14 ::= ENUMERATED
type ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedNothing = iota
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp0
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp1
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp2
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp3
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp4
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp8
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp16
	ScMcchSchedulinginfoNbR14DrxInactivitytimerscptmR14EnumeratedPp32
)
