package ies

import "rrc/utils"

// SC-MTCH-SchedulingInfo-r13-onDurationTimerSCPTM-r13 ::= ENUMERATED
type ScMtchSchedulinginfoR13OndurationtimerscptmR13 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedNothing = iota
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf1
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf2
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf3
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf4
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf5
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf6
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf8
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf10
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf20
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf30
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf40
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf50
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf60
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf80
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf100
	ScMtchSchedulinginfoR13OndurationtimerscptmR13EnumeratedPsf200
)
