package ies

import "rrc/utils"

// SC-MTCH-SchedulingInfo-BR-r14-onDurationTimerSCPTM-r14 ::= ENUMERATED
type ScMtchSchedulinginfoBrR14OndurationtimerscptmR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedNothing = iota
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf300
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf400
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf500
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf600
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf800
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf1000
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf1200
	ScMtchSchedulinginfoBrR14OndurationtimerscptmR14EnumeratedPsf1600
)
