package ies

import "rrc/utils"

// SC-MTCH-SchedulingInfo-r13-drx-InactivityTimerSCPTM-r13 ::= ENUMERATED
type ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedNothing = iota
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf0
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf1
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf2
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf4
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf8
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf10
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf20
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf40
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf80
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf160
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPs320
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf640
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf960
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf1280
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf1920
	ScMtchSchedulinginfoR13DrxInactivitytimerscptmR13EnumeratedPsf2560
)
