package ies

import "rrc/utils"

// SC-MTCH-Info-NB-r14-npdcch-NumRepetitions-SC-MTCH-r14 ::= ENUMERATED
type ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedNothing = iota
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR1
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR2
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR4
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR8
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR16
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR32
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR64
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR128
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR256
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR512
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR1024
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedR2048
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedSpare4
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedSpare3
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedSpare2
	ScMtchInfoNbR14NpdcchNumrepetitionsScMtchR14EnumeratedSpare1
)
