package ies

import "rrc/utils"

// SC-MTCH-SchedulingInfo-NB-r14-onDurationTimerSCPTM-r14 ::= ENUMERATED
type ScMtchSchedulinginfoNbR14OndurationtimerscptmR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedNothing = iota
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp1
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp2
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp3
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp4
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp8
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp16
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedPp32
	ScMtchSchedulinginfoNbR14OndurationtimerscptmR14EnumeratedSpare
)
