package ies

import "rrc/utils"

// SC-MTCH-Info-BR-r14-mpdcch-NumRepetition-SC-MTCH-r14 ::= ENUMERATED
type ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedNothing = iota
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR1
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR2
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR4
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR8
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR16
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR32
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR64
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR128
	ScMtchInfoBrR14MpdcchNumrepetitionScMtchR14EnumeratedR256
)
