package ies

import "rrc/utils"

// SC-MTCH-SchedulingInfo-BR-r14-drx-InactivityTimerSCPTM-r14 ::= ENUMERATED
type ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedNothing = iota
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf0
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf1
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf2
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf4
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf8
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf16
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf32
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf64
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf128
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf256
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPs512
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf1024
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf2048
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf4096
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf8192
	ScMtchSchedulinginfoBrR14DrxInactivitytimerscptmR14EnumeratedPsf16384
)
