package ies

import "rrc/utils"

// SC-MTCH-Info-NB-r14-npdcch-StartSF-SC-MTCH-r14 ::= ENUMERATED
type ScMtchInfoNbR14NpdcchStartsfScMtchR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedNothing = iota
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV1dot5
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV2
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV4
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV8
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV16
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV32
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV48
	ScMtchInfoNbR14NpdcchStartsfScMtchR14EnumeratedV64
)
