package ies

import "rrc/utils"

// SC-MTCH-Info-BR-r14-mpdcch-Offset-SC-MTCH-r14 ::= ENUMERATED
type ScMtchInfoBrR14MpdcchOffsetScMtchR14 struct {
	Value utils.ENUMERATED
}

const (
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedNothing = iota
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedZero
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedOneeighth
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedOnequarter
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedThreeeighth
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedOnehalf
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedFiveeighth
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedThreequarter
	ScMtchInfoBrR14MpdcchOffsetScMtchR14EnumeratedSeveneighth
)
