package ies

import "rrc/utils"

// SDT-ConfigCommonSIB-r17-sdt-LogicalChannelSR-DelayTimer-r17 ::= ENUMERATED
type SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17 struct {
	Value utils.ENUMERATED
}

const (
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedNothing = iota
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSf20
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSf40
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSf64
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSf128
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSf512
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSf1024
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSf2560
	SdtConfigcommonsibR17SdtLogicalchannelsrDelaytimerR17EnumeratedSpare1
)
