package ies

import "rrc/utils"

// SearchSpace-nrofCandidates-aggregationLevel8 ::= ENUMERATED
type SearchspaceNrofcandidatesAggregationlevel8 struct {
	Value utils.ENUMERATED
}

const (
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedNothing = iota
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN0
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN1
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN2
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN3
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN4
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN5
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN6
	SearchspaceNrofcandidatesAggregationlevel8EnumeratedN8
)
