package ies

import "rrc/utils"

// SearchSpace-searchSpaceType-common-dci-Format2-0-nrofCandidates-SFI-aggregationLevel1 ::= ENUMERATED
type SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel1 struct {
	Value utils.ENUMERATED
}

const (
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel1EnumeratedNothing = iota
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel1EnumeratedN1
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel1EnumeratedN2
)
