package ies

import "rrc/utils"

// SearchSpace-searchSpaceType-common-dci-Format2-0-nrofCandidates-SFI-aggregationLevel4 ::= ENUMERATED
type SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel4 struct {
	Value utils.ENUMERATED
}

const (
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel4EnumeratedNothing = iota
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel4EnumeratedN1
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel4EnumeratedN2
)
