package ies

import "rrc/utils"

// SearchSpace-searchSpaceType-common-dci-Format2-0-nrofCandidates-SFI-aggregationLevel2 ::= ENUMERATED
type SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel2 struct {
	Value utils.ENUMERATED
}

const (
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel2EnumeratedNothing = iota
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel2EnumeratedN1
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel2EnumeratedN2
)
