package ies

import "rrc/utils"

// SearchSpace-searchSpaceType-common-dci-Format2-0-nrofCandidates-SFI-aggregationLevel8 ::= ENUMERATED
type SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel8 struct {
	Value utils.ENUMERATED
}

const (
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel8EnumeratedNothing = iota
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel8EnumeratedN1
	SearchspaceSearchspacetypeCommonDciFormat20NrofcandidatesSfiAggregationlevel8EnumeratedN2
)
