package ies

import "rrc/utils"

// SearchSpace-nrofCandidates-aggregationLevel1 ::= ENUMERATED
type SearchspaceNrofcandidatesAggregationlevel1 struct {
	Value utils.ENUMERATED
}

const (
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedNothing = iota
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN0
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN1
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN2
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN3
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN4
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN5
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN6
	SearchspaceNrofcandidatesAggregationlevel1EnumeratedN8
)
