package ies

// SearchSpace-nrofCandidates ::= SEQUENCE
type SearchspaceNrofcandidates struct {
	Aggregationlevel1  SearchspaceNrofcandidatesAggregationlevel1
	Aggregationlevel2  SearchspaceNrofcandidatesAggregationlevel2
	Aggregationlevel4  SearchspaceNrofcandidatesAggregationlevel4
	Aggregationlevel8  SearchspaceNrofcandidatesAggregationlevel8
	Aggregationlevel16 SearchspaceNrofcandidatesAggregationlevel16
}
