package ies

import "rrc/utils"

// SemiStaticChannelAccessConfig-r16-period ::= ENUMERATED
type SemistaticchannelaccessconfigR16Period struct {
	Value utils.ENUMERATED
}

const (
	SemistaticchannelaccessconfigR16PeriodEnumeratedNothing = iota
	SemistaticchannelaccessconfigR16PeriodEnumeratedMs1
	SemistaticchannelaccessconfigR16PeriodEnumeratedMs2
	SemistaticchannelaccessconfigR16PeriodEnumeratedMs2dot5
	SemistaticchannelaccessconfigR16PeriodEnumeratedMs4
	SemistaticchannelaccessconfigR16PeriodEnumeratedMs5
	SemistaticchannelaccessconfigR16PeriodEnumeratedMs10
)
