package ies

import "rrc/utils"

// SemiStaticChannelAccessConfigUE-r17-periodUE-r17 ::= ENUMERATED
type SemistaticchannelaccessconfigueR17PeriodueR17 struct {
	Value utils.ENUMERATED
}

const (
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedNothing = iota
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedMs1
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedMs2
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedMs2dot5
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedMs4
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedMs5
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedMs10
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedSpare2
	SemistaticchannelaccessconfigueR17PeriodueR17EnumeratedSpare1
)
