package ies

import "rrc/utils"

// ServingCellConfigCommon-discoveryBurstWindowLength-r16 ::= ENUMERATED
type ServingcellconfigcommonDiscoveryburstwindowlengthR16 struct {
	Value utils.ENUMERATED
}

const (
	ServingcellconfigcommonDiscoveryburstwindowlengthR16EnumeratedNothing = iota
	ServingcellconfigcommonDiscoveryburstwindowlengthR16EnumeratedMs0dot5
	ServingcellconfigcommonDiscoveryburstwindowlengthR16EnumeratedMs1
	ServingcellconfigcommonDiscoveryburstwindowlengthR16EnumeratedMs2
	ServingcellconfigcommonDiscoveryburstwindowlengthR16EnumeratedMs3
	ServingcellconfigcommonDiscoveryburstwindowlengthR16EnumeratedMs4
	ServingcellconfigcommonDiscoveryburstwindowlengthR16EnumeratedMs5
)
