package ies

import "rrc/utils"

// ServingCellConfigCommonSIB-ssb-PeriodicityServingCell ::= ENUMERATED
type ServingcellconfigcommonsibSsbPeriodicityservingcell struct {
	Value utils.ENUMERATED
}

const (
	ServingcellconfigcommonsibSsbPeriodicityservingcellEnumeratedNothing = iota
	ServingcellconfigcommonsibSsbPeriodicityservingcellEnumeratedMs5
	ServingcellconfigcommonsibSsbPeriodicityservingcellEnumeratedMs10
	ServingcellconfigcommonsibSsbPeriodicityservingcellEnumeratedMs20
	ServingcellconfigcommonsibSsbPeriodicityservingcellEnumeratedMs40
	ServingcellconfigcommonsibSsbPeriodicityservingcellEnumeratedMs80
	ServingcellconfigcommonsibSsbPeriodicityservingcellEnumeratedMs160
)
