package ies

import "rrc/utils"

// ServingCellConfig-sCellDeactivationTimer ::= ENUMERATED
type ServingcellconfigScelldeactivationtimer struct {
	Value utils.ENUMERATED
}

const (
	ServingcellconfigScelldeactivationtimerEnumeratedNothing = iota
	ServingcellconfigScelldeactivationtimerEnumeratedMs20
	ServingcellconfigScelldeactivationtimerEnumeratedMs40
	ServingcellconfigScelldeactivationtimerEnumeratedMs80
	ServingcellconfigScelldeactivationtimerEnumeratedMs160
	ServingcellconfigScelldeactivationtimerEnumeratedMs200
	ServingcellconfigScelldeactivationtimerEnumeratedMs240
	ServingcellconfigScelldeactivationtimerEnumeratedMs320
	ServingcellconfigScelldeactivationtimerEnumeratedMs400
	ServingcellconfigScelldeactivationtimerEnumeratedMs480
	ServingcellconfigScelldeactivationtimerEnumeratedMs520
	ServingcellconfigScelldeactivationtimerEnumeratedMs640
	ServingcellconfigScelldeactivationtimerEnumeratedMs720
	ServingcellconfigScelldeactivationtimerEnumeratedMs840
	ServingcellconfigScelldeactivationtimerEnumeratedMs1280
	ServingcellconfigScelldeactivationtimerEnumeratedSpare2
	ServingcellconfigScelldeactivationtimerEnumeratedSpare1
)
