package ies

import "rrc/utils"

// ServingCellConfigCommonSIB-discoveryBurstWindowLength-v1700 ::= ENUMERATED
type ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700 struct {
	Value utils.ENUMERATED
}

const (
	ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700EnumeratedNothing = iota
	ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700EnumeratedMs0dot125
	ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700EnumeratedMs0dot25
	ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700EnumeratedMs0dot5
	ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700EnumeratedMs0dot75
	ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700EnumeratedMs1
	ServingcellconfigcommonsibDiscoveryburstwindowlengthV1700EnumeratedMs1dot25
)
