package ies

import "rrc/utils"

// ServingCellConfigCommonSIB-discoveryBurstWindowLength-r16 ::= ENUMERATED
type ServingcellconfigcommonsibDiscoveryburstwindowlengthR16 struct {
	Value utils.ENUMERATED
}

const (
	ServingcellconfigcommonsibDiscoveryburstwindowlengthR16EnumeratedNothing = iota
	ServingcellconfigcommonsibDiscoveryburstwindowlengthR16EnumeratedMs0dot5
	ServingcellconfigcommonsibDiscoveryburstwindowlengthR16EnumeratedMs1
	ServingcellconfigcommonsibDiscoveryburstwindowlengthR16EnumeratedMs2
	ServingcellconfigcommonsibDiscoveryburstwindowlengthR16EnumeratedMs3
	ServingcellconfigcommonsibDiscoveryburstwindowlengthR16EnumeratedMs4
	ServingcellconfigcommonsibDiscoveryburstwindowlengthR16EnumeratedMs5
)
