package ies

import "rrc/utils"

// ServingCellConfig-bwp-InactivityTimer ::= ENUMERATED
type ServingcellconfigBwpInactivitytimer struct {
	Value utils.ENUMERATED
}

const (
	ServingcellconfigBwpInactivitytimerEnumeratedNothing = iota
	ServingcellconfigBwpInactivitytimerEnumeratedMs2
	ServingcellconfigBwpInactivitytimerEnumeratedMs3
	ServingcellconfigBwpInactivitytimerEnumeratedMs4
	ServingcellconfigBwpInactivitytimerEnumeratedMs5
	ServingcellconfigBwpInactivitytimerEnumeratedMs6
	ServingcellconfigBwpInactivitytimerEnumeratedMs8
	ServingcellconfigBwpInactivitytimerEnumeratedMs10
	ServingcellconfigBwpInactivitytimerEnumeratedMs20
	ServingcellconfigBwpInactivitytimerEnumeratedMs30
	ServingcellconfigBwpInactivitytimerEnumeratedMs40
	ServingcellconfigBwpInactivitytimerEnumeratedMs50
	ServingcellconfigBwpInactivitytimerEnumeratedMs60
	ServingcellconfigBwpInactivitytimerEnumeratedMs80
	ServingcellconfigBwpInactivitytimerEnumeratedMs100
	ServingcellconfigBwpInactivitytimerEnumeratedMs200
	ServingcellconfigBwpInactivitytimerEnumeratedMs300
	ServingcellconfigBwpInactivitytimerEnumeratedMs500
	ServingcellconfigBwpInactivitytimerEnumeratedMs750
	ServingcellconfigBwpInactivitytimerEnumeratedMs1280
	ServingcellconfigBwpInactivitytimerEnumeratedMs1920
	ServingcellconfigBwpInactivitytimerEnumeratedMs2560
	ServingcellconfigBwpInactivitytimerEnumeratedSpare10
	ServingcellconfigBwpInactivitytimerEnumeratedSpare9
	ServingcellconfigBwpInactivitytimerEnumeratedSpare8
	ServingcellconfigBwpInactivitytimerEnumeratedSpare7
	ServingcellconfigBwpInactivitytimerEnumeratedSpare6
	ServingcellconfigBwpInactivitytimerEnumeratedSpare5
	ServingcellconfigBwpInactivitytimerEnumeratedSpare4
	ServingcellconfigBwpInactivitytimerEnumeratedSpare3
	ServingcellconfigBwpInactivitytimerEnumeratedSpare2
	ServingcellconfigBwpInactivitytimerEnumeratedSpare1
)
