package ies

import "rrc/utils"

// SIB2-relaxedMeasurement-r16-lowMobilityEvaluation-r16-t-SearchDeltaP-r16 ::= ENUMERATED
type Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16 struct {
	Value utils.ENUMERATED
}

const (
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedNothing = iota
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS5
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS10
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS20
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS30
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS60
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS120
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS180
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS240
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedS300
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedSpare7
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedSpare6
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedSpare5
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedSpare4
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedSpare3
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedSpare2
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16TSearchdeltapR16EnumeratedSpare1
)
