package ies

import "rrc/utils"

// SIB2-relaxedMeasurement-r17-stationaryMobilityEvaluation-r17-t-SearchDeltaP-Stationary-r17 ::= ENUMERATED
type Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17 struct {
	Value utils.ENUMERATED
}

const (
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedNothing = iota
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS5
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS10
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS20
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS30
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS60
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS120
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS180
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS240
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedS300
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedSpare7
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedSpare6
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedSpare5
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedSpare4
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedSpare3
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedSpare2
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17TSearchdeltapStationaryR17EnumeratedSpare1
)
