package ies

import "rrc/utils"

// SIB2-relaxedMeasurement-r16-lowMobilityEvaluation-r16-s-SearchDeltaP-r16 ::= ENUMERATED
type Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16 struct {
	Value utils.ENUMERATED
}

const (
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedNothing = iota
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedDb3
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedDb6
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedDb9
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedDb12
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedDb15
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedSpare3
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedSpare2
	Sib2RelaxedmeasurementR16LowmobilityevaluationR16SSearchdeltapR16EnumeratedSpare1
)
