package ies

import "rrc/utils"

// SIB2-cellReselectionInfoCommon-speedStateReselectionPars-q-HystSF-sf-Medium ::= ENUMERATED
type Sib2CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMedium struct {
	Value utils.ENUMERATED
}

const (
	Sib2CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedNothing = iota
	Sib2CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb_6
	Sib2CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb_4
	Sib2CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb_2
	Sib2CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb0
)
