package ies

import "rrc/utils"

// SIB2-relaxedMeasurement-r17-stationaryMobilityEvaluation-r17-s-SearchDeltaP-Stationary-r17 ::= ENUMERATED
type Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17 struct {
	Value utils.ENUMERATED
}

const (
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedNothing = iota
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedDb2
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedDb3
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedDb6
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedDb9
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedDb12
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedDb15
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedSpare2
	Sib2RelaxedmeasurementR17StationarymobilityevaluationR17SSearchdeltapStationaryR17EnumeratedSpare1
)
