package ies

import "rrc/utils"

// SidelinkPreconfigNR-r16-sl-MaxNumConsecutiveDTX-r16 ::= ENUMERATED
type SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16 struct {
	Value utils.ENUMERATED
}

const (
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedNothing = iota
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN1
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN2
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN3
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN4
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN6
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN8
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN16
	SidelinkpreconfignrR16SlMaxnumconsecutivedtxR16EnumeratedN32
)
