package ies

import "rrc/utils"

// SI-SchedulingInfo-si-WindowLength ::= ENUMERATED
type SiSchedulinginfoSiWindowlength struct {
	Value utils.ENUMERATED
}

const (
	SiSchedulinginfoSiWindowlengthEnumeratedNothing = iota
	SiSchedulinginfoSiWindowlengthEnumeratedS5
	SiSchedulinginfoSiWindowlengthEnumeratedS10
	SiSchedulinginfoSiWindowlengthEnumeratedS20
	SiSchedulinginfoSiWindowlengthEnumeratedS40
	SiSchedulinginfoSiWindowlengthEnumeratedS80
	SiSchedulinginfoSiWindowlengthEnumeratedS160
	SiSchedulinginfoSiWindowlengthEnumeratedS320
	SiSchedulinginfoSiWindowlengthEnumeratedS640
	SiSchedulinginfoSiWindowlengthEnumeratedS1280
	SiSchedulinginfoSiWindowlengthEnumeratedS2560_V1710
	SiSchedulinginfoSiWindowlengthEnumeratedS5120_V1710
)
