package ies

import "rrc/utils"

// SL-BWP-Generic-r16-sl-LengthSymbols-r16 ::= ENUMERATED
type SlBwpGenericR16SlLengthsymbolsR16 struct {
	Value utils.ENUMERATED
}

const (
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedNothing = iota
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym7
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym8
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym9
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym10
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym11
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym12
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym13
	SlBwpGenericR16SlLengthsymbolsR16EnumeratedSym14
)
