package ies

import "rrc/utils"

// SL-CommTxPoolSensingConfig-r14-probResourceKeep-r14 ::= ENUMERATED
type SlCommtxpoolsensingconfigR14ProbresourcekeepR14 struct {
	Value utils.ENUMERATED
}

const (
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedNothing = iota
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedV0
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedV0dot2
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedV0dot4
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedV0dot6
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedV0dot8
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedSpare3
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedSpare2
	SlCommtxpoolsensingconfigR14ProbresourcekeepR14EnumeratedSpare1
)
