package ies

import "rrc/utils"

// SL-CommTxPoolSensingConfig-r14-sl-ReselectAfter-r14 ::= ENUMERATED
type SlCommtxpoolsensingconfigR14SlReselectafterR14 struct {
	Value utils.ENUMERATED
}

const (
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedNothing = iota
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN1
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN2
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN3
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN4
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN5
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN6
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN7
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN8
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedN9
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedSpare7
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedSpare6
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedSpare5
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedSpare4
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedSpare3
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedSpare2
	SlCommtxpoolsensingconfigR14SlReselectafterR14EnumeratedSpare1
)
