package ies

import "rrc/utils"

// SL-ConfigCommonNR-r16-sl-MaxNumConsecutiveDTX-r16 ::= ENUMERATED
type SlConfigcommonnrR16SlMaxnumconsecutivedtxR16 struct {
	Value utils.ENUMERATED
}

const (
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedNothing = iota
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN1
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN2
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN3
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN4
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN6
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN8
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN16
	SlConfigcommonnrR16SlMaxnumconsecutivedtxR16EnumeratedN32
)
