package ies

import "rrc/utils"

// SL-CommResourcePoolV2X-r14-numSubchannel-r14 ::= ENUMERATED
type SlCommresourcepoolv2xR14NumsubchannelR14 struct {
	Value utils.ENUMERATED
}

const (
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedNothing = iota
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedN1
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedN3
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedN5
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedN8
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedN10
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedN15
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedN20
	SlCommresourcepoolv2xR14NumsubchannelR14EnumeratedSpare1
)
