package ies

import "rrc/utils"

// SL-DRX-GC-BC-QoS-r17-sl-DRX-GC-InactivityTimer-r17 ::= ENUMERATED
type SlDrxGcBcQosR17SlDrxGcInactivitytimerR17 struct {
	Value utils.ENUMERATED
}

const (
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedNothing = iota
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs0
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs1
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs2
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs3
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs4
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs5
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs6
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs8
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs10
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs20
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs30
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs40
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs50
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs60
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs80
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs100
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs200
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs300
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs500
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs750
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs1280
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs1920
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedMs2560
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare9
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare8
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare7
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare6
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare5
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare4
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare3
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare2
	SlDrxGcBcQosR17SlDrxGcInactivitytimerR17EnumeratedSpare1
)
