package ies

import "rrc/utils"

// SL-DRX-ConfigUC-r17-sl-drx-InactivityTimer-r17 ::= ENUMERATED
type SlDrxConfigucR17SlDrxInactivitytimerR17 struct {
	Value utils.ENUMERATED
}

const (
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedNothing = iota
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs0
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs1
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs2
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs3
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs4
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs5
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs6
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs8
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs10
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs20
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs30
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs40
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs50
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs60
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs80
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs100
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs200
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs300
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs500
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs750
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs1280
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs1920
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedMs2560
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare9
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare8
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare7
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare6
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare5
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare4
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare3
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare2
	SlDrxConfigucR17SlDrxInactivitytimerR17EnumeratedSpare1
)
