package ies

import "rrc/utils"

// SL-DRX-ConfigUC-r17-sl-drx-RetransmissionTimer-r17 ::= ENUMERATED
type SlDrxConfigucR17SlDrxRetransmissiontimerR17 struct {
	Value utils.ENUMERATED
}

const (
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedNothing = iota
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl0
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl1
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl2
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl4
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl6
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl8
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl16
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl24
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl33
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl40
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl64
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl80
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl96
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl112
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl128
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl160
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSl320
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare15
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare14
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare13
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare12
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare11
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare10
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare9
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare8
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare7
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare6
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare5
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare4
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare3
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare2
	SlDrxConfigucR17SlDrxRetransmissiontimerR17EnumeratedSpare1
)
