package ies

import "rrc/utils"

// SL-DRX-GC-Generic-r17-sl-DRX-GC-RetransmissionTimer-r17 ::= ENUMERATED
type SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17 struct {
	Value utils.ENUMERATED
}

const (
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedNothing = iota
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl0
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl1
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl2
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl4
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl6
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl8
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl16
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl24
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl33
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl40
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl64
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl80
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl96
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl112
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl128
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl160
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSl320
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare15
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare14
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare13
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare12
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare11
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare10
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare9
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare8
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare7
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare6
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare5
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare4
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare3
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare2
	SlDrxGcGenericR17SlDrxGcRetransmissiontimerR17EnumeratedSpare1
)
