package ies

import "rrc/utils"

// SL-DRX-ConfigUC-r17-sl-drx-HARQ-RTT-Timer2-r17 ::= ENUMERATED
type SlDrxConfigucR17SlDrxHarqRttTimer2R17 struct {
	Value utils.ENUMERATED
}

const (
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedNothing = iota
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSl0
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSl1
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSl2
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSl4
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSpare4
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSpare3
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSpare2
	SlDrxConfigucR17SlDrxHarqRttTimer2R17EnumeratedSpare1
)
