package ies

import "rrc/utils"

// SL-DRX-ConfigUC-r17-sl-drx-HARQ-RTT-Timer1-r17 ::= ENUMERATED
type SlDrxConfigucR17SlDrxHarqRttTimer1R17 struct {
	Value utils.ENUMERATED
}

const (
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedNothing = iota
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSl0
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSl1
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSl2
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSl4
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSpare4
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSpare3
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSpare2
	SlDrxConfigucR17SlDrxHarqRttTimer1R17EnumeratedSpare1
)
