package ies

import "rrc/utils"

// SL-EventTriggerConfig-r16-sl-ReportAmount-r16 ::= ENUMERATED
type SlEventtriggerconfigR16SlReportamountR16 struct {
	Value utils.ENUMERATED
}

const (
	SlEventtriggerconfigR16SlReportamountR16EnumeratedNothing = iota
	SlEventtriggerconfigR16SlReportamountR16EnumeratedR1
	SlEventtriggerconfigR16SlReportamountR16EnumeratedR2
	SlEventtriggerconfigR16SlReportamountR16EnumeratedR4
	SlEventtriggerconfigR16SlReportamountR16EnumeratedR8
	SlEventtriggerconfigR16SlReportamountR16EnumeratedR16
	SlEventtriggerconfigR16SlReportamountR16EnumeratedR32
	SlEventtriggerconfigR16SlReportamountR16EnumeratedR64
	SlEventtriggerconfigR16SlReportamountR16EnumeratedInfinity
)
