package ies

import "rrc/utils"

// SL-LogicalChannelConfig-r16-sl-BucketSizeDuration-r16 ::= ENUMERATED
type SlLogicalchannelconfigR16SlBucketsizedurationR16 struct {
	Value utils.ENUMERATED
}

const (
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedNothing = iota
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs5
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs10
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs20
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs50
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs100
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs150
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs300
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs500
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedMs1000
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedSpare7
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedSpare6
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedSpare5
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedSpare4
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedSpare3
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedSpare2
	SlLogicalchannelconfigR16SlBucketsizedurationR16EnumeratedSpare1
)
