package ies

import "rrc/utils"

// SL-LogicalChannelConfig-r16-sl-MaxPUSCH-Duration-r16 ::= ENUMERATED
type SlLogicalchannelconfigR16SlMaxpuschDurationR16 struct {
	Value utils.ENUMERATED
}

const (
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedNothing = iota
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedMs0p02
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedMs0p04
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedMs0p0625
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedMs0p125
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedMs0p25
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedMs0p5
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedSpare2
	SlLogicalchannelconfigR16SlMaxpuschDurationR16EnumeratedSpare1
)
