package ies

import "rrc/utils"

// SL-LogicalChannelConfig-r16-sl-PrioritisedBitRate-r16 ::= ENUMERATED
type SlLogicalchannelconfigR16SlPrioritisedbitrateR16 struct {
	Value utils.ENUMERATED
}

const (
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedNothing = iota
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps0
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps8
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps16
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps32
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps64
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps128
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps256
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps512
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps1024
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps2048
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps4096
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps8192
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps16384
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps32768
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedKbps65536
	SlLogicalchannelconfigR16SlPrioritisedbitrateR16EnumeratedInfinity
)
