package ies

import "rrc/utils"

// SlotOrSubslotPDSCH-Config-r15-setup-altCQI-TableSTTI-r15 ::= ENUMERATED
type SlotorsubslotpdschConfigR15SetupAltcqiTablesttiR15 struct {
	Value utils.ENUMERATED
}

const (
	SlotorsubslotpdschConfigR15SetupAltcqiTablesttiR15EnumeratedNothing = iota
	SlotorsubslotpdschConfigR15SetupAltcqiTablesttiR15EnumeratedAllsubframes
	SlotorsubslotpdschConfigR15SetupAltcqiTablesttiR15EnumeratedCsi_Subframeset1
	SlotorsubslotpdschConfigR15SetupAltcqiTablesttiR15EnumeratedCsi_Subframeset2
	SlotorsubslotpdschConfigR15SetupAltcqiTablesttiR15EnumeratedSpare1
)
