package ies

import "rrc/utils"

// SL-PBPS-CPS-Config-r17-sl-AllowedResourceSelectionConfig-r17 ::= ENUMERATED
type SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17 struct {
	Value utils.ENUMERATED
}

const (
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedNothing = iota
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedC1
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedC2
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedC3
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedC4
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedC5
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedC6
	SlPbpsCpsConfigR17SlAllowedresourceselectionconfigR17EnumeratedC7
)
