package ies

import "rrc/utils"

// SL-PowerControl-r16-dl-Alpha-PSFCH-r16 ::= ENUMERATED
type SlPowercontrolR16DlAlphaPsfchR16 struct {
	Value utils.ENUMERATED
}

const (
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedNothing = iota
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha0
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha04
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha05
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha06
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha07
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha08
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha09
	SlPowercontrolR16DlAlphaPsfchR16EnumeratedAlpha1
)
