package ies

import "rrc/utils"

// SL-PowerControl-r16-dl-Alpha-PSSCH-PSCCH-r16 ::= ENUMERATED
type SlPowercontrolR16DlAlphaPsschPscchR16 struct {
	Value utils.ENUMERATED
}

const (
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedNothing = iota
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha0
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha04
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha05
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha06
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha07
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha08
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha09
	SlPowercontrolR16DlAlphaPsschPscchR16EnumeratedAlpha1
)
