package ies

import "rrc/utils"

// SL-PreconfigV2X-Sync-r14-syncRefDiffHyst-r14 ::= ENUMERATED
type SlPreconfigv2xSyncR14SyncrefdiffhystR14 struct {
	Value utils.ENUMERATED
}

const (
	SlPreconfigv2xSyncR14SyncrefdiffhystR14EnumeratedNothing = iota
	SlPreconfigv2xSyncR14SyncrefdiffhystR14EnumeratedDb0
	SlPreconfigv2xSyncR14SyncrefdiffhystR14EnumeratedDb3
	SlPreconfigv2xSyncR14SyncrefdiffhystR14EnumeratedDb6
	SlPreconfigv2xSyncR14SyncrefdiffhystR14EnumeratedDb9
	SlPreconfigv2xSyncR14SyncrefdiffhystR14EnumeratedDb12
	SlPreconfigv2xSyncR14SyncrefdiffhystR14EnumeratedDbinf
)
