package ies

import "rrc/utils"

// SL-RestrictResourceReservationPeriod-r14 ::= ENUMERATED
type SlRestrictresourcereservationperiodR14 struct {
	Value utils.ENUMERATED
}

const (
	SlRestrictresourcereservationperiodR14EnumeratedNothing = iota
	SlRestrictresourcereservationperiodR14EnumeratedV0dot2
	SlRestrictresourcereservationperiodR14EnumeratedV0dot5
	SlRestrictresourcereservationperiodR14EnumeratedV1
	SlRestrictresourcereservationperiodR14EnumeratedV2
	SlRestrictresourcereservationperiodR14EnumeratedV3
	SlRestrictresourcereservationperiodR14EnumeratedV4
	SlRestrictresourcereservationperiodR14EnumeratedV5
	SlRestrictresourcereservationperiodR14EnumeratedV6
	SlRestrictresourcereservationperiodR14EnumeratedV7
	SlRestrictresourcereservationperiodR14EnumeratedV8
	SlRestrictresourcereservationperiodR14EnumeratedV9
	SlRestrictresourcereservationperiodR14EnumeratedV10
	SlRestrictresourcereservationperiodR14EnumeratedSpare4
	SlRestrictresourcereservationperiodR14EnumeratedSpare3
	SlRestrictresourcereservationperiodR14EnumeratedSpare2
	SlRestrictresourcereservationperiodR14EnumeratedSpare1
)
