package ies

import "rrc/utils"

// SL-SIB-ReqInfo-r17 ::= utils.ENUMERATED // Extensible
type SlSibReqinfoR17 struct {
	Value utils.ENUMERATED
}

const (
	SlSibReqinfoR17EnumeratedNothing = iota
	SlSibReqinfoR17EnumeratedSib1
	SlSibReqinfoR17EnumeratedSib2
	SlSibReqinfoR17EnumeratedSib3
	SlSibReqinfoR17EnumeratedSib4
	SlSibReqinfoR17EnumeratedSib5
	SlSibReqinfoR17EnumeratedSib6
	SlSibReqinfoR17EnumeratedSib7
	SlSibReqinfoR17EnumeratedSib8
	SlSibReqinfoR17EnumeratedSib9
	SlSibReqinfoR17EnumeratedSib10
	SlSibReqinfoR17EnumeratedSib11
	SlSibReqinfoR17EnumeratedSib12
	SlSibReqinfoR17EnumeratedSib13
	SlSibReqinfoR17EnumeratedSib14
	SlSibReqinfoR17EnumeratedSib15
	SlSibReqinfoR17EnumeratedSib16
	SlSibReqinfoR17EnumeratedSib17
	SlSibReqinfoR17EnumeratedSib18
	SlSibReqinfoR17EnumeratedSib19
	SlSibReqinfoR17EnumeratedSib20
	SlSibReqinfoR17EnumeratedSib21
	SlSibReqinfoR17EnumeratedSpare11
	SlSibReqinfoR17EnumeratedSpare10
	SlSibReqinfoR17EnumeratedSpare9
	SlSibReqinfoR17EnumeratedSpare8
	SlSibReqinfoR17EnumeratedSpare7
	SlSibReqinfoR17EnumeratedSpare6
	SlSibReqinfoR17EnumeratedSpare5
	SlSibReqinfoR17EnumeratedSpare4
	SlSibReqinfoR17EnumeratedSpare3
	SlSibReqinfoR17EnumeratedSpare2
	SlSibReqinfoR17EnumeratedSpare1
)
