package ies

import "rrc/utils"

// SL-SSB-TimeAllocation-r16-sl-NumSSB-WithinPeriod-r16 ::= ENUMERATED
type SlSsbTimeallocationR16SlNumssbWithinperiodR16 struct {
	Value utils.ENUMERATED
}

const (
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedNothing = iota
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedN1
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedN2
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedN4
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedN8
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedN16
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedN32
	SlSsbTimeallocationR16SlNumssbWithinperiodR16EnumeratedN64
)
