package ies

import "rrc/utils"

// SL-TrafficPatternInfo-r16-trafficPeriodicity-r16 ::= ENUMERATED
type SlTrafficpatterninfoR16TrafficperiodicityR16 struct {
	Value utils.ENUMERATED
}

const (
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedNothing = iota
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs20
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs50
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs100
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs200
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs300
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs400
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs500
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs600
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs700
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs800
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs900
	SlTrafficpatterninfoR16TrafficperiodicityR16EnumeratedMs1000
)
