package ies

import "rrc/utils"

// SoundingRS-UL-ConfigDedicatedUpPTsExt-r13-setup-cyclicShift-r13 ::= ENUMERATED
type SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13 struct {
	Value utils.ENUMERATED
}

const (
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedNothing = iota
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs0
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs1
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs2
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs3
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs4
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs5
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs6
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs7
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs8
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs9
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs10
	SoundingrsUlConfigdedicatedupptsextR13SetupCyclicshiftR13EnumeratedCs11
)
