package ies

import "rrc/utils"

// SoundingRS-UL-ConfigCommon-setup-srs-BandwidthConfig ::= ENUMERATED
type SoundingrsUlConfigcommonSetupSrsBandwidthconfig struct {
	Value utils.ENUMERATED
}

const (
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedNothing = iota
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw0
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw1
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw2
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw3
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw4
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw5
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw6
	SoundingrsUlConfigcommonSetupSrsBandwidthconfigEnumeratedBw7
)
