package ies

import "rrc/utils"

// SoundingRS-UL-ConfigCommon-setup-srs-SubframeConfig ::= ENUMERATED
type SoundingrsUlConfigcommonSetupSrsSubframeconfig struct {
	Value utils.ENUMERATED
}

const (
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedNothing = iota
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc0
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc1
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc2
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc3
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc4
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc5
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc6
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc7
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc8
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc9
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc10
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc11
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc12
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc13
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc14
	SoundingrsUlConfigcommonSetupSrsSubframeconfigEnumeratedSc15
)
