package ies

// SpatialRelationsSRS-Pos-r16 ::= SEQUENCE
type SpatialrelationssrsPosR16 struct {
	SpatialrelationSrsPosbasedonssbServingR16   *SpatialrelationssrsPosR16SpatialrelationSrsPosbasedonssbServingR16
	SpatialrelationSrsPosbasedoncsiRsServingR16 *SpatialrelationssrsPosR16SpatialrelationSrsPosbasedoncsiRsServingR16
	SpatialrelationSrsPosbasedonprsServingR16   *SpatialrelationssrsPosR16SpatialrelationSrsPosbasedonprsServingR16
	SpatialrelationSrsPosbasedonsrsR16          *SpatialrelationssrsPosR16SpatialrelationSrsPosbasedonsrsR16
	SpatialrelationSrsPosbasedonssbNeighR16     *SpatialrelationssrsPosR16SpatialrelationSrsPosbasedonssbNeighR16
	SpatialrelationSrsPosbasedonprsNeighR16     *SpatialrelationssrsPosR16SpatialrelationSrsPosbasedonprsNeighR16
}
