package ies

import "rrc/utils"

// SpCellConfig-lowMobilityEvaluationConnected-r17-s-SearchDeltaP-Connected-r17 ::= ENUMERATED
type SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17 struct {
	Value utils.ENUMERATED
}

const (
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedNothing = iota
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedDb3
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedDb6
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedDb9
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedDb12
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedDb15
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedSpare3
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedSpare2
	SpcellconfigLowmobilityevaluationconnectedR17SSearchdeltapConnectedR17EnumeratedSpare1
)
