package ies

import "rrc/utils"

// SpCellConfig-lowMobilityEvaluationConnected-r17-t-SearchDeltaP-Connected-r17 ::= ENUMERATED
type SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17 struct {
	Value utils.ENUMERATED
}

const (
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedNothing = iota
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS5
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS10
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS20
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS30
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS60
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS120
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS180
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS240
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedS300
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedSpare7
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedSpare6
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedSpare5
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedSpare4
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedSpare3
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedSpare2
	SpcellconfigLowmobilityevaluationconnectedR17TSearchdeltapConnectedR17EnumeratedSpare1
)
