package ies

import "rrc/utils"

// SPS-ConfigDL-STTI-r15-setup-semiPersistSchedIntervalDL-STTI-r15 ::= ENUMERATED
type SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15 struct {
	Value utils.ENUMERATED
}

const (
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedNothing = iota
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti1
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti2
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti3
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti4
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti6
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti8
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti12
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti16
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti20
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti40
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti60
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti80
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti120
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedStti240
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedSpare2
	SpsConfigdlSttiR15SetupSemipersistschedintervaldlSttiR15EnumeratedSpare1
)
