package ies

import "rrc/utils"

// SPS-ConfigDL-setup-semiPersistSchedIntervalDL ::= ENUMERATED
type SpsConfigdlSetupSemipersistschedintervaldl struct {
	Value utils.ENUMERATED
}

const (
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedNothing = iota
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf10
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf20
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf32
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf40
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf64
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf80
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf128
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf160
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf320
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSf640
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSpare6
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSpare5
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSpare4
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSpare3
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSpare2
	SpsConfigdlSetupSemipersistschedintervaldlEnumeratedSpare1
)
