package ies

import "rrc/utils"

// SPS-ConfigUL-setup-semiPersistSchedIntervalUL ::= ENUMERATED
type SpsConfigulSetupSemipersistschedintervalul struct {
	Value utils.ENUMERATED
}

const (
	SpsConfigulSetupSemipersistschedintervalulEnumeratedNothing = iota
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf10
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf20
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf32
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf40
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf64
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf80
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf128
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf160
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf320
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf640
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf1_V1430
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf2_V1430
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf3_V1430
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf4_V1430
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSf5_V1430
	SpsConfigulSetupSemipersistschedintervalulEnumeratedSpare1
)
