package ies

import "rrc/utils"

// SPS-ConfigSL-r14-semiPersistSchedIntervalSL-r14 ::= ENUMERATED
type SpsConfigslR14SemipersistschedintervalslR14 struct {
	Value utils.ENUMERATED
}

const (
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedNothing = iota
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf20
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf50
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf100
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf200
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf300
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf400
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf500
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf600
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf700
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf800
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf900
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSf1000
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSpare4
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSpare3
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSpare2
	SpsConfigslR14SemipersistschedintervalslR14EnumeratedSpare1
)
