package ies

import "rrc/utils"

// SPS-ConfigUL-STTI-r15-setup-semiPersistSchedIntervalUL-STTI-r15 ::= ENUMERATED
type SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15 struct {
	Value utils.ENUMERATED
}

const (
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedNothing = iota
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti1
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti2
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti3
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti4
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti6
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti8
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti12
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti16
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti20
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti40
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti60
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti80
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti120
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedStti240
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedSpare2
	SpsConfigulSttiR15SetupSemipersistschedintervalulSttiR15EnumeratedSpare1
)
