package ies

import "rrc/utils"

// SRS-AllPosResourcesRRC-Inactive-r17-srs-PosResourcesRRC-Inactive-r17-dummy2 ::= ENUMERATED
type SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2 struct {
	Value utils.ENUMERATED
}

const (
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedNothing = iota
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN1
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN2
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN3
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN4
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN5
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN6
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN8
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN10
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN12
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy2EnumeratedN14
)
