package ies

import "rrc/utils"

// SRS-AllPosResourcesRRC-Inactive-r17-srs-PosResourcesRRC-Inactive-r17-maxNumberSRS-PosResourcesPerBWP-r17 ::= ENUMERATED
type SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17 struct {
	Value utils.ENUMERATED
}

const (
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedNothing = iota
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedN1
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedN2
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedN4
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedN8
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedN16
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedN32
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesperbwpR17EnumeratedN64
)
