package ies

import "rrc/utils"

// SRS-AllPosResourcesRRC-Inactive-r17-srs-PosResourcesRRC-Inactive-r17-maxNumberSRS-PosResourceSetPerBWP-r17 ::= ENUMERATED
type SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17 struct {
	Value utils.ENUMERATED
}

const (
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17EnumeratedNothing = iota
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17EnumeratedN1
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17EnumeratedN2
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17EnumeratedN4
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17EnumeratedN8
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17EnumeratedN12
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsPosresourcesetperbwpR17EnumeratedN16
)
