package ies

import "rrc/utils"

// SRS-AllPosResourcesRRC-Inactive-r17-srs-PosResourcesRRC-Inactive-r17-maxNumberPeriodicSRS-PosResourcesPerBWP-r17 ::= ENUMERATED
type SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17 struct {
	Value utils.ENUMERATED
}

const (
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedNothing = iota
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedN1
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedN2
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedN4
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedN8
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedN16
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedN32
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpR17EnumeratedN64
)
