package ies

import "rrc/utils"

// SRS-AllPosResourcesRRC-Inactive-r17-srs-PosResourcesRRC-Inactive-r17-dummy1 ::= ENUMERATED
type SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1 struct {
	Value utils.ENUMERATED
}

const (
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedNothing = iota
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedN1
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedN2
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedN4
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedN8
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedN16
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedN32
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17Dummy1EnumeratedN64
)
