package ies

import "rrc/utils"

// SRS-AllPosResourcesRRC-Inactive-r17-srs-PosResourcesRRC-Inactive-r17-maxNumberSRS-ResourcesPerBWP-PerSlot-r17 ::= ENUMERATED
type SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17 struct {
	Value utils.ENUMERATED
}

const (
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedNothing = iota
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN1
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN2
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN3
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN4
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN5
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN6
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN8
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN10
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN12
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumbersrsResourcesperbwpPerslotR17EnumeratedN14
)
