package ies

import "rrc/utils"

// SRS-AllPosResourcesRRC-Inactive-r17-srs-PosResourcesRRC-Inactive-r17-maxNumberPeriodicSRS-PosResourcesPerBWP-PerSlot-r17 ::= ENUMERATED
type SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17 struct {
	Value utils.ENUMERATED
}

const (
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedNothing = iota
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN1
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN2
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN3
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN4
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN5
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN6
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN8
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN10
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN12
	SrsAllposresourcesrrcInactiveR17SrsPosresourcesrrcInactiveR17MaxnumberperiodicsrsPosresourcesperbwpPerslotR17EnumeratedN14
)
