package ies

import "rrc/utils"

// SRS-ConfigAdd-r16-srs-RepNumAdd-r16 ::= ENUMERATED
type SrsConfigaddR16SrsRepnumaddR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsConfigaddR16SrsRepnumaddR16EnumeratedNothing = iota
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN1
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN2
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN3
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN4
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN6
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN7
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN8
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN9
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN12
	SrsConfigaddR16SrsRepnumaddR16EnumeratedN13
)
