package ies

import "rrc/utils"

// SRS-CapabilityPerBandPair-r14-retuningInfo-rf-RetuningTimeDL-r14 ::= ENUMERATED
type SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14 struct {
	Value utils.ENUMERATED
}

const (
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedNothing = iota
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN0
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN0dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN1
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN1dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN2
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN2dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN3
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN3dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN4
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN4dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN5dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN6
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN6dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedN7
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimedlR14EnumeratedSpare1
)
