package ies

import "rrc/utils"

// SRS-CapabilityPerBandPair-r14-retuningInfo-rf-RetuningTimeUL-r14 ::= ENUMERATED
type SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14 struct {
	Value utils.ENUMERATED
}

const (
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedNothing = iota
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN0
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN0dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN1
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN1dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN2
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN2dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN3
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN3dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN4
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN4dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN5dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN6
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN6dot5
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedN7
	SrsCapabilityperbandpairR14RetuninginfoRfRetuningtimeulR14EnumeratedSpare1
)
