package ies

import "rrc/utils"

// SRS-PosResourceSP-r16-maxNumberSP-SRS-PosResourcesPerBWP-PerSlot-r16 ::= ENUMERATED
type SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedNothing = iota
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN1
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN2
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN3
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN4
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN5
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN6
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN8
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN10
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN12
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpPerslotR16EnumeratedN14
)
