package ies

import "rrc/utils"

// SRS-PosResourceAP-r16-maxNumberAP-SRS-PosResourcesPerBWP-r16 ::= ENUMERATED
type SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedNothing = iota
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedN1
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedN2
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedN4
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedN8
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedN16
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedN32
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpR16EnumeratedN64
)
