package ies

import "rrc/utils"

// SRS-PosResources-r16-maxNumberSRS-PosResourcesPerBWP-r16 ::= ENUMERATED
type SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedNothing = iota
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedN1
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedN2
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedN4
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedN8
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedN16
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedN32
	SrsPosresourcesR16MaxnumbersrsPosresourcesperbwpR16EnumeratedN64
)
