package ies

import "rrc/utils"

// SRS-PosResources-r16-maxNumberSRS-ResourcesPerBWP-PerSlot-r16 ::= ENUMERATED
type SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedNothing = iota
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN1
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN2
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN3
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN4
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN5
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN6
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN8
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN10
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN12
	SrsPosresourcesR16MaxnumbersrsResourcesperbwpPerslotR16EnumeratedN14
)
