package ies

import "rrc/utils"

// SRS-PosResourceAP-r16-maxNumberAP-SRS-PosResourcesPerBWP-PerSlot-r16 ::= ENUMERATED
type SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedNothing = iota
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN1
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN2
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN3
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN4
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN5
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN6
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN8
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN10
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN12
	SrsPosresourceapR16MaxnumberapSrsPosresourcesperbwpPerslotR16EnumeratedN14
)
