package ies

import "rrc/utils"

// SRS-PosResources-r16-maxNumberPeriodicSRS-PosResourcesPerBWP-r16 ::= ENUMERATED
type SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedNothing = iota
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedN1
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedN2
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedN4
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedN8
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedN16
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedN32
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpR16EnumeratedN64
)
