package ies

import "rrc/utils"

// SRS-PosResources-r16-maxNumberPeriodicSRS-PosResourcesPerBWP-PerSlot-r16 ::= ENUMERATED
type SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedNothing = iota
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN1
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN2
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN3
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN4
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN5
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN6
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN8
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN10
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN12
	SrsPosresourcesR16MaxnumberperiodicsrsPosresourcesperbwpPerslotR16EnumeratedN14
)
