package ies

import "rrc/utils"

// SRS-PosResources-r16-maxNumberSRS-PosResourceSetPerBWP-r16 ::= ENUMERATED
type SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16EnumeratedNothing = iota
	SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16EnumeratedN1
	SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16EnumeratedN2
	SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16EnumeratedN4
	SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16EnumeratedN8
	SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16EnumeratedN12
	SrsPosresourcesR16MaxnumbersrsPosresourcesetperbwpR16EnumeratedN16
)
