package ies

import "rrc/utils"

// SRS-PosResourceSP-r16-maxNumberSP-SRS-PosResourcesPerBWP-r16 ::= ENUMERATED
type SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16 struct {
	Value utils.ENUMERATED
}

const (
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedNothing = iota
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedN1
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedN2
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedN4
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedN8
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedN16
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedN32
	SrsPosresourcespR16MaxnumberspSrsPosresourcesperbwpR16EnumeratedN64
)
