package ies

import "rrc/utils"

// SRS-SwitchingTimeEUTRA-switchingTimeDL ::= ENUMERATED
type SrsSwitchingtimeeutraSwitchingtimedl struct {
	Value utils.ENUMERATED
}

const (
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedNothing = iota
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN0
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN0dot5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN1
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN1dot5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN2
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN2dot5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN3
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN3dot5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN4
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN4dot5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN5dot5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN6
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN6dot5
	SrsSwitchingtimeeutraSwitchingtimedlEnumeratedN7
)
