package ies

import "rrc/utils"

// SRS-SwitchingTimeNR-switchingTimeDL ::= ENUMERATED
type SrsSwitchingtimenrSwitchingtimedl struct {
	Value utils.ENUMERATED
}

const (
	SrsSwitchingtimenrSwitchingtimedlEnumeratedNothing = iota
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN0us
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN30us
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN100us
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN140us
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN200us
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN300us
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN500us
	SrsSwitchingtimenrSwitchingtimedlEnumeratedN900us
)
