package ies

import "rrc/utils"

// SSB-Configuration-r16-ssb-Periodicity-r16 ::= ENUMERATED
type SsbConfigurationR16SsbPeriodicityR16 struct {
	Value utils.ENUMERATED
}

const (
	SsbConfigurationR16SsbPeriodicityR16EnumeratedNothing = iota
	SsbConfigurationR16SsbPeriodicityR16EnumeratedMs5
	SsbConfigurationR16SsbPeriodicityR16EnumeratedMs10
	SsbConfigurationR16SsbPeriodicityR16EnumeratedMs20
	SsbConfigurationR16SsbPeriodicityR16EnumeratedMs40
	SsbConfigurationR16SsbPeriodicityR16EnumeratedMs80
	SsbConfigurationR16SsbPeriodicityR16EnumeratedMs160
	SsbConfigurationR16SsbPeriodicityR16EnumeratedSpare2
	SsbConfigurationR16SsbPeriodicityR16EnumeratedSpare1
)
