package ies

import "rrc/utils"

// SSB-MTC-AdditionalPCI-r17-periodicity-r17 ::= ENUMERATED
type SsbMtcAdditionalpciR17PeriodicityR17 struct {
	Value utils.ENUMERATED
}

const (
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedNothing = iota
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedMs5
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedMs10
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedMs20
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedMs40
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedMs80
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedMs160
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedSpare2
	SsbMtcAdditionalpciR17PeriodicityR17EnumeratedSpare1
)
