package ies

import "rrc/utils"

// SupportedCSI-RS-Resource-maxNumberTxPortsPerResource ::= ENUMERATED
type SupportedcsiRsResourceMaxnumbertxportsperresource struct {
	Value utils.ENUMERATED
}

const (
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedNothing = iota
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedP2
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedP4
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedP8
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedP12
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedP16
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedP24
	SupportedcsiRsResourceMaxnumbertxportsperresourceEnumeratedP32
)
