package ies

import "rrc/utils"

// SupportedBandUTRA-TDD128 ::= utils.ENUMERATED // Extensible
type SupportedbandutraTdd128 struct {
	Value utils.ENUMERATED
}

const (
	SupportedbandutraTdd128EnumeratedNothing = iota
	SupportedbandutraTdd128EnumeratedA
	SupportedbandutraTdd128EnumeratedB
	SupportedbandutraTdd128EnumeratedC
	SupportedbandutraTdd128EnumeratedD
	SupportedbandutraTdd128EnumeratedE
	SupportedbandutraTdd128EnumeratedF
	SupportedbandutraTdd128EnumeratedG
	SupportedbandutraTdd128EnumeratedH
	SupportedbandutraTdd128EnumeratedI
	SupportedbandutraTdd128EnumeratedJ
	SupportedbandutraTdd128EnumeratedK
	SupportedbandutraTdd128EnumeratedL
	SupportedbandutraTdd128EnumeratedM
	SupportedbandutraTdd128EnumeratedN
	SupportedbandutraTdd128EnumeratedO
	SupportedbandutraTdd128EnumeratedP
)
