package ies

import "rrc/utils"

// SupportedBandGERAN ::= utils.ENUMERATED // Extensible
type Supportedbandgeran struct {
	Value utils.ENUMERATED
}

const (
	SupportedbandgeranEnumeratedNothing = iota
	SupportedbandgeranEnumeratedGsm450
	SupportedbandgeranEnumeratedGsm480
	SupportedbandgeranEnumeratedGsm710
	SupportedbandgeranEnumeratedGsm750
	SupportedbandgeranEnumeratedGsm810
	SupportedbandgeranEnumeratedGsm850
	SupportedbandgeranEnumeratedGsm900p
	SupportedbandgeranEnumeratedGsm900e
	SupportedbandgeranEnumeratedGsm900r
	SupportedbandgeranEnumeratedGsm1800
	SupportedbandgeranEnumeratedGsm1900
	SupportedbandgeranEnumeratedSpare5
	SupportedbandgeranEnumeratedSpare4
	SupportedbandgeranEnumeratedSpare3
	SupportedbandgeranEnumeratedSpare2
	SupportedbandgeranEnumeratedSpare1
)
