package ies

import "rrc/utils"

// SystemInformationBlockType1-v1310-IEs-bandwidthReducedAccessRelatedInfo-r13-si-WindowLength-BR-r13 ::= ENUMERATED
type Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedNothing = iota
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedMs20
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedMs40
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedMs60
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedMs80
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedMs120
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedMs160
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedMs200
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiWindowlengthBrR13EnumeratedSpare
)
