package ies

import "rrc/utils"

// SystemInformationBlockType1-NB-nrs-CRS-PowerOffset-r13 ::= ENUMERATED
type Systeminformationblocktype1NbNrsCrsPoweroffsetR13 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedNothing = iota
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb_6
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb_4dot77
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb_3
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb_1dot77
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb0
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb1
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb1dot23
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb2
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb3
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb4
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb4dot23
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb5
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb6
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb7
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb8
	Systeminformationblocktype1NbNrsCrsPoweroffsetR13EnumeratedDb9
)
