package ies

import "rrc/utils"

// SystemInformationBlockType1-v1530-IEs-cellAccessRelatedInfo-5GC-r15-cellBarred-5GC-CRS-r15 ::= ENUMERATED
type Systeminformationblocktype1V1530IesCellaccessrelatedinfo5gcR15Cellbarred5gcCrsR15 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1V1530IesCellaccessrelatedinfo5gcR15Cellbarred5gcCrsR15EnumeratedNothing = iota
	Systeminformationblocktype1V1530IesCellaccessrelatedinfo5gcR15Cellbarred5gcCrsR15EnumeratedBarred
	Systeminformationblocktype1V1530IesCellaccessrelatedinfo5gcR15Cellbarred5gcCrsR15EnumeratedNotbarred
)
