package ies

import "rrc/utils"

// SystemInformationBlockType1-si-WindowLength ::= ENUMERATED
type Systeminformationblocktype1SiWindowlength struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1SiWindowlengthEnumeratedNothing = iota
	Systeminformationblocktype1SiWindowlengthEnumeratedMs1
	Systeminformationblocktype1SiWindowlengthEnumeratedMs2
	Systeminformationblocktype1SiWindowlengthEnumeratedMs5
	Systeminformationblocktype1SiWindowlengthEnumeratedMs10
	Systeminformationblocktype1SiWindowlengthEnumeratedMs15
	Systeminformationblocktype1SiWindowlengthEnumeratedMs20
	Systeminformationblocktype1SiWindowlengthEnumeratedMs40
)
