package ies

import "rrc/utils"

// SystemInformationBlockType1-NB-si-WindowLength-r13 ::= ENUMERATED
type Systeminformationblocktype1NbSiWindowlengthR13 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedNothing = iota
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedMs160
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedMs320
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedMs480
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedMs640
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedMs960
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedMs1280
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedMs1600
	Systeminformationblocktype1NbSiWindowlengthR13EnumeratedSpare1
)
