package ies

import "rrc/utils"

// SystemInformationBlockType2-freqInfo-ul-Bandwidth ::= ENUMERATED
type Systeminformationblocktype2FreqinfoUlBandwidth struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype2FreqinfoUlBandwidthEnumeratedNothing = iota
	Systeminformationblocktype2FreqinfoUlBandwidthEnumeratedN6
	Systeminformationblocktype2FreqinfoUlBandwidthEnumeratedN15
	Systeminformationblocktype2FreqinfoUlBandwidthEnumeratedN25
	Systeminformationblocktype2FreqinfoUlBandwidthEnumeratedN50
	Systeminformationblocktype2FreqinfoUlBandwidthEnumeratedN75
	Systeminformationblocktype2FreqinfoUlBandwidthEnumeratedN100
)
