package ies

import "rrc/utils"

// SystemInformationBlockType3-NB-r13-cellReselectionInfoCommon-r13-q-Hyst-r13 ::= ENUMERATED
type Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedNothing = iota
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb0
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb1
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb2
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb3
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb4
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb5
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb6
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb8
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb10
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb12
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb14
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb16
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb18
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb20
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb22
	Systeminformationblocktype3NbR13CellreselectioninfocommonR13QHystR13EnumeratedDb24
)
