package ies

import "rrc/utils"

// SystemInformationBlockType1-v1320-IEs-freqHoppingParametersDL-r13-interval-DLHoppingConfigCommonModeA-r13 ::= CHOICE
const (
	Systeminformationblocktype1V1320IesFreqhoppingparametersdlR13IntervalDlhoppingconfigcommonmodeaR13ChoiceNothing = iota
	Systeminformationblocktype1V1320IesFreqhoppingparametersdlR13IntervalDlhoppingconfigcommonmodeaR13ChoiceIntervalFddR13
	Systeminformationblocktype1V1320IesFreqhoppingparametersdlR13IntervalDlhoppingconfigcommonmodeaR13ChoiceIntervalTddR13
)

type Systeminformationblocktype1V1320IesFreqhoppingparametersdlR13IntervalDlhoppingconfigcommonmodeaR13 struct {
	Choice         uint64
	IntervalFddR13 *utils.ENUMERATED
	IntervalTddR13 *utils.ENUMERATED
}
