package ies

import "rrc/utils"

// SystemInformationBlockType1-NB-cellAccessRelatedInfo-r13-cellBarred-r13 ::= ENUMERATED
type Systeminformationblocktype1NbCellaccessrelatedinfoR13CellbarredR13 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1NbCellaccessrelatedinfoR13CellbarredR13EnumeratedNothing = iota
	Systeminformationblocktype1NbCellaccessrelatedinfoR13CellbarredR13EnumeratedBarred
	Systeminformationblocktype1NbCellaccessrelatedinfoR13CellbarredR13EnumeratedNotbarred
)
