package ies

import "rrc/utils"

// SystemInformationBlockType3-cellReselectionInfoCommon-speedStateReselectionPars-q-HystSF-sf-Medium ::= ENUMERATED
type Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMedium struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedNothing = iota
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb_6
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb_4
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb_2
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfMediumEnumeratedDb0
)
