package ies

import "rrc/utils"

// SystemInformationBlockType3-cellReselectionInfoCommon-q-Hyst ::= ENUMERATED
type Systeminformationblocktype3CellreselectioninfocommonQHyst struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedNothing = iota
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb0
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb1
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb2
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb3
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb4
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb5
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb6
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb8
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb10
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb12
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb14
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb16
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb18
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb20
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb22
	Systeminformationblocktype3CellreselectioninfocommonQHystEnumeratedDb24
)
