package ies

import "rrc/utils"

// SystemInformationBlockType1-NB-v1610-cellAccessRelatedInfo-5GC-r16-cellBarred-5GC-r16 ::= ENUMERATED
type Systeminformationblocktype1NbV1610Cellaccessrelatedinfo5gcR16Cellbarred5gcR16 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1NbV1610Cellaccessrelatedinfo5gcR16Cellbarred5gcR16EnumeratedNothing = iota
	Systeminformationblocktype1NbV1610Cellaccessrelatedinfo5gcR16Cellbarred5gcR16EnumeratedBarred
	Systeminformationblocktype1NbV1610Cellaccessrelatedinfo5gcR16Cellbarred5gcR16EnumeratedNotbarred
)
