package ies

import "rrc/utils"

// SystemInformationBlockType1-v1310-IEs-bandwidthReducedAccessRelatedInfo-r13-si-RepetitionPattern-r13 ::= ENUMERATED
type Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiRepetitionpatternR13 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiRepetitionpatternR13EnumeratedNothing = iota
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiRepetitionpatternR13EnumeratedEveryrf
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiRepetitionpatternR13EnumeratedEvery2ndrf
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiRepetitionpatternR13EnumeratedEvery4thrf
	Systeminformationblocktype1V1310IesBandwidthreducedaccessrelatedinfoR13SiRepetitionpatternR13EnumeratedEvery8thrf
)
