package ies

import "rrc/utils"

// SystemInformationBlockType3-cellReselectionInfoCommon-speedStateReselectionPars-q-HystSF-sf-High ::= ENUMERATED
type Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfHigh struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfHighEnumeratedNothing = iota
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfHighEnumeratedDb_6
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfHighEnumeratedDb_4
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfHighEnumeratedDb_2
	Systeminformationblocktype3CellreselectioninfocommonSpeedstatereselectionparsQHystsfSfHighEnumeratedDb0
)
