package ies

import "rrc/utils"

// SystemInformationBlockType1-NB-eutraControlRegionSize-r13 ::= ENUMERATED
type Systeminformationblocktype1NbEutracontrolregionsizeR13 struct {
	Value utils.ENUMERATED
}

const (
	Systeminformationblocktype1NbEutracontrolregionsizeR13EnumeratedNothing = iota
	Systeminformationblocktype1NbEutracontrolregionsizeR13EnumeratedN1
	Systeminformationblocktype1NbEutracontrolregionsizeR13EnumeratedN2
	Systeminformationblocktype1NbEutracontrolregionsizeR13EnumeratedN3
)
