package ies

import "rrc/utils"

// TDD-Config-specialSubframePatterns ::= ENUMERATED
type TddConfigSpecialsubframepatterns struct {
	Value utils.ENUMERATED
}

const (
	TddConfigSpecialsubframepatternsEnumeratedNothing = iota
	TddConfigSpecialsubframepatternsEnumeratedSsp0
	TddConfigSpecialsubframepatternsEnumeratedSsp1
	TddConfigSpecialsubframepatternsEnumeratedSsp2
	TddConfigSpecialsubframepatternsEnumeratedSsp3
	TddConfigSpecialsubframepatternsEnumeratedSsp4
	TddConfigSpecialsubframepatternsEnumeratedSsp5
	TddConfigSpecialsubframepatternsEnumeratedSsp6
	TddConfigSpecialsubframepatternsEnumeratedSsp7
	TddConfigSpecialsubframepatternsEnumeratedSsp8
)
