package ies

import "rrc/utils"

// TDD-Config-NB-r15-specialSubframePatterns-r15 ::= ENUMERATED
type TddConfigNbR15SpecialsubframepatternsR15 struct {
	Value utils.ENUMERATED
}

const (
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedNothing = iota
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp0
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp1
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp2
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp3
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp4
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp5
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp6
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp7
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp8
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp9
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp10
	TddConfigNbR15SpecialsubframepatternsR15EnumeratedSsp10_Crs_Lessdwpts
)
