package ies

import "rrc/utils"

// TDD-UL-DL-Pattern-dl-UL-TransmissionPeriodicity ::= ENUMERATED
type TddUlDlPatternDlUlTransmissionperiodicity struct {
	Value utils.ENUMERATED
}

const (
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedNothing = iota
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs0p5
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs0p625
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs1
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs1p25
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs2
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs2p5
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs5
	TddUlDlPatternDlUlTransmissionperiodicityEnumeratedMs10
)
