package ies

import "rrc/utils"

// TDM-AssistanceInfo-r11-drx-AssistanceInfo-r11-drx-CycleLength-r11 ::= ENUMERATED
type TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11 struct {
	Value utils.ENUMERATED
}

const (
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedNothing = iota
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSf40
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSf64
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSf80
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSf128
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSf160
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSf256
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSpare2
	TdmAssistanceinfoR11DrxAssistanceinfoR11DrxCyclelengthR11EnumeratedSpare1
)
