package ies

import "rrc/utils"

// T-PollRetransmit ::= ENUMERATED
type TPollretransmit struct {
	Value utils.ENUMERATED
}

const (
	TPollretransmitEnumeratedNothing = iota
	TPollretransmitEnumeratedMs5
	TPollretransmitEnumeratedMs10
	TPollretransmitEnumeratedMs15
	TPollretransmitEnumeratedMs20
	TPollretransmitEnumeratedMs25
	TPollretransmitEnumeratedMs30
	TPollretransmitEnumeratedMs35
	TPollretransmitEnumeratedMs40
	TPollretransmitEnumeratedMs45
	TPollretransmitEnumeratedMs50
	TPollretransmitEnumeratedMs55
	TPollretransmitEnumeratedMs60
	TPollretransmitEnumeratedMs65
	TPollretransmitEnumeratedMs70
	TPollretransmitEnumeratedMs75
	TPollretransmitEnumeratedMs80
	TPollretransmitEnumeratedMs85
	TPollretransmitEnumeratedMs90
	TPollretransmitEnumeratedMs95
	TPollretransmitEnumeratedMs100
	TPollretransmitEnumeratedMs105
	TPollretransmitEnumeratedMs110
	TPollretransmitEnumeratedMs115
	TPollretransmitEnumeratedMs120
	TPollretransmitEnumeratedMs125
	TPollretransmitEnumeratedMs130
	TPollretransmitEnumeratedMs135
	TPollretransmitEnumeratedMs140
	TPollretransmitEnumeratedMs145
	TPollretransmitEnumeratedMs150
	TPollretransmitEnumeratedMs155
	TPollretransmitEnumeratedMs160
	TPollretransmitEnumeratedMs165
	TPollretransmitEnumeratedMs170
	TPollretransmitEnumeratedMs175
	TPollretransmitEnumeratedMs180
	TPollretransmitEnumeratedMs185
	TPollretransmitEnumeratedMs190
	TPollretransmitEnumeratedMs195
	TPollretransmitEnumeratedMs200
	TPollretransmitEnumeratedMs205
	TPollretransmitEnumeratedMs210
	TPollretransmitEnumeratedMs215
	TPollretransmitEnumeratedMs220
	TPollretransmitEnumeratedMs225
	TPollretransmitEnumeratedMs230
	TPollretransmitEnumeratedMs235
	TPollretransmitEnumeratedMs240
	TPollretransmitEnumeratedMs245
	TPollretransmitEnumeratedMs250
	TPollretransmitEnumeratedMs300
	TPollretransmitEnumeratedMs350
	TPollretransmitEnumeratedMs400
	TPollretransmitEnumeratedMs450
	TPollretransmitEnumeratedMs500
	TPollretransmitEnumeratedMs800_V1310
	TPollretransmitEnumeratedMs1000_V1310
	TPollretransmitEnumeratedMs2000_V1310
	TPollretransmitEnumeratedMs4000_V1310
	TPollretransmitEnumeratedSpare5
	TPollretransmitEnumeratedSpare4
	TPollretransmitEnumeratedSpare3
	TPollretransmitEnumeratedSpare2
	TPollretransmitEnumeratedSpare1
)
