package ies

import "rrc/utils"

// T-StatusProhibit ::= ENUMERATED
type TStatusprohibit struct {
	Value utils.ENUMERATED
}

const (
	TStatusprohibitEnumeratedNothing = iota
	TStatusprohibitEnumeratedMs0
	TStatusprohibitEnumeratedMs5
	TStatusprohibitEnumeratedMs10
	TStatusprohibitEnumeratedMs15
	TStatusprohibitEnumeratedMs20
	TStatusprohibitEnumeratedMs25
	TStatusprohibitEnumeratedMs30
	TStatusprohibitEnumeratedMs35
	TStatusprohibitEnumeratedMs40
	TStatusprohibitEnumeratedMs45
	TStatusprohibitEnumeratedMs50
	TStatusprohibitEnumeratedMs55
	TStatusprohibitEnumeratedMs60
	TStatusprohibitEnumeratedMs65
	TStatusprohibitEnumeratedMs70
	TStatusprohibitEnumeratedMs75
	TStatusprohibitEnumeratedMs80
	TStatusprohibitEnumeratedMs85
	TStatusprohibitEnumeratedMs90
	TStatusprohibitEnumeratedMs95
	TStatusprohibitEnumeratedMs100
	TStatusprohibitEnumeratedMs105
	TStatusprohibitEnumeratedMs110
	TStatusprohibitEnumeratedMs115
	TStatusprohibitEnumeratedMs120
	TStatusprohibitEnumeratedMs125
	TStatusprohibitEnumeratedMs130
	TStatusprohibitEnumeratedMs135
	TStatusprohibitEnumeratedMs140
	TStatusprohibitEnumeratedMs145
	TStatusprohibitEnumeratedMs150
	TStatusprohibitEnumeratedMs155
	TStatusprohibitEnumeratedMs160
	TStatusprohibitEnumeratedMs165
	TStatusprohibitEnumeratedMs170
	TStatusprohibitEnumeratedMs175
	TStatusprohibitEnumeratedMs180
	TStatusprohibitEnumeratedMs185
	TStatusprohibitEnumeratedMs190
	TStatusprohibitEnumeratedMs195
	TStatusprohibitEnumeratedMs200
	TStatusprohibitEnumeratedMs205
	TStatusprohibitEnumeratedMs210
	TStatusprohibitEnumeratedMs215
	TStatusprohibitEnumeratedMs220
	TStatusprohibitEnumeratedMs225
	TStatusprohibitEnumeratedMs230
	TStatusprohibitEnumeratedMs235
	TStatusprohibitEnumeratedMs240
	TStatusprohibitEnumeratedMs245
	TStatusprohibitEnumeratedMs250
	TStatusprohibitEnumeratedMs300
	TStatusprohibitEnumeratedMs350
	TStatusprohibitEnumeratedMs400
	TStatusprohibitEnumeratedMs450
	TStatusprohibitEnumeratedMs500
	TStatusprohibitEnumeratedMs800_V1310
	TStatusprohibitEnumeratedMs1000_V1310
	TStatusprohibitEnumeratedMs1200_V1310
	TStatusprohibitEnumeratedMs1600_V1310
	TStatusprohibitEnumeratedMs2000_V1310
	TStatusprohibitEnumeratedMs2400_V1310
	TStatusprohibitEnumeratedSpare2
	TStatusprohibitEnumeratedSpare1
)
