package ies

import "rrc/utils"

// UAC-BarringPerCat-NB-r16-uac-BarringFactor-r16 ::= ENUMERATED
type UacBarringpercatNbR16UacBarringfactorR16 struct {
	Value utils.ENUMERATED
}

const (
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedNothing = iota
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP00
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP05
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP10
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP15
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP20
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP25
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP30
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP40
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP50
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP60
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP70
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP75
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP80
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP85
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP90
	UacBarringpercatNbR16UacBarringfactorR16EnumeratedP95
)
