package ies

import "rrc/utils"

// UAC-BarringInfoSet-r15-uac-BarringFactor-r15 ::= ENUMERATED
type UacBarringinfosetR15UacBarringfactorR15 struct {
	Value utils.ENUMERATED
}

const (
	UacBarringinfosetR15UacBarringfactorR15EnumeratedNothing = iota
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP00
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP05
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP10
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP15
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP20
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP25
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP30
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP40
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP50
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP60
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP70
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP75
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP80
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP85
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP90
	UacBarringinfosetR15UacBarringfactorR15EnumeratedP95
)
