package ies

import "rrc/utils"

// UAC-BarringInfoSet-r15-uac-BarringTime-r15 ::= ENUMERATED
type UacBarringinfosetR15UacBarringtimeR15 struct {
	Value utils.ENUMERATED
}

const (
	UacBarringinfosetR15UacBarringtimeR15EnumeratedNothing = iota
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS4
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS8
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS16
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS32
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS64
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS128
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS256
	UacBarringinfosetR15UacBarringtimeR15EnumeratedS512
)
