package ies

import "rrc/utils"

// UEAssistanceInformation-v1700-IEs-scg-DeactivationPreference-r17 ::= ENUMERATED
type UeassistanceinformationV1700IesScgDeactivationpreferenceR17 struct {
	Value utils.ENUMERATED
}

const (
	UeassistanceinformationV1700IesScgDeactivationpreferenceR17EnumeratedNothing = iota
	UeassistanceinformationV1700IesScgDeactivationpreferenceR17EnumeratedScgdeactivationpreferred
	UeassistanceinformationV1700IesScgDeactivationpreferenceR17EnumeratedNopreference
)
