package ies

import "rrc/utils"

// UEPositioningAssistanceInfo-v1720-IEs-ue-TxTEG-TimingErrorMarginValue-r17 ::= ENUMERATED
type UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17 struct {
	Value utils.ENUMERATED
}

const (
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedNothing = iota
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc0
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc2
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc4
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc6
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc8
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc12
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc16
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc20
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc24
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc32
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc40
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc48
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc56
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc64
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc72
	UepositioningassistanceinfoV1720IesUeTxtegTimingerrormarginvalueR17EnumeratedTc80
)
