package ies

// UERadioPagingInformation-v15e0-IEs ::= SEQUENCE
type UeradiopaginginformationV15e0 struct {
	DlSchedulingoffsetPdschTypeaFddFr1 *UeradiopaginginformationV15e0IesDlSchedulingoffsetPdschTypeaFddFr1
	DlSchedulingoffsetPdschTypeaTddFr1 *UeradiopaginginformationV15e0IesDlSchedulingoffsetPdschTypeaTddFr1
	DlSchedulingoffsetPdschTypeaTddFr2 *UeradiopaginginformationV15e0IesDlSchedulingoffsetPdschTypeaTddFr2
	DlSchedulingoffsetPdschTypebFddFr1 *UeradiopaginginformationV15e0IesDlSchedulingoffsetPdschTypebFddFr1
	DlSchedulingoffsetPdschTypebTddFr1 *UeradiopaginginformationV15e0IesDlSchedulingoffsetPdschTypebTddFr1
	DlSchedulingoffsetPdschTypebTddFr2 *UeradiopaginginformationV15e0IesDlSchedulingoffsetPdschTypebTddFr2
	Noncriticalextension               *UeradiopaginginformationV1700
}
