package ies

import "rrc/utils"

// UL-DataSplitThreshold ::= ENUMERATED
type UlDatasplitthreshold struct {
	Value utils.ENUMERATED
}

const (
	UlDatasplitthresholdEnumeratedNothing = iota
	UlDatasplitthresholdEnumeratedB0
	UlDatasplitthresholdEnumeratedB100
	UlDatasplitthresholdEnumeratedB200
	UlDatasplitthresholdEnumeratedB400
	UlDatasplitthresholdEnumeratedB800
	UlDatasplitthresholdEnumeratedB1600
	UlDatasplitthresholdEnumeratedB3200
	UlDatasplitthresholdEnumeratedB6400
	UlDatasplitthresholdEnumeratedB12800
	UlDatasplitthresholdEnumeratedB25600
	UlDatasplitthresholdEnumeratedB51200
	UlDatasplitthresholdEnumeratedB102400
	UlDatasplitthresholdEnumeratedB204800
	UlDatasplitthresholdEnumeratedB409600
	UlDatasplitthresholdEnumeratedB819200
	UlDatasplitthresholdEnumeratedB1228800
	UlDatasplitthresholdEnumeratedB1638400
	UlDatasplitthresholdEnumeratedB2457600
	UlDatasplitthresholdEnumeratedB3276800
	UlDatasplitthresholdEnumeratedB4096000
	UlDatasplitthresholdEnumeratedB4915200
	UlDatasplitthresholdEnumeratedB5734400
	UlDatasplitthresholdEnumeratedB6553600
	UlDatasplitthresholdEnumeratedInfinity
	UlDatasplitthresholdEnumeratedSpare8
	UlDatasplitthresholdEnumeratedSpare7
	UlDatasplitthresholdEnumeratedSpare6
	UlDatasplitthresholdEnumeratedSpare5
	UlDatasplitthresholdEnumeratedSpare4
	UlDatasplitthresholdEnumeratedSpare3
	UlDatasplitthresholdEnumeratedSpare2
	UlDatasplitthresholdEnumeratedSpare1
)
