package ies

import "rrc/utils"

// UL-DelayConfig-r13-setup-delayThreshold-r13 ::= ENUMERATED
type UlDelayconfigR13SetupDelaythresholdR13 struct {
	Value utils.ENUMERATED
}

const (
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedNothing = iota
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs30
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs40
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs50
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs60
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs70
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs80
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs90
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs100
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs150
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs300
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs500
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedMs750
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedSpare4
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedSpare3
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedSpare2
	UlDelayconfigR13SetupDelaythresholdR13EnumeratedSpare1
)
