package ies

import "rrc/utils"

// UplinkPowerControlDedicatedSCell-r10-pathlossReferenceLinking-r10 ::= ENUMERATED
type UplinkpowercontroldedicatedscellR10PathlossreferencelinkingR10 struct {
	Value utils.ENUMERATED
}

const (
	UplinkpowercontroldedicatedscellR10PathlossreferencelinkingR10EnumeratedNothing = iota
	UplinkpowercontroldedicatedscellR10PathlossreferencelinkingR10EnumeratedPcell
	UplinkpowercontroldedicatedscellR10PathlossreferencelinkingR10EnumeratedScell
)
