package ies

import "rrc/utils"

// UplinkTxSwitchingBandParameters-v1700-uplinkTxSwitching2T2T-PUSCH-TransCoherence-r17 ::= ENUMERATED
type UplinktxswitchingbandparametersV1700Uplinktxswitching2t2tPuschTranscoherenceR17 struct {
	Value utils.ENUMERATED
}

const (
	UplinktxswitchingbandparametersV1700Uplinktxswitching2t2tPuschTranscoherenceR17EnumeratedNothing = iota
	UplinktxswitchingbandparametersV1700Uplinktxswitching2t2tPuschTranscoherenceR17EnumeratedNoncoherent
	UplinktxswitchingbandparametersV1700Uplinktxswitching2t2tPuschTranscoherenceR17EnumeratedFullcoherent
)
