package ies

import "rrc/utils"

// UplinkPowerControlCommon-NB-r13-alpha-r13 ::= ENUMERATED
type UplinkpowercontrolcommonNbR13AlphaR13 struct {
	Value utils.ENUMERATED
}

const (
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedNothing = iota
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl0
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl04
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl05
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl06
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl07
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl08
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl09
	UplinkpowercontrolcommonNbR13AlphaR13EnumeratedAl1
)
