package ies

import "rrc/utils"

// UplinkPowerControlCommon-v1020-deltaF-PUCCH-Format1bCS-r10 ::= ENUMERATED
type UplinkpowercontrolcommonV1020DeltafPucchFormat1bcsR10 struct {
	Value utils.ENUMERATED
}

const (
	UplinkpowercontrolcommonV1020DeltafPucchFormat1bcsR10EnumeratedNothing = iota
	UplinkpowercontrolcommonV1020DeltafPucchFormat1bcsR10EnumeratedDeltaf1
	UplinkpowercontrolcommonV1020DeltafPucchFormat1bcsR10EnumeratedDeltaf2
	UplinkpowercontrolcommonV1020DeltafPucchFormat1bcsR10EnumeratedSpare2
	UplinkpowercontrolcommonV1020DeltafPucchFormat1bcsR10EnumeratedSpare1
)
