package ies

import "rrc/utils"

// UplinkPowerControlCommonPSCell-r12-deltaF-PUCCH-Format1bCS-r12 ::= ENUMERATED
type UplinkpowercontrolcommonpscellR12DeltafPucchFormat1bcsR12 struct {
	Value utils.ENUMERATED
}

const (
	UplinkpowercontrolcommonpscellR12DeltafPucchFormat1bcsR12EnumeratedNothing = iota
	UplinkpowercontrolcommonpscellR12DeltafPucchFormat1bcsR12EnumeratedDeltaf1
	UplinkpowercontrolcommonpscellR12DeltafPucchFormat1bcsR12EnumeratedDeltaf2
	UplinkpowercontrolcommonpscellR12DeltafPucchFormat1bcsR12EnumeratedSpare2
	UplinkpowercontrolcommonpscellR12DeltafPucchFormat1bcsR12EnumeratedSpare1
)
