package ies

import "rrc/utils"

// UplinkDataCompression-r17-newSetup-bufferSize-r17 ::= ENUMERATED
type UplinkdatacompressionR17NewsetupBuffersizeR17 struct {
	Value utils.ENUMERATED
}

const (
	UplinkdatacompressionR17NewsetupBuffersizeR17EnumeratedNothing = iota
	UplinkdatacompressionR17NewsetupBuffersizeR17EnumeratedKbyte2
	UplinkdatacompressionR17NewsetupBuffersizeR17EnumeratedKbyte4
	UplinkdatacompressionR17NewsetupBuffersizeR17EnumeratedKbyte8
	UplinkdatacompressionR17NewsetupBuffersizeR17EnumeratedSpare1
)
