package ies

import "rrc/utils"

// UplinkPowerControlCommonSCell-v1310-deltaF-PUCCH-Format3-r12 ::= ENUMERATED
type UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12 struct {
	Value utils.ENUMERATED
}

const (
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedNothing = iota
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf_1
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf0
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf1
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf2
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf3
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf4
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf5
	UplinkpowercontrolcommonscellV1310DeltafPucchFormat3R12EnumeratedDeltaf6
)
